const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const styles=new Map(),text={nodeValue:'Играть',parentElement:{closest:()=>false}};
const context={console,localStorage:{getItem:()=>null,setItem(){}},NodeFilter:{SHOW_TEXT:4},MutationObserver:class{observe(){}},document:{body:{dataset:{}},documentElement:{},head:{append(s){styles.set('#'+s.id,s)}},querySelector:s=>styles.get(s),createElement:()=>({}),createTreeWalker:()=>{let done=false;return{nextNode(){if(done)return null;done=true;return text;}}},addEventListener(){}}};
vm.createContext(context);vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../src/Spectra/Web/locales.js'),'utf8'),context);vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../src/Spectra/Web/appearance.js'),'utf8'),context);
vm.runInContext("SpectraAppearance.apply({language:'en',theme:'light',css:'.hero{display:none}'})",context);assert.equal(text.nodeValue,'Play');assert.equal(context.document.body.dataset.theme,'light');assert.equal(styles.get('#customThemeStyle').textContent,'.hero{display:none}');
vm.runInContext("SpectraAppearance.apply({language:'ru',theme:'gradient',colors:['#112233','#abcdef'],angle:90})",context);assert.equal(text.nodeValue,'Играть');assert(styles.get('#themeStyle').textContent.includes('linear-gradient(90deg,#112233,#abcdef)'));
const clean=vm.runInContext("SpectraAppearance.validate({language:'bad',theme:'bad',colors:['red','#123456'],angle:999})",context);assert.equal(clean.language,'ru');assert.equal(clean.angle,360);assert.equal(clean.colors.length,1);
vm.runInContext("SpectraAppearance.hydrate({theme:'steam'});SpectraAppearance.apply({theme:'aero'});SpectraAppearance.hydrate({theme:'steam'})",context);assert.equal(context.document.body.dataset.theme,'aero');
assert.equal(vm.runInContext("SpectraLocales.dictionary('de')['Исполняемый файл Java']",context),'Java-Programm');vm.runInContext("for(const [language,row] of Object.entries(SpectraLocales.rows)){if(row.split('|').length!==SpectraLocales.keys.length)throw Error(language+' locale length');}",context);vm.runInContext("SpectraAppearance.apply({theme:'windows'})",context);assert(styles.get('#themeStyle').textContent.includes('--theme-bg:#171717'));
vm.runInContext("for(const [language,row] of Object.entries(SpectraLocales.extraRows)){if(row.split('|').length!==SpectraLocales.extraKeys.length)throw Error(language+' extra locale length');}",context);assert.equal(vm.runInContext("SpectraLocales.dictionary('en')['Поиск версии…']",context),'Search versions…');assert.equal(vm.runInContext("SpectraLocales.dictionary('de')['ТВОЯ КОЛЛЕКЦИЯ']",context),'DEINE SAMMLUNG');
const nav={textContent:''},profile={textContent:'',hasAttribute:()=>true};const oldQuery=context.document.querySelector;context.document.querySelector=selector=>selector==='nav [data-page="discover"]'?nav:selector==='#profileTab'?profile:oldQuery(selector);
vm.runInContext("SpectraAppearance.apply({language:'en',theme:'dark'})",context);assert.equal(nav.textContent,'DISCOVER');assert.equal(profile.textContent,'PROFILE');vm.runInContext("SpectraAppearance.apply({language:'ru',theme:'dark'})",context);assert.equal(nav.textContent,'ОБЗОР');assert.equal(profile.textContent,'ПРОФИЛЬ');
assert.equal(vm.runInContext("SpectraLocales.dictionary('en')['Обзор']",context),'Discover');assert.equal(vm.runInContext("SpectraLocales.dictionary('en')['Профиль']",context),'Profile');
console.log('PASS: theme validation, CSS override, gradient and reversible translation');

vm.runInContext("SpectraAppearance.apply({theme:'dark',headingFont:'arial',bodyFont:'consolas'})",context);assert(styles.get('#themeStyle').textContent.includes("--heading-font:'Arial'"));assert(styles.get('#themeStyle').textContent.includes("--ui-font:'Consolas'"));
const invalid=vm.runInContext("SpectraAppearance.validate({headingFont:'Arial;bad',bodyFont:'custom:../file.ttf'})",context);assert.equal(invalid.headingFont,'pixel');assert.equal(invalid.bodyFont,'reading');
vm.runInContext("SpectraAppearance.apply({theme:'gradient',headingFont:'custom:'+ 'a'.repeat(64)+'.ttf',bodyFont:'reading'})",context);assert(styles.get('#themeStyle').textContent.includes('https://fonts.spectra.local/'+ 'a'.repeat(64)+'.ttf'));
vm.runInContext("SpectraAppearance.apply({theme:'windows',headingFont:'arial',bodyFont:'consolas'})",context);assert(!styles.get('#themeStyle').textContent.includes("--ui-font:'Consolas'"));
console.log('PASS: separate font roles, custom-font URLs, rejected font injection, themed font isolation');

vm.runInContext("SpectraAppearance.apply({theme:'steam',navigationPosition:'left'})",context);assert.equal(context.document.body.dataset.navigation,'left');assert.equal(vm.runInContext("SpectraAppearance.validate({navigationPosition:'sideways'}).navigationPosition",context),'top');vm.runInContext("SpectraAppearance.apply({navigationPosition:'bottom'});SpectraAppearance.apply({navigationPosition:'right'})",context);assert.equal(context.document.body.dataset.navigation,'right');console.log('PASS: navigation placement persists across themes and rejects invalid positions');
