const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const nodes=new Map(),listeners={},calls=[];const node=id=>{if(!nodes.has(id))nodes.set(id,{innerHTML:'',textContent:'',value:'version:1.21.4',disabled:false,isConnected:true,open:true,close(){this.open=false;}});return nodes.get(id);};
const state={instances:[],launcherFullscreen:false,bedrockSkinFolder:'C:/Downloads'},versions=[{id:'1.21.4'}];let result={status:'manualDownload',url:'https://example.test/map',message:'Use browser'};
const context={state,versions,localStorage:{getItem(){return null;},setItem(){}},document:{addEventListener(name,callback){listeners[name]=callback;}},$:(selector)=>node(selector.slice(1)),$$:()=>[],esc:String,heading:()=>'',closeButton:()=>'',getVersions:async()=>versions,run:fn=>Promise.resolve().then(fn),modal(html){node('modal').open=true;node('modal').innerHTML=html;},updateState(value){Object.assign(state,value);},toast(){},api:async(action,data)=>{calls.push({action,data});if(action==='window')state.launcherFullscreen=!state.launcherFullscreen;if(action==='contentDownload')return result;if(action==='state')return state;if(action==='bedrockSkinFolder'){state.bedrockSkinFolder='D:/Skins';return state;}},console};
vm.createContext(context);let source=fs.readFileSync(path.join(__dirname,'../src/Spectra/Web/content.js'),'utf8');source=source.replace('return {render,settings,additions};','return {render,settings,additions,targetDialog,perform};');vm.runInContext(source,context);
(async()=>{
 let prevented=false;listeners.keydown({key:'F11',repeat:false,preventDefault(){prevented=true;}});assert(prevented);assert.equal(calls.at(-1).data.command,'fullscreen');const count=calls.length;listeners.keydown({key:'F11',repeat:true,preventDefault(){}});assert.equal(calls.length,count);
 context.settingsHost={insertAdjacentHTML(){}};vm.runInContext('SpectraContent.settings(settingsHost)',context);await node('launcherFullscreen').onclick();assert.equal(state.launcherFullscreen,false);await node('pickBedrockSkinFolder').onclick();assert.equal(node('skinDownloadFolder').textContent,'D:/Skins');
 await vm.runInContext("SpectraContent.targetDialog(target=>SpectraContent.perform('contentDownload',{edition:'java',kind:'worlds',...target}))",context);await node('worldInstall').onclick();assert.equal(calls.find(x=>x.action==='contentDownload').data.version,'1.21.4');assert.equal(node('modal').open,true,'fallback download dialog must remain open');assert(node('modal').innerHTML.includes('importAfterDownload'));
 result={cancelled:false,message:'Done'};await vm.runInContext("SpectraContent.targetDialog(target=>SpectraContent.perform('contentDownload',target))",context);await node('worldInstall').onclick();assert.equal(node('modal').open,false);
 console.log('PASS: F11 ignores key repeat, settings toggle fullscreen and skin folder, map target is forwarded, manual-download fallback stays open');
})().catch(e=>{console.error(e);process.exitCode=1;});
