const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const nodes=new Map(),listeners={},calls=[];const node=id=>{if(!nodes.has(id))nodes.set(id,{innerHTML:'',textContent:'',value:'version:1.21.4',disabled:false,isConnected:true,open:true,insertAdjacentHTML(position,html){this.insertion={position,html};},addEventListener(name,callback){this['on'+name]=callback;},close(){this.open=false;}});return nodes.get(id);};
const state={instances:[],launcherFullscreen:false,bedrockSkinFolder:'C:/Downloads'},versions=[{id:'1.21.4'}];let result={status:'manualDownload',url:'https://example.test/map',message:'Use browser'};
const context={state,versions,localStorage:{getItem(){return null;},setItem(){}},document:{insertAdjacentHTML(position,html){this.insertion={position,html};},addEventListener(name,callback){listeners[name]=callback;}},$:(selector)=>node(selector.slice(1)),$$:()=>[],esc:String,heading:()=>'',closeButton:()=>'',getVersions:async()=>versions,run:fn=>Promise.resolve().then(fn),modal(html){node('modal').open=true;node('modal').innerHTML=html;},updateState(value){Object.assign(state,value);},toast(){},api:async(action,data)=>{calls.push({action,data});if(action==='window')state.launcherFullscreen=!state.launcherFullscreen;if(action==='contentDownload')return result;if(action==='state')return state;if(action==='bedrockSkinFolder'){state.bedrockSkinFolder='D:/Skins';return state;}},console};
vm.createContext(context);let source=fs.readFileSync(path.join(__dirname,'../src/Spectra/Web/content.js'),'utf8');source=source.replace('return {render,settings,additions};','return {render,settings,additions,targetDialog,perform};');vm.runInContext(source,context);
(async()=>{
 let prevented=false;listeners.keydown({key:'F11',repeat:false,preventDefault(){prevented=true;}});assert(prevented);assert.equal(calls.at(-1).data.command,'fullscreen');const count=calls.length;listeners.keydown({key:'F11',repeat:true,preventDefault(){}});assert.equal(calls.length,count);
 context.settingsHost={insertAdjacentHTML(){}};vm.runInContext('SpectraContent.settings(settingsHost)',context);await node('launcherFullscreen').onclick();assert.equal(state.launcherFullscreen,false);await node('pickBedrockSkinFolder').onclick();assert.equal(node('skinDownloadFolder').textContent,'D:/Skins');
 await vm.runInContext("SpectraContent.targetDialog(target=>SpectraContent.perform('contentDownload',{edition:'java',kind:'worlds',...target}))",context);await node('worldInstall').onclick();assert.equal(calls.find(x=>x.action==='contentDownload').data.version,'1.21.4');assert.equal(node('modal').open,true,'fallback download dialog must remain open');assert(node('modal').innerHTML.includes('importAfterDownload'));
 result={cancelled:false,message:'Done'};await vm.runInContext("SpectraContent.targetDialog(target=>SpectraContent.perform('contentDownload',target))",context);await node('worldInstall').onclick();assert.equal(node('modal').open,false);
 // Category selection changes the catalogue; removed providers are never requested.
 const contentCalls=[];const contentContext={...context,page:'discover',localStorage:{getItem(){return 'bedrock';},setItem(){}},image:()=>'',pixelIcon:()=>'',empty:()=>'',api:async(action,data)=>{contentCalls.push({action,data});if(action==='contentSearch')return {items:[],hasMore:false,warning:'',url:'https://www.curseforge.com/'};throw Error(action);}};
 node('contentQuery').value='test';vm.createContext(contentContext);vm.runInContext(source,contentContext);await vm.runInContext('SpectraContent.render()',contentContext);
 assert.equal(contentCalls.at(-1).data.source,'curseforge');assert.equal(contentCalls.at(-1).data.kind,'addons');assert(!node('main').innerHTML.includes('contentProvider'));
 node('contentKind').value='worlds';await node('contentKind').onchange();assert.equal(contentCalls.at(-1).data.kind,'worlds');assert.equal(contentCalls.at(-1).data.offset,0);
 node('contentKind').value='skins';await node('contentKind').onchange();assert.equal(contentCalls.at(-1).data.kind,'skins');assert.equal(contentCalls.at(-1).data.edition,'bedrock');
 const javaContext={...contentContext,localStorage:{getItem(){return 'java';},setItem(){}},renderModpacks:async()=>{node('main').innerHTML='<section><h1>Обзор</h1><div class="hero"></div><div class="toolbar"><input id="catalogQuery"></div></section>';}};
 vm.createContext(javaContext);vm.runInContext(source,javaContext);await vm.runInContext('SpectraContent.render()',javaContext);
 assert.equal(node('main .hero').insertion.position,'beforebegin');assert(node('main .hero').insertion.html.includes('Java Edition'));
 assert.equal(node('catalogQuery').insertion.position,'afterend');assert(node('catalogQuery').insertion.html.includes('МОДПАКИ'));assert(!node('catalogQuery').insertion.html.includes('СКИНЫ'));
 node('contentKind').value='worlds';await node('contentKind').onchange();assert.equal(contentCalls.at(-1).data.edition,'java');assert.equal(contentCalls.at(-1).data.kind,'worlds');
 console.log('PASS: catalogue category selection switches Bedrock content without a provider selector');
 console.log('PASS: F11 ignores key repeat, settings toggle fullscreen and skin folder, map target is forwarded, manual-download fallback stays open');
})().catch(e=>{console.error(e);process.exitCode=1;});
