const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const elements=new Map(),listeners={};let lastAnimation,resolveFriends,calls=[];
function element(id){if(!elements.has(id))elements.set(id,{id,hidden:true,value:'',dataset:{},checked:false,disabled:false,addEventListener(type,fn){this['on'+type]=fn;},focus(){},setSelectionRange(){},animate(frames,options){lastAnimation={frames,options,cancel(){}};return lastAnimation;},insertAdjacentHTML(where,html){this.innerHTML+=html;},get innerHTML(){return this.html||'';},set innerHTML(html){this.html=html;this.nodes=[];for(const match of html.matchAll(/<(?:button|input|select|span)[^>]*>/g)){const tag=match[0],id=tag.match(/id="([^"]+)"/)?.[1];const node=id?element(id):{dataset:{},checked:false};node.dataset={};for(const attr of tag.matchAll(/data-([a-z-]+)="([^"]*)"/g))node.dataset[attr[1].replace(/-([a-z])/g,(_,x)=>x.toUpperCase())]=attr[2];node.checked=/\schecked(?:\s|>)/.test(tag);if(Object.keys(node.dataset).length)this.nodes.push(node);}},close(){this.open=false;}});return elements.get(id);}
const panel=element('friendsPanel');element('friendsButton');element('accountMenu');const escaped=x=>String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const state={profile:{id:'minecraft',name:'Player'},networkAccount:{name:'Player',id:'network',minecraftName:'Player',minecraftVerified:true},friendsEndpoint:'https://friends.test',instances:[],running:[],shareGameActivity:true,hideOnlineStatus:false};
const context={console,state,window:{},setInterval(){},setTimeout(){},Date,Set,matchMedia:()=>({matches:false}),$:selector=>selector.startsWith('#')?element(selector.slice(1)):null,$$:selector=>{const m=selector.match(/\[data-([a-z-]+)\]/);if(!m)return [];const key=m[1].replace(/-([a-z])/g,(_,x)=>x.toUpperCase());return [...elements.values()].flatMap(e=>e.nodes||[]).filter(n=>n.dataset[key]!==undefined&&(!selector.endsWith(':checked')||n.checked));},esc:escaped,closeButton:()=>'',toast(){},navigate(){},modal(html){const m=element('modal');m.innerHTML=html;m.open=true;},updateState(x){Object.assign(state,x);},run:fn=>Promise.resolve().then(fn),document:{addEventListener(name,fn){listeners[name]=fn;}},api:async(action,data)=>{calls.push({action,data});if(action==='friends')return new Promise(r=>resolveFriends=r);if(action==='friendPackPlan')return {matching:[],packId:'pack',presence:data.id==='menu-friend'?{playing:true,gameState:'menu',targetKind:'',target:''}:{playing:true,gameState:'server',targetKind:'servers',target:'mc.test:25565'},manifest:{name:'Custom pack',version:'1.21',loader:'fabric',loaderVersion:'0.16',files:[{kind:'mods',name:'core.jar',size:100},{kind:'mods',name:'extra.jar',size:200},{kind:'shaders',name:'shader.zip',size:500},{kind:'resources',name:'texture.zip',size:900}]}};if(action==='installFriendPack')return {instanceId:'installed',presence:data.id==='menu-friend'?{playing:true,gameState:'menu',targetKind:'',target:''}:{playing:true,gameState:'server',targetKind:'servers',target:'mc.test:25565'},state:{instances:[{id:'installed',name:'Custom pack'}]}};if(action==='files')return [];if(action==='serverAction')return {};if(action==='joinFriend')return {};if(action==='friendsSettings')return {hideOnlineStatus:data.hideOnline,shareGameActivity:data.shareActivity};throw Error(action);}};
vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../src/Spectra/Web/friends.js'),'utf8'),context);
(async()=>{
 element('friendsButton').onclick();assert.equal(panel.hidden,false);assert.equal(lastAnimation.options.duration,220);
 resolveFriends({items:[{id:'friend',name:'<script>',relation:'friend',online:true,presence:{playing:true,sharedPack:'pack',version:'1.21',loader:'fabric',targetKind:'servers',target:'mc.test:25565'}}]});await new Promise(setImmediate);assert(panel.innerHTML.includes('&lt;script&gt;'));assert(!panel.innerHTML.includes('><script>'));
 element('friendsClose').onclick();assert.equal(panel.hidden,false);assert.equal(lastAnimation.options.duration,160);lastAnimation.onfinish();assert.equal(panel.hidden,true);
 element('friendsButton').onclick();assert.equal(panel.hidden,false);listeners.pointerdown({target:{closest:()=>null}});const old=lastAnimation;assert.equal(old.options.duration,160);element('friendsButton').onclick();assert.equal(panel.hidden,false);assert.equal(lastAnimation.options.duration,220); // reopen cancels the outgoing animation
 const host=element('networkAccountSettings');context.window.SpectraFriends.profile(state.profile,true);assert(host.innerHTML.includes('hideSpectraOnline'));assert(host.innerHTML.includes('hideSpectraGame'));element('hideSpectraOnline').checked=true;element('hideSpectraGame').checked=true;await element('friendPrivacy').onsubmit({preventDefault(){}});await new Promise(setImmediate);
 const save=calls.find(c=>c.action==='friendsSettings');assert.equal(save.data.hideOnline,true);assert.equal(save.data.shareActivity,false);assert.equal(state.hideOnlineStatus,true);
 // Open the actual file-selection dialog and submit only the checked Mods category.
 resolveFriends({items:[{id:'friend',name:'Friend',relation:'friend',online:true,presence:{playing:true,sharedPack:'pack',version:'1.21',loader:'fabric',targetKind:'servers',target:'mc.test:25565'}}]});await new Promise(setImmediate);
 const join=context.$$(' [data-friend-join]')[0];assert(join);await join.onclick();await new Promise(setImmediate);assert(element('modal').innerHTML.includes('friendPackInstall'));
 const categories=context.$$('[data-pack-category]');assert.equal(categories.filter(n=>n.checked).map(n=>n.dataset.packCategory).join(','),'mods');context.$$('[data-pack-file]').find(n=>n.dataset.packFile==='mods/extra.jar').checked=false;
 await element('friendPackInstall').onsubmit({preventDefault(){}});await new Promise(setImmediate);const install=calls.find(c=>c.action==='installFriendPack');assert.equal(install.data.categories.join(','),'mods');assert.equal(install.data.selected.join(','),'mods/core.jar');assert.equal(install.data.overwrite,'');
 await element('playInstalledFriend').onclick();await new Promise(setImmediate);assert.equal(calls.find(c=>c.action==='serverAction').data.address,'mc.test:25565');assert.equal(calls.find(c=>c.action==='joinFriend').data.allowCustomized,true);
 // A running game in its main menu still exposes Download, but not Connect.
 if(lastAnimation.onfinish)lastAnimation.onfinish();element('friendsButton').onclick();const menuList={items:[{id:'menu-friend',name:'MenuFriend',relation:'friend',online:true,presence:{playing:true,gameState:'menu',version:'1.21',loader:'fabric',targetKind:'',target:'',sharedPack:'pack'}}]};resolveFriends(menuList);await new Promise(setImmediate);resolveFriends(menuList);await new Promise(setImmediate);
 assert(panel.innerHTML.includes('Главное меню / загрузка'));assert.equal(context.$$('[data-friend-join]').length,0);assert.equal(context.$$('[data-friend-download]').length,1);
 await context.$$('[data-friend-download]')[0].onclick();assert(element('modal').innerHTML.includes('friendPackInstall'));assert(!element('modal').innerHTML.includes('id="joinMatchingFriend"'));await element('friendPackInstall').onsubmit({preventDefault(){}});await new Promise(setImmediate);assert(element('modal').innerHTML.includes('Сборка установлена'));assert(!element('modal').innerHTML.includes('id="playInstalledFriend"'));assert(!element('modal').innerHTML.includes('id="addFriendServer"'));
 // Vanilla keeps Connect but suppresses Download even if an old presence contains sharedPack.
 if(lastAnimation.onfinish)lastAnimation.onfinish();element('friendsButton').onclick();const vanillaList={items:[{id:'vanilla-friend',name:'VanillaFriend',relation:'friend',online:true,presence:{playing:true,version:'1.21',loader:'vanilla',targetKind:'servers',target:'mc.test',sharedPack:'stale-pack'}}]};resolveFriends(vanillaList);await new Promise(setImmediate);resolveFriends(vanillaList);await new Promise(setImmediate);
 assert.equal(context.$$('[data-friend-download]').length,0);assert.equal(context.$$('[data-friend-join]').length,1);const plans=calls.filter(c=>c.action==='friendPackPlan').length;
 await context.$$('[data-friend-join]')[0].onclick();assert(element('modal').innerHTML.includes('joinVanillaFriend'));assert.equal(calls.filter(c=>c.action==='friendPackPlan').length,plans);await element('joinVanillaFriend').onclick();assert.equal(calls.at(-1).action,'joinFriend');assert.equal(calls.at(-1).data.instanceId,'vanilla');
 console.log('PASS: friend-panel animations, reopening, escaped names privacy, selective install, server addition and pack download while friend is in menu');
})().catch(e=>{console.error(e);process.exitCode=1;});
