const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const draws=[];
function element(tag='div'){return {tag,style:{},dataset:{},isConnected:true,children:[],append(x){this.children.push(x)},replaceChildren(...xs){this.children=xs},setAttribute(){},getContext(){return {drawImage(...args){draws.push(args.slice(1))}}},toDataURL(){return 'data:image/png;base64,test'}};}
const context={document:{createElement:element},Map,Promise,console};vm.createContext(context);vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../src/Spectra/Web/skin-preview.js'),'utf8'),context);
(async()=>{context.host=element();vm.runInContext("skinTextures.set('skin:https://test/skin',Promise.resolve({width:64,height:64}))",context);await vm.runInContext("mountSkin(host,'https://test/skin','classic')",context);
 const cubes=context.host.children[0].children;assert.equal(cubes.length,12);const base=cubes[0],hat=cubes[1];const front=x=>x.children.find(f=>f.className==='skin-plane front');assert.notEqual(front(base).style.transform,front(hat).style.transform);assert.equal(hat.style.width,'63px');assert.equal(base.style.width,'56px');assert.notEqual(front(cubes[2]).style.transform,front(cubes[7]).style.transform);
 context.pair=element();draws.length=0;await vm.runInContext("paintSkinPair(pair,'https://test/skin','slim')",context);assert.equal(context.pair.children[0].width,36);assert(draws.some(a=>a[0]===8&&a[1]===8));assert(draws.some(a=>a[0]===24&&a[1]===8));context.cape=element();vm.runInContext("skinTextures.set('cape:https://test/cape',Promise.resolve({width:64,height:32}))",context);draws.length=0;await vm.runInContext("paintCape(cape,'https://test/cape')",context);assert.equal(context.cape.children[0].width,23);assert(draws.some(a=>a[0]===1&&a[1]===1));assert(draws.some(a=>a[0]===12&&a[1]===1));
 console.log('PASS: outer layers have separate depth; front/back texture patches and pair canvas');
})().catch(e=>{console.error(e);process.exit(1)});
