'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeImage=u=>/^(https:\/\/|data:image\/(png|jpeg|webp);base64,)/.test(u||'')?u:'';
const image=(u,cls='')=>safeImage(u)?`<img class="${cls}" src="${esc(u)}" loading="lazy" decoding="async" referrerpolicy="no-referrer" alt="">`:'';
const pixelIcon=name=>`<span class="pixel-icon" style="--icon-mask:url('assets/${esc(name)}.svg')" aria-hidden="true"><img src="assets/${esc(name)}.svg" alt=""></span>`;
const pending=new Map();let seq=0,state={instances:[],defaults:{minRam:512,maxRam:4096,width:1280,height:720,javaPath:'',gpu:'system'},profile:null,running:[]},versions=[],versionArt={},page='instances',editorId=null,editorTab='logs',searchTimer,viewSeq=0;
const logs=new Map(), busy=new Set();
const preview=!window.chrome?.webview;
async function api(action,data={}){
 if(preview)return previewApi(action,data);
 const id=String(++seq);return new Promise((resolve,reject)=>{pending.set(id,{resolve,reject});window.chrome.webview.postMessage({id,action,data});});
}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,6000);}
async function run(fn){try{return await fn();}catch(e){toast(e.message||String(e));return null;}}
function bind(root=document){root.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page));}
function date(s){return s?new Date(s).toLocaleDateString(SpectraAppearance.language(),{day:'numeric',month:'short',year:'numeric'}):'Ещё не запускалась';}
let latestCommitLabel=null;
function updateState(s){if(!s)return;state=s;const build=$('#installedVersion');if(build){build.textContent=latestCommitLabel?.name||s.installedCommitName||s.installedCommit?.slice(0,7)||'0.14.1';build.title=latestCommitLabel?latestCommitLabel.name+' · GitHub '+latestCommitLabel.sha+' · installed '+(s.installedCommit||'unknown'):(s.installedCommit||'0.14.1');build.setAttribute('data-no-i18n','');}SpectraAppearance.hydrate(s.appearance);const name=state.profile?.name||'Войти';$('#accountName').textContent=name;$('#profileTab').textContent=state.profile?.name?.toUpperCase()||'ПРОФИЛЬ';if(state.profile?.name)$('#profileTab').removeAttribute('data-i18n');else $('#profileTab').setAttribute('data-i18n','ПРОФИЛЬ');SpectraAppearance.navigation();$('.avatar').textContent=name[0];if(state.profile)paintFace($('.avatar'),skinUrl(state.profile));renderQuick();syncPlayButtons();if(typeof SpectraShell!=='undefined')SpectraShell.refresh();}
function onMessage(m){
 if(m.type==='windowState'){const button=$('[data-window="maximize"]');button?.setAttribute('aria-pressed',String(m.maximized));button?.setAttribute('aria-label',m.maximized?'Восстановить':'Развернуть');return;}
 if(m.type==='reply'){const p=pending.get(m.id);if(p){pending.delete(m.id);m.ok?p.resolve(m.result):p.reject(new Error(m.error));}return;}
 if(m.type==='auth'){if(!$('#boot').hidden)$('#bootStatus').textContent=m.message;if(m.state==='waiting')$('#status').textContent='Ожидаем Microsoft';return;}
 if(m.type==='transferComplete'){$('#status').textContent=state.running.length?'Minecraft запущен':'Готов к приключениям';$('#progressText').textContent='';$('#progressBar').style.width='0%';$('#progressTrack').classList.remove('indeterminate');return;}
 if(m.type==='progress'){if(sourceUpdateRunning){$('#updateDetail').textContent=(m.message||'Подготовка')+(m.downloadedBytes!=null?' · '+bytes(m.downloadedBytes)+' / '+(m.totalBytes>0?bytes(m.totalBytes)+' · осталось '+bytes(Math.max(0,m.totalBytes-m.downloadedBytes)):'размер неизвестен'):'');$('#updateTrack').classList.toggle('indeterminate',!(m.percent>0));$('#updateBar').style.width=Math.max(0,Math.min(100,m.percent||0))+'%';}$('#status').textContent='Загрузка';$('#progressText').textContent=(m.message||'Подготовка')+(m.downloadedBytes!=null?' · '+bytes(m.downloadedBytes)+' / '+(m.totalBytes>0?bytes(m.totalBytes):'размер неизвестен')+(m.scope==='file'?' · текущий файл':' · текущий этап'):'');$('#progressTrack').classList.toggle('indeterminate',m.downloadedBytes!=null&&!(m.totalBytes>0));$('#progressBar').style.width=Math.max(0,Math.min(100,m.percent||0))+'%';return;}
 if(m.type==='logBatch'){for(const item of m.items||[])onMessage(item);return;}
 if(m.type==='log'){const a=logs.get(m.instanceId)||[];a.push(m.line);if(a.length>5000)a.splice(0,a.length-5000);logs.set(m.instanceId,a);if(editorId===m.instanceId&&editorTab==='logs')scheduleLogPaint(m.instanceId);return;}
 if(m.type==='started'){busy.delete(m.instanceId);state.running=[...new Set([...state.running,m.instanceId])];$('#status').textContent='Minecraft запущен';$('#progressText').textContent='';$('#progressBar').style.width='0%';syncPlayButtons();if(editorId===m.instanceId)renderEditor();return;}
 if(m.type==='exited'){state.running=state.running.filter(x=>x!==m.instanceId);toast(`Игра закрыта · код ${m.code}`);$('#status').textContent='Готов к приключениям';syncPlayButtons();if(editorId===m.instanceId)renderEditor();}
}
let logPaintTimer=0;
function scheduleLogPaint(id){if(logPaintTimer)return;logPaintTimer=setTimeout(()=>{logPaintTimer=0;if(editorId!==id||editorTab!=='logs')return;const p=$('#liveLog');if(!p||p.dataset.archive)return;const bottom=p.scrollHeight-p.scrollTop-p.clientHeight<45;p.textContent=(logs.get(id)||[]).join('\n');if(bottom)p.scrollTop=p.scrollHeight;},100);}
window.chrome?.webview?.addEventListener('message',e=>onMessage(e.data));
function openShell(){ $('#updateScreen').hidden=true;$('#boot').hidden=true;$('#shell').hidden=false;renderQuick();navigate('instances'); }
async function login(interactive=true){$('#signIn').disabled=true;try{updateState(await api('login',{interactive}));openShell();}finally{$('#signIn').disabled=false;}}
$$('[data-window]').forEach(b=>b.onclick=()=>api('window',{command:b.dataset.window}));$('#titlebar').onmousedown=e=>{if(e.button===0&&!e.target.closest('button'))api('window',{command:'drag'});};$('#titlebar').ondblclick=e=>{if(!e.target.closest('button'))api('window',{command:'maximize'});};
$('#account').onclick=()=>$('#accountMenu').hidden=!$('#accountMenu').hidden;document.addEventListener('click',e=>{if(!e.target.closest('#account,#accountMenu'))$('#accountMenu').hidden=true;});
$('#signIn').onclick=()=>run(()=>login());$('#switchAccount').onclick=()=>run(()=>login());$('#logout').onclick=()=>run(async()=>{updateState(await api('logout'));$('#shell').hidden=true;$('#boot').hidden=false;$('#accountMenu').hidden=true;});
$('#bootSettings').onclick=()=>configurationModal();$('#libraryOnly').onclick=()=>run(async()=>{updateState(await api('expand'));openShell();});
async function navigate(target){profileRequest++;page=target;editorId=null;viewSeq++;$('#accountMenu').hidden=true;$$('nav [data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===target));if(target==='instances')renderInstances();else if(target==='versions')await renderVersions();else if(target==='discover')await renderDiscover();else if(target==='profile')renderProfile();else if(target==='settings')renderSettings();}
function heading(eyebrow,title,actions=''){return `<div class="heading"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1></div><div class="small-gap">${actions}</div></div>`;}
function empty(title,subtitle,symbol='◈'){return `<div class="empty"><span class="symbol">${symbol}</span><h3>${title}</h3><p>${subtitle}</p></div>`;}
function renderInstances(){
 $('#main').innerHTML=`<section>${heading('ТВОЯ КОЛЛЕКЦИЯ','Сборки',`${viewButtons('instances')}<button id="importInstance">Prism / MultiMC ZIP</button><button id="importPack">${pixelIcon('down')} Импорт модпака</button><button class="primary" id="createInstance">${pixelIcon('plus')} Создать сборку</button>`)}<div class="hero"><div><div class="eyebrow">MINECRAFT, ПО-ТВОЕМУ</div><h2>Место для твоих миров.</h2><p>Любимая версия, нужные моды и собственная атмосфера.<br>Каждое приключение начинается здесь.</p></div><button id="heroBrowse">Найти новую сборку ${pixelIcon('arrow')}</button></div><div class="section-label"><h2>Моя библиотека <span class="muted"> / ${state.instances.length}</span></h2><span class="muted">Изолированные папки · Индивидуальные настройки</span></div><div class="instance-list view-${esc(state.views?.instances||'cards')}">${state.instances.map(instanceCard).join('')||empty('Первое приключение ещё впереди','Создайте сборку или найдите готовый модпак в обзоре.')}</div></section>`;
 bindViews();syncPlayButtons();$('#createInstance').onclick=()=>instanceModal();$('#heroBrowse').onclick=()=>navigate('discover');$('#importInstance').onclick=()=>run(async()=>{updateState(await api('importInstance'));renderInstances();});$('#importPack').onclick=()=>run(async()=>{updateState(await api('importPack'));renderInstances();toast('Импорт завершён');});
 $$('.instance-card').forEach(c=>{const id=c.dataset.id;c.querySelector('[data-delete]').onclick=()=>confirmAction('Удалить сборку?', 'Будут удалены сборка, её миры и файлы.',async()=>{updateState(await api('deleteInstance',{instanceId:id}));renderInstances();});c.querySelector('[data-edit]').onclick=()=>openEditor(id,'version');c.querySelector('[data-launch]').onclick=()=>run(async()=>{await choose('',id);await playAction(id);});c.querySelectorAll('[data-folder]').forEach(b=>b.onclick=()=>run(()=>api('openFolder',{instanceId:id,kind:b.dataset.folder})));c.querySelector('[data-export]').onclick=()=>exportModal(id);c.querySelector('[data-shots]').onclick=()=>openEditor(id,'screenshots');});
}
function instanceCard(i){return `<article class="instance-card" data-id="${esc(i.id)}"><div class="card-bg">${image(i.banner)}</div><div class="card-gradient"></div><div class="instance-icon">${image(i.icon)||pixelIcon('cube')}</div><div class="instance-meta"><h3>${esc(i.name)}</h3><span class="muted">Minecraft ${esc(i.version)} &nbsp;·&nbsp; ${esc(i.loader)} ${esc(i.loaderVersion)}</span><p class="muted">${date(i.lastPlayed)}</p></div><div class="card-actions"><button class="icon-button" data-delete title="Удалить сборку">×</button><button class="icon-button" data-edit title="Редактировать">${pixelIcon('edit')}</button><button class="icon-button" data-export title="Экспорт Prism / MultiMC">${pixelIcon('down')}</button><button class="icon-button" data-shots title="Скриншоты">${pixelIcon('shots')}</button><button class="icon-button" data-folder="minecraft" title="Открыть .minecraft">${pixelIcon('home')}</button><button class="icon-button" data-folder="instance" title="Папка сборки">${pixelIcon('folder')}</button><button class="icon-button" data-folder="mods" title="Моды">${pixelIcon('mods')}</button><button class="icon-button" data-folder="shaders" title="Шейдеры">${pixelIcon('sun')}</button><button class="icon-button" data-folder="resources" title="Ресурс паки">${pixelIcon('pack')}</button><button class="primary play" data-launch>${state.running.includes(i.id)?'Игра запущена':pixelIcon('play')+' Играть'}</button></div></article>`;}
async function getVersions(){if(!versions.length)versions=await api('versions');return versions;}
async function renderVersions(){
 if(typeof SpectraBedrock!=='undefined'&&localStorage.getItem('spectra.versionEdition')==='bedrock')return SpectraBedrock.render();
 const token=viewSeq;$('#main').innerHTML=`<section>${heading('JAVA EDITION','Версии',viewButtons('versions'))}${typeof SpectraBedrock!=='undefined'?SpectraBedrock.switcher('java'):''}<div class="toolbar"><select id="sort"><option value="new">Сначала новые</option><option value="old">Сначала старые</option></select><label><input id="snapshots" type="checkbox"> Снапшоты</label><label><input id="beta" type="checkbox"> Бета</label><label><input id="alpha" type="checkbox"> Альфа</label><input id="versionSearch" placeholder="Поиск версии…" aria-label="Поиск версии"></div><div class="version-list view-${esc(state.views?.versions||'cards')}" id="versionList">${empty('Получаем официальный список','Соединяемся с Mojang…')}</div><div class="form-actions"><button id="moreVersions" hidden>Показать ещё</button></div></section>`;
 bindViews();if(typeof SpectraBedrock!=='undefined')SpectraBedrock.bindSwitcher();await run(async()=>{await getVersions();if(token!==viewSeq)return;renderQuick();let limit=24;function fill(){const query=$('#versionSearch').value.toLowerCase();let list=versions.filter(v=>v.id.toLowerCase().includes(query)&&(v.type==='release'||v.type==='snapshot'&&$('#snapshots').checked||v.type==='old_beta'&&$('#beta').checked||v.type==='old_alpha'&&$('#alpha').checked));if($('#sort').value==='old')list=[...list].reverse();$('#versionList').innerHTML=list.slice(0,limit).map(v=>`<article class="version-card ${!state.selection?.instanceId&&state.selection?.version===v.id?'selected':''}" tabindex="0" role="button" data-version="${esc(v.id)}"><div class="version-art">${image(versionArt[v.id])}<span>${esc(v.id)}</span></div><div><h3>Minecraft ${esc(v.id)}</h3><span class="muted">${date(v.releaseTime)}</span></div><span class="pill">${esc(v.type.toUpperCase())}</span><button class="version-play" data-play-version="${esc(v.id)}">${pixelIcon('play')} Играть</button></article>`).join('')||empty('Версия не найдена','Попробуйте изменить поиск или включить другие категории.');$('#moreVersions').hidden=list.length<=limit;$$('[data-version]').forEach(b=>{b.onclick=e=>{if(!e.target.closest('[data-play-version]'))run(()=>choose(b.dataset.version,''));};b.onkeydown=e=>{if(e.key==='Enter'&&e.target===b)b.click();};});$$('[data-play-version]').forEach(b=>b.onclick=e=>{e.stopPropagation();run(async()=>{await choose(b.dataset.playVersion,'');await launch('vanilla');});});}
 ['sort','snapshots','beta','alpha','versionSearch'].forEach(id=>$('#'+id).oninput=()=>{limit=24;clearTimeout(searchTimer);if(id==='versionSearch')searchTimer=setTimeout(fill,120);else fill();});$('#moreVersions').onclick=()=>{limit+=24;fill();};fill();api('artwork').then(art=>{versionArt=art;renderQuick();if(token===viewSeq)fill();}).catch(()=>{});});
}
function modal(html){$('#modal').classList.remove('screenshot-dialog','project-dialog');$('#modalContent').innerHTML=html;$('#modal').showModal();$('.modal-close')?.addEventListener('click',()=>$('#modal').close());}
function closeButton(){return '<button class="modal-close" aria-label="Закрыть">×</button>';}
function creationVersions(list,flags={}){return list.filter(v=>v.type==='release'||v.type==='snapshot'&&flags.snapshots||v.type==='old_beta'&&flags.beta||v.type==='old_alpha'&&flags.alpha);}
async function instanceModal(existing=null,version=''){
 const i=existing?structuredClone(existing):{name:'',version,loader:'vanilla',loaderVersion:'',icon:'',banner:'',settings:structuredClone(state.defaults)};
 modal(`${closeButton()}<h2>${existing?'Редактировать сборку':'Новая сборка'}</h2><p>Соберите своё пространство для игры.</p><form id="instanceForm"><div class="form-grid"><label class="wide">Название<input id="instanceName" value="${esc(i.name)}" placeholder="Например, Тихая долина" maxlength="80" required></label><div class="wide toolbar"><label><input type="checkbox" id="createSnapshots"> Снапшоты</label><label><input type="checkbox" id="createBeta"> Бета</label><label><input type="checkbox" id="createAlpha"> Альфа</label></div><label>Minecraft<select id="mcVersion" required><option>Загрузка…</option></select></label><label>Загрузчик<select id="loader">${['vanilla','fabric','forge','quilt','neoforge'].map(l=>`<option value="${l}" ${i.loader===l?'selected':''}>${l==='vanilla'?'Vanilla':l}</option>`).join('')}</select></label><label class="wide">Версия загрузчика<select id="loaderVersion"><option value="">Не требуется</option></select><span id="loaderHint" class="muted"></span></label><div class="wide artwork-picker"><button type="button" id="pickIcon">▧ Выбрать иконку</button><button type="button" id="pickBanner">▧ Выбрать баннер</button></div><div class="wide" id="artPreview">${i.banner?image(i.banner,'artwork-preview'):''}</div></div><div class="form-actions"><button type="button" id="cancel">Отмена</button><button class="primary" id="saveInstance" type="submit">Сохранить сборку</button></div></form>`);
 $('#cancel').onclick=()=>$('#modal').close();$('#pickIcon').onclick=()=>run(async()=>{const p=await api('pickImage');if(p){i.icon=p;toast('Иконка выбрана');}});$('#pickBanner').onclick=()=>run(async()=>{const p=await api('pickImage');if(p){i.banner=p;$('#artPreview').innerHTML=image(p,'artwork-preview');}});
 let loaderRequest=0;
 async function loaders(){const request=++loaderRequest;$('#loaderVersion').disabled=true;$('#saveInstance').disabled=true;$('#loaderHint').textContent='Получаем совместимые версии…';try{const list=await api('loaders',{version:$('#mcVersion').value,loader:$('#loader').value});if(request!==loaderRequest)return;const selected=list.find(x=>x.version===i.loaderVersion)||list.find(x=>x.recommended)||list[0];$('#loaderVersion').innerHTML=list.length?list.map(x=>`<option value="${esc(x.version)}" ${selected?.version===x.version?'selected':''}>${esc(x.version)}${x.recommended?' · Рекомендованная':''}</option>`).join(''):'<option value="">Не требуется</option>';const vanilla=$('#loader').value==='vanilla';$('#loaderVersion').disabled=vanilla;$('#loaderHint').textContent=!vanilla&&!list.length?'Совместимых версий нет':'';$('#saveInstance').disabled=!vanilla&&!list.length;}catch(e){$('#loaderHint').textContent=e.message;}}
 async function filterCreationVersions(){const selected=$('#mcVersion').value||i.version;$('#mcVersion').innerHTML=creationVersions(versions,{snapshots:$('#createSnapshots').checked,beta:$('#createBeta').checked,alpha:$('#createAlpha').checked}).map(v=>`<option value="${esc(v.id)}" ${v.id===selected?'selected':''}>${esc(v.id)} · ${esc(v.type)}</option>`).join('');await loaders();}await run(async()=>{await getVersions();await filterCreationVersions();});for(const id of ['createSnapshots','createBeta','createAlpha'])$('#'+id).onchange=()=>run(filterCreationVersions);$('#mcVersion').onchange=loaders;$('#loader').onchange=loaders;
 $('#instanceForm').onsubmit=e=>{e.preventDefault();run(async()=>{$('#saveInstance').disabled=true;i.name=$('#instanceName').value.trim();i.version=$('#mcVersion').value;i.loader=$('#loader').value;i.loaderVersion=$('#loaderVersion').value;try{updateState(await api('saveInstance',i));$('#modal').close();if(editorId)openEditor(i.id,'version');else navigate('instances');}finally{if($('#saveInstance'))$('#saveInstance').disabled=false;}});};
}
async function launch(id){
 if(state.running.includes(id)){openEditor(id,'logs');return;}if(busy.has(id))return;busy.add(id);syncPlayButtons();logs.set(id,[]);openEditor(id,'logs');
 const result=await run(()=>api('launch',{instanceId:id}));busy.delete(id);syncPlayButtons();if(result)updateState(result);else{$('#status').textContent='Запуск не завершён';$('#progressText').textContent='';$('#progressBar').style.width='0%';}if(editorId===id)renderEditor();
}
const tabs=[['logs','ЛОГИ'],['version','ВЕРСИЯ'],['mods','МОДЫ'],['shaders','ШЕЙДЕРЫ'],['resources','РЕСУРС ПАКИ'],['worlds','МИРЫ'],['servers','СЕРВЕРЫ'],['screenshots','СКРИНШОТЫ'],['settings','НАСТРОЙКИ']];
function openEditor(id,tab){page='instances';editorId=id;editorTab=tab;viewSeq++;renderEditor();}
async function renderEditor(){
 const i=findInstance(editorId);if(!i)return navigate('instances');const token=++viewSeq;
 $('#main').innerHTML=`<section><div class="editor-head"><button id="back">←</button><div class="instance-icon">${image(i.icon)||pixelIcon('cube')}</div><div class="instance-meta"><div class="eyebrow">РЕДАКТОР СБОРКИ</div><h1>${esc(i.name)}</h1><p class="muted">${esc(i.version)} · ${esc(i.loader)} ${esc(i.loaderVersion)}</p></div><button id="editIdentity">Оформление</button><button class="primary" id="editorPlay">${state.running.includes(i.id)?'■ Остановить':busy.has(i.id)?'Подготовка…':'▷ Играть'}</button></div><div class="editor-layout"><div id="editorContent"></div><aside class="editor-tabs">${tabs.map(([id,t])=>`<button data-tab="${id}" class="${editorTab===id?'active':''}">${t}</button>`).join('')}</aside></div></section>`;
 $('#back').onclick=()=>navigate('instances');$('#editIdentity').hidden=i.id==='vanilla';$('#editIdentity').onclick=()=>instanceModal(i);$('#editorPlay').onclick=()=>state.running.includes(i.id)?run(()=>api('stop',{instanceId:i.id})):launch(i.id);$('#editorPlay').disabled=busy.has(i.id);
 $$('[data-tab]').forEach(b=>b.onclick=()=>{editorTab=b.dataset.tab;renderEditor();});
 if(editorTab==='version'){ $('#editorContent').innerHTML=`<div class="panel"><h2>Компоненты версии</h2><table class="component-table"><thead><tr><th>Состояние</th><th>Компонент</th><th>Версия</th></tr></thead><tbody><tr><td class="check">✓</td><td>Minecraft</td><td>${esc(i.version)}</td></tr>${i.loader!=='vanilla'?`<tr><td class="check">✓</td><td>${esc(i.loader)} Loader</td><td>${esc(i.loaderVersion)}</td></tr>`:''}<tr><td class="check">↳</td><td>LWJGL и библиотеки</td><td>Из манифеста Mojang</td></tr></tbody></table><div class="form-actions"><button id="versionFolder">Открыть .minecraft</button><button class="primary" id="changeVersion">Изменить версию</button></div></div>`;$('#changeVersion').onclick=()=>i.id==='vanilla'?navigate('versions'):instanceModal(i);$('#versionFolder').onclick=()=>run(()=>api('openFolder',{instanceId:i.id,kind:'minecraft'}));run(async()=>{const rows=await api('components',{instanceId:i.id});if(token===viewSeq)$('#editorContent tbody').innerHTML=rows.map(x=>`<tr><td class="check">✓</td><td>${esc(x.name)}</td><td>${esc(x.version)}</td></tr>`).join('');});return; }
 if(editorTab==='settings'&&i.id==='vanilla'){ $('#editorContent').innerHTML='<div class="panel"><h2>Настройки обычного Minecraft</h2><p>Используются общие параметры лаунчера.</p><button data-page="settings">Открыть настройки</button></div>';bind($('#editorContent'));return;}
 if(editorTab==='settings'){ $('#editorContent').innerHTML=settingsForm(i.settings,false);bindSettings(false,i);return; }
 const kind=editorTab;
 if(kind==='logs')$('#editorContent').innerHTML=`<div class="log-layout"><aside class="log-files" id="logFiles"><button id="live">● Текущий запуск</button></aside><pre class="log" id="liveLog"></pre></div>`;
 else $('#editorContent').innerHTML=`<div class="toolbar"><h2>${tabs.find(t=>t[0]===kind)[1]}</h2><span class="nav-spacer"></span><button id="folder">▱ Папка</button>${['mods','shaders','resources'].includes(kind)?'<button id="download" class="primary">↓ Скачать</button>':''}</div><div id="fileList">${empty('Загрузка файлов','Читаем папку сборки…')}</div>`;
 await run(async()=>{const files=await api('files',{instanceId:i.id,kind});if(token!==viewSeq)return;
  if(kind==='logs'){$('#liveLog').textContent=(logs.get(i.id)||[]).join('\n')||'Лог текущего запуска появится здесь.';const showLive=()=>{delete $('#liveLog').dataset.archive;$('#liveLog').textContent=(logs.get(i.id)||[]).join('\n');};$('#live').onclick=showLive;for(const f of files){const b=document.createElement('button');b.textContent=f.name;b.onclick=()=>run(async()=>{const text=await api('readLog',{instanceId:i.id,path:f.path});if(token!==viewSeq)return;$('#liveLog').dataset.archive='true';$('#liveLog').textContent=text;});$('#logFiles').append(b);}return;}
  $('#folder').onclick=()=>run(()=>api('openFolder',{instanceId:i.id,kind}));if($('#download'))$('#download').onclick=()=>catalogModal(kind,i.id);
  renderLibraryFiles(i,kind,files);
 });
}
function confirmAction(title,message,action){modal(`${closeButton()}<h2>${esc(title)}</h2><p>${esc(message)}</p><div class="form-actions"><button id="confirmCancel">Отмена</button><button class="primary" id="confirmOk">Удалить</button></div>`);$('#confirmCancel').onclick=()=>$('#modal').close();$('#confirmOk').onclick=()=>run(async()=>{$('#confirmOk').disabled=true;try{await action();$('#modal').close();}finally{if($('#confirmOk'))$('#confirmOk').disabled=false;}});}
function editText(title,value,submit){modal(`${closeButton()}<h2>${esc(title)}</h2><form id="editTextForm"><input id="editText" value="${esc(value)}" required maxlength="100"><div class="form-actions"><button type="submit" class="primary">Сохранить</button></div></form>`);$('#editTextForm').onsubmit=e=>{e.preventDefault();run(async()=>{await submit($('#editText').value.trim());$('#modal').close();renderEditor();});};}
function serverModal(instance,file=null){modal(`${closeButton()}<h2>${file?'Изменить сервер':'Добавить сервер'}</h2><form id="serverForm"><label>Название<input id="serverName" value="${esc(file?.name||'')}" maxlength="100" required></label><label>Адрес / IP<input id="serverAddress" value="${esc(file?.address||'')}" maxlength="255" required placeholder="example.org:25565"></label><div class="form-actions"><button type="submit" class="primary">Сохранить</button></div></form>`);$('#serverForm').onsubmit=e=>{e.preventDefault();run(async()=>{await api('serverAction',{instanceId:instance.id,operation:file?'edit':'add',index:file?.index??-1,name:$('#serverName').value.trim(),address:$('#serverAddress').value.trim()});$('#modal').close();renderEditor();});};}
function renderLibraryFiles(instance,kind,files){
 const selectable=['mods','shaders','resources','screenshots'].includes(kind), selected=new Set();
 const toolbar=$('#editorContent .toolbar');toolbar.insertAdjacentHTML('beforeend',`<input id="fileSearch" placeholder="Поиск…" aria-label="Поиск файлов">${['mods','shaders','resources'].includes(kind)?'<button id="enableSelected" disabled>Включить выбранные</button><button id="disableSelected" disabled>Отключить выбранные</button>':kind==='screenshots'?'<button id="copySelected" disabled>Копировать</button>':kind==='servers'?'<button id="addServer">Добавить сервер</button>':kind==='worlds'?'<button id="importWorld">Добавить мир</button>':''}${selectable?'<span class="muted" id="selectionCount">Выбрано: 0</span>':''}`);
 const content=files.length?kind==='screenshots'?`<div class="screenshots">${files.map((f,index)=>`<figure class="screenshot" data-select="${index}" data-search="${esc(f.name.toLowerCase())}">${image(f.image)}<figcaption>${esc(f.name)}</figcaption><button data-view-shot="${index}">Открыть</button><button data-rename-shot="${index}">Переименовать</button></figure>`).join('')}</div>`:`<div class="panel">${files.map((f,index)=>`<div class="file-row" ${selectable?`data-select="${index}"`:''} data-search="${esc(((f.label||f.name||'')+' '+(f.address||'')).toLowerCase())}"><div class="catalog-icon">${image(f.icon?.startsWith('data:')||f.icon?.startsWith('https:')?f.icon:f.icon?'data:image/png;base64,'+f.icon:'')||'◈'}</div><div class="details"><h3>${esc(f.label||f.name)}</h3><p class="muted">${esc(f.version||f.address||'')} ${esc(f.game||'')} ${f.lastPlayed?'· '+date(f.lastPlayed):''}</p></div>${['mods','shaders','resources'].includes(kind)?`<button class="switch ${f.enabled?'':'off'}" data-toggle-file="${index}">${f.enabled?'Включён':'Отключён'}</button>`:`<button data-play-target="${index}">${kind==='servers'?'Подключиться':'Играть'}</button><button data-edit-item="${index}">Изменить</button><button data-delete-item="${index}">Удалить</button>`}</div>`).join('')}</div>`:empty('Здесь пока пусто','Добавьте файлы или создайте запись.');$('#fileList').innerHTML=content;
 function selectionChanged(){for(const row of $$('[data-select]'))row.classList.toggle('selected-file',selected.has(Number(row.dataset.select)));if($('#selectionCount'))$('#selectionCount').textContent='Выбрано: '+selected.size;for(const id of ['enableSelected','disableSelected','copySelected'])if($('#'+id))$('#'+id).disabled=!selected.size;}
 $('#fileSearch').oninput=()=>{const query=$('#fileSearch').value.trim().toLowerCase();$$('#fileList [data-search]').forEach(row=>{const show=row.dataset.search.includes(query);row.hidden=!show;if(!show&&row.dataset.select)selected.delete(Number(row.dataset.select));});selectionChanged();};
 if(selectable)bindFileSelection($('#fileList'),selected,selectionChanged);
 async function enable(paths,enabled){await api('enableFiles',{instanceId:instance.id,kind,paths,enabled});renderEditor();}
 if($('#enableSelected'))$('#enableSelected').onclick=()=>run(()=>enable([...selected].map(n=>files[n].path),true));if($('#disableSelected'))$('#disableSelected').onclick=()=>run(()=>enable([...selected].map(n=>files[n].path),false));
 $$('[data-toggle-file]').forEach(b=>b.onclick=()=>run(()=>{const f=files[Number(b.dataset.toggleFile)];return enable([f.path],!f.enabled);}));
 if($('#copySelected'))$('#copySelected').onclick=()=>run(async()=>{await api('copyScreenshots',{instanceId:instance.id,paths:[...selected].map(n=>files[n].path)});toast(selected.size===1?'Изображение скопировано':'Файлы скопированы');});
 $$('[data-rename-shot]').forEach(b=>b.onclick=()=>{const f=files[Number(b.dataset.renameShot)];editText('Переименовать скриншот',f.name,name=>api('renameScreenshot',{instanceId:instance.id,path:f.path,name}));});
 $$('[data-view-shot]').forEach(b=>b.onclick=()=>screenshotViewer(files[Number(b.dataset.viewShot)].image));
 $$('.screenshot img').forEach(img=>img.ondblclick=()=>screenshotViewer(img.src));
 if($('#addServer'))$('#addServer').onclick=()=>serverModal(instance);
 if($('#importWorld'))$('#importWorld').onclick=()=>run(async()=>{await api('worldAction',{instanceId:instance.id,operation:'import'});renderEditor();});
 $$('[data-edit-item]').forEach(b=>b.onclick=()=>{const f=files[Number(b.dataset.editItem)];if(kind==='servers')serverModal(instance,f);else editText('Название мира',f.name,name=>api('worldAction',{instanceId:instance.id,operation:'rename',path:f.path,name}));});
 $$('[data-delete-item]').forEach(b=>b.onclick=()=>{const f=files[Number(b.dataset.deleteItem)];confirmAction(kind==='servers'?'Удалить сервер?':'Удалить мир?',f.name,async()=>{await api(kind==='servers'?'serverAction':'worldAction',{instanceId:instance.id,operation:'delete',index:f.index,path:f.path});renderEditor();});});
 $$('[data-play-target]').forEach(b=>b.onclick=()=>run(async()=>{const f=files[Number(b.dataset.playTarget)];if(state.running.includes(instance.id)||busy.has(instance.id))throw Error('Закройте текущую игру перед новым запуском');busy.add(instance.id);syncPlayButtons();openEditor(instance.id,'logs');try{updateState(await api('launchTarget',{instanceId:instance.id,kind,target:kind==='servers'?f.address:f.path}));}finally{busy.delete(instance.id);syncPlayButtons();}}));
}
let activeFileSelection=null;
document.addEventListener('pointerdown',e=>{
 if(e.button!==0||!activeFileSelection)return;
 const {host,clear}=activeFileSelection;
 if(!host.isConnected){activeFileSelection=null;return;}
 if(!host.contains(e.target)&&!e.target.closest('button,input,select,textarea,a,[role="button"],#modal'))clear();
});
function bindFileSelection(host,selected,changed){
 activeFileSelection={host,clear:()=>{selected.clear();changed();}};
 let anchor=null,frame=0,rectangle=null;const rows=[...host.querySelectorAll('[data-select]')];
 host.onpointerdown=e=>{if(e.button!==0||e.target.closest('button,input'))return;const row=e.target.closest('[data-select]');const wasSelected=row&&selected.has(Number(row.dataset.select));const before=new Set(e.ctrlKey?selected:[]);anchor={x:e.clientX,y:e.clientY,before,index:row?Number(row.dataset.select):null,moved:false};if(!e.ctrlKey&&!wasSelected)selected.clear();if(row){const index=Number(row.dataset.select);if(wasSelected)selected.delete(index);else selected.add(index);}changed();};
 host.onpointermove=e=>{if(!anchor)return;const x=e.clientX,y=e.clientY;if(Math.abs(x-anchor.x)+Math.abs(y-anchor.y)<5&&!anchor.moved)return;anchor.moved=true;host.setPointerCapture(e.pointerId);if(frame)cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{frame=0;if(!anchor)return;const bounds={left:Math.min(x,anchor.x),top:Math.min(y,anchor.y),right:Math.max(x,anchor.x),bottom:Math.max(y,anchor.y)};if(!rectangle){rectangle=document.createElement('div');rectangle.className='selection-box';document.body.append(rectangle);}Object.assign(rectangle.style,{left:bounds.left+'px',top:bounds.top+'px',width:bounds.right-bounds.left+'px',height:bounds.bottom-bounds.top+'px'});selected.clear();for(const n of anchor.before)selected.add(n);for(const row of rows){if(row.hidden)continue;const r=row.getBoundingClientRect();if(r.left<bounds.right&&r.right>bounds.left&&r.top<bounds.bottom&&r.bottom>bounds.top)selected.add(Number(row.dataset.select));}changed();});};
 host.onpointerup=host.onpointercancel=()=>{if(frame)cancelAnimationFrame(frame);frame=0;anchor=null;rectangle?.remove();rectangle=null;};host.ondragstart=e=>e.preventDefault();
}

function screenshotViewer(src){
 modal(`${closeButton()}<div class="screenshot-viewer" id="shotViewport">${image(src,'shot-image')}</div><p class="muted">Нажмите для приближения. Зажмите мышь, чтобы переместить изображение. Нажмите ещё раз, чтобы уменьшить.</p>`);
 $('#modal').classList.add('screenshot-dialog');
 const stage=$('#shotViewport'),img=stage.querySelector('img');let zoomed=false,x=0,y=0,drag=null;
 function paint(){const limitX=Math.max(0,(img.clientWidth*2.5-stage.clientWidth)/2),limitY=Math.max(0,(img.clientHeight*2.5-stage.clientHeight)/2);x=Math.max(-limitX,Math.min(limitX,x));y=Math.max(-limitY,Math.min(limitY,y));img.style.transform=`translate(${x}px,${y}px) scale(${zoomed?2.5:1})`;stage.classList.toggle('is-zoomed',zoomed);}
 stage.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();drag={id:e.pointerId,x:e.clientX,y:e.clientY,startX:x,startY:y,moved:false};stage.setPointerCapture(e.pointerId);};
 stage.onpointermove=e=>{if(!drag||e.pointerId!==drag.id)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)>5)drag.moved=true;if(zoomed&&drag.moved){x=drag.startX+dx;y=drag.startY+dy;paint();}};
 stage.onpointerup=e=>{if(!drag||e.pointerId!==drag.id)return;if(!drag.moved){zoomed=!zoomed;x=0;y=0;if(zoomed){const r=stage.getBoundingClientRect();x=(r.left+r.width/2-e.clientX)*1.5;y=(r.top+r.height/2-e.clientY)*1.5;}paint();}drag=null;stage.releasePointerCapture(e.pointerId);};
 stage.onpointercancel=()=>{drag=null;};stage.ondragstart=e=>e.preventDefault();img.onload=paint;
}

async function renderDiscover(){
 $('#main').innerHTML=`<section>${heading('НОВЫЕ ПРИКЛЮЧЕНИЯ','Обзор')}<div class="hero"><div><div class="eyebrow">MODRINTH + CURSEFORGE</div><h2>Найди мир, в котором<br>захочется остаться.</h2><p>Готовые сборки от сообщества. От лёгких улучшений<br>до совершенно нового Minecraft.</p></div><span class="pill">МОДПАКИ</span></div><div class="toolbar"><input id="catalogQuery" placeholder="Поиск модпаков…"><button id="searchCatalog">Найти</button></div><div id="catalogResults"></div><div class="form-actions"><button id="catalogMore" hidden>Показать ещё</button></div></section>`;
 let offset=0;const search=async(append=false)=>{if(!append)offset=0;await fillCatalog($('#catalogResults'),'modpacks','',$('#catalogQuery').value,offset,append);offset+=24;};$('#searchCatalog').onclick=()=>run(()=>search());$('#catalogQuery').onkeydown=e=>{if(e.key==='Enter')run(()=>search());};$('#catalogMore').onclick=()=>run(()=>search(true));await run(()=>search());
}
async function catalogModal(kind,id){modal(`${closeButton()}<h2>Скачивание ${kind==='mods'?'модов':kind==='shaders'?'шейдеров':'ресурс паков'}</h2><p>Совместимость: ${esc(findInstance(id).version)} · ${esc(findInstance(id).loader)}</p><div class="toolbar"><input id="modalQuery" placeholder="Поиск…"><button id="modalSearch">Найти</button></div><div id="modalResults"></div><div class="form-actions"><button id="modalMore" hidden>Показать ещё</button></div>`);let offset=0;const search=async(append=false)=>{if(!append)offset=0;await fillCatalog($('#modalResults'),kind,id,$('#modalQuery').value,offset,append);offset+=24;};$('#modalSearch').onclick=()=>run(()=>search());$('#modalQuery').onkeydown=e=>{if(e.key==='Enter')run(()=>search());};$('#modalMore').onclick=()=>run(()=>search(true));await run(()=>search());}
let catalogSeq=0;
async function fillCatalog(container,kind,id,query,offset,append){
 const request=++catalogSeq;if(!append)container.innerHTML=empty('Ищем дополнения','Получаем результаты из каталогов…');const result=await api('search',{query,kind,instanceId:id,offset});if(request!==catalogSeq||!container.isConnected)return;
 const cards=result.items.map(x=>`<article class="catalog-card" tabindex="0" role="button" data-project="${esc(x.id)}" data-source="${esc(x.source)}"><div class="catalog-top"><div class="catalog-icon">${image(x.icon)||pixelIcon('cube')}</div><div><h3>${esc(x.title)}</h3><span class="source ${x.source==='curseforge'?'cf':''}">${x.source.toUpperCase()}</span></div></div><p>${esc(x.description)}</p><div class="catalog-bottom"><span class="muted">↓ ${Intl.NumberFormat('ru',{notation:'compact'}).format(x.downloads)}</span><button data-install="${esc(x.id)}" data-source="${x.source}" class="primary">Установить</button></div></article>`).join('');
 if(append)container.querySelector('.catalog-grid')?.insertAdjacentHTML('beforeend',cards);else container.innerHTML=result.warnings.map(w=>`<div class="warning">${esc(w)}</div>`).join('')+(cards?`<div class="catalog-grid">${cards}</div>`:empty('Ничего не найдено','Попробуйте другой запрос.'));
 const more=$('#modalMore')||$('#catalogMore');if(more)more.hidden=!result.items.length;
 container.querySelectorAll('[data-project]').forEach(card=>{card.onclick=e=>{if(!e.target.closest('[data-install]'))SpectraProjects.open(card.dataset.source,card.dataset.project,kind,id);};card.onkeydown=e=>{if(e.key==='Enter'&&e.target===card)card.click();};});
 container.querySelectorAll('[data-install]').forEach(b=>b.onclick=e=>{e.stopPropagation();run(async()=>{b.disabled=true;b.textContent='Загрузка…';try{if(kind==='modpacks'){updateState(await api('installPack',{source:b.dataset.source,projectId:b.dataset.install}));toast('Модпак добавлен в сборки');}else{await api('install',{source:b.dataset.source,projectId:b.dataset.install,kind,instanceId:id});toast('Дополнение установлено');}b.textContent='✓ Установлено';$('#progressText').textContent='';}catch(e){b.disabled=false;b.textContent='Установить';throw e;}});});
}
function settingsForm(s,global){return `<form id="settingsForm"><div class="panel settings-section"><h2>${global?'Настройки новых сборок':'Настройки сборки'}</h2><div class="form-grid"><label class="wide">Исполняемый файл Java<div class="field-line"><input id="javaPath" value="${esc(s.javaPath)}" placeholder="Автоматически · Eclipse Adoptium"><button type="button" id="chooseJava">Обзор…</button></div></label><label>Предпочтение графики<select id="gpu"><option value="system">Выбор Windows</option><option value="high" ${s.gpu==='high'?'selected':''}>Высокая производительность</option><option value="low" ${s.gpu==='low'?'selected':''}>Энергосбережение</option></select></label><label>Доступные видеокарты<span id="gpuNames" class="muted">Получаем список…</span></label><label>Минимальная память, МБ<input type="number" id="minRam" min="256" max="131072" value="${s.minRam}" required></label><label>Максимальная память, МБ<input type="number" id="maxRam" min="256" max="131072" value="${s.maxRam}" required></label><label>Ширина окна<input type="number" id="gameWidth" min="320" value="${s.width}" required></label><label>Высота окна<input type="number" id="gameHeight" min="240" value="${s.height}" required></label><label class="wide"><span><input type="checkbox" id="hideOnLaunch" ${s.hideOnLaunch?'checked':''}> Сворачивать лаунчер после запуска</span></label></div><p class="hint">Java загружается по требованиям официального манифеста версии. Предпочтение GPU записывается для выбранного javaw.exe при запуске. Окончательное назначение видеокарты определяет Windows; точное соответствие режиму здесь пока не определяется.</p></div><div class="form-actions"><button class="primary" type="submit">Сохранить настройки</button></div></form>`;}
function readSettings(){return{javaPath:$('#javaPath').value.trim(),minRam:Number($('#minRam').value),maxRam:Number($('#maxRam').value),width:Number($('#gameWidth').value),height:Number($('#gameHeight').value),gpu:$('#gpu').value,hideOnLaunch:$('#hideOnLaunch').checked};}
function bindSettings(global,i){$('#chooseJava').onclick=()=>run(async()=>{const path=await api('pickJava');if(path)$('#javaPath').value=path;});run(async()=>{const gpus=await api('gpus');if($('#gpuNames'))$('#gpuNames').textContent=gpus.join(' / ')||'Не удалось определить';});$('#settingsForm').onsubmit=e=>{e.preventDefault();run(async()=>{const settings=readSettings();if(settings.maxRam<settings.minRam)throw new Error('Максимум памяти должен быть не меньше минимума');updateState(await api(global?'settings':'saveInstance',global?{defaults:settings,curseForgeKey:'',craftyKey:''}:{...i,settings}));toast('Настройки сохранены');});};}
function renderSettings(){$('#main').innerHTML=`<section>${heading('ПОД ТВОИ ПРИВЫЧКИ','Настройки')}<p class="muted">Эти параметры применяются к новым сборкам.</p>${settingsForm(state.defaults,true)}<div class="panel settings-section"><h2>Аккаунт Minecraft</h2><p>Ник, скин и доступные плащи изменяются в профиле.</p><button data-page="profile">Открыть профиль →</button></div></section>`;bindSettings(true);window.SpectraFriends?.settings($('#main'));bind($('#main'));SpectraAppearance.mount($('#main'));}
function configurationModal(){modal(`${closeButton()}<h2>Вход Microsoft</h2><p>Нажмите «Войти с Microsoft». По умолчанию официальная страница Microsoft откроется во встроенном окне: выберите аккаунт и подтвердите доступ. Если разработчик настроил собственную регистрацию Spectra, вход откроется в браузере по умолчанию. Затем лаунчер подключит профиль Minecraft Java Edition.</p><div class="warning">Для встроенного провайдера CmlLib свой Client ID не требуется. Доступность входа зависит от Microsoft и Minecraft Services. Для игры нужен аккаунт с Minecraft Java Edition.</div><div class="form-actions"><button class="primary" id="modalLogin">Войти с Microsoft ${pixelIcon('arrow')}</button></div>`);$('#modalLogin').onclick=()=>run(async()=>{$('#modal').close();await login();});}

let profileRequest=0;
function skinUrl(p){return (p?.skins?.find(x=>x.state==='ACTIVE')?.url||p?.skins?.[0]?.url||'').replace(/^http:\/\/textures\.minecraft\.net\//,'https://textures.minecraft.net/');}
let displayedProfile=null;
function capeUrl(p){return (p?.capes?.find(c=>c.state==='ACTIVE')?.url||'').replace(/^http:\/\/textures\.minecraft\.net\//,'https://textures.minecraft.net/');}
function renderProfile(player=state.profile){
 displayedProfile=player;
 const request=++profileRequest,p=player,own=!!p&&p.id===state.profile?.id;
 $('#main').innerHTML=`<section>${heading('MINECRAFT JAVA EDITION','Профиль')}<div class="hero profile-hero"><div class="profile-avatar">${esc((p?.name||'S')[0])}</div><div class="profile-copy"><div class="eyebrow">${own?'МОЙ ПРОФИЛЬ':'ПРОФИЛЬ ИГРОКА'}</div><h1>${esc(p?.name||'Гость')}</h1><p>${p?'Minecraft Java Edition':'Войдите, чтобы изменить скин и играть.'}</p><span class="pill">${own?'АККАУНТ ПОДКЛЮЧЁН':'ПРОСМОТР'}</span></div>${!p?'<button id="profileLogin" class="primary">Войти с Microsoft</button>':''}</div>
 <div class="toolbar"><input id="playerSearch" placeholder="Ник игрока" value="${esc(p?.name||'')}"><button id="findPlayer">Найти игрока</button>${state.profile&&!own?'<button id="myProfile">Мой профиль</button><button id="profileFriendRequest">Добавить в друзья</button><span id="profileOnline" class="muted"></span>':''}<button id="craftyLink">Crafty ↗</button></div>
 <div class="profile-grid"><div class="panel"><h2>3D-превью скина</h2><div id="skinPreview" class="skin-stage"></div><p class="muted">Перетаскивайте мышью, чтобы повернуть модель.</p></div><div class="panel"><h2>Информация игрока</h2><dl class="player-info"><dt>UUID</dt><dd>${esc(p?.id||'Нет аккаунта')}</dd><dt>Ссылка на профиль</dt><dd>${esc(p?.name?'crafty.gg/@'+p.name:'Нет данных')}</dd><dt>Модель</dt><dd>${esc(p?.skins?.[0]?.variant||'Нет данных')}</dd><dt>Дата создания Minecraft-аккаунта</dt><dd>Не предоставлена источником</dd></dl><div id="craftyData"><p class="muted">Получаем дополнительные сведения…</p></div></div></div>
 ${own?`<div id="networkAccountSettings" class="panel profile-edit"></div><div class="panel profile-edit"><h2>Мой Minecraft</h2><div class="toolbar"><input id="newName" value="${esc(p.name)}" minlength="3" maxlength="16"><button id="changeName">Изменить ник</button><select id="skinVariant"><option value="classic">Обычные руки</option><option value="slim">Тонкие руки</option></select><button id="changeSkin">Загрузить и надеть PNG</button></div><div class="cape-list">${(p.capes||[]).map(c=>`<div class="cape-row"><div class="cape-preview" data-cape-preview="${esc(c.id)}"></div><span>${esc(c.alias||c.id)}</span><button data-cape="${esc(c.id)}">${c.state==='ACTIVE'?'Надет':'Надеть'}</button></div>`).join('')||'<p>Доступных плащей нет</p>'}<button id="hideCape">Скрыть плащ</button></div></div><div class="panel profile-edit"><div class="section-label"><h2>Мои сохранённые скины</h2><button id="addSkin">${pixelIcon('plus')} Добавить PNG</button></div><p class="muted">Видны только в вашем профиле этого лаунчера. Добавление не меняет скин в игре.</p><div class="saved-skins">${(state.skins||[]).map(x=>`<article class="saved-skin"><div class="saved-pair" data-face="${esc(x.id)}"></div><h3>${esc(x.name)}</h3><p class="muted">${date(x.added)} · ${esc(x.variant)}</p><button data-preview-skin="${esc(x.id)}">Превью</button><button data-apply-skin="${esc(x.id)}">Надеть</button><button data-remove-skin="${esc(x.id)}">Удалить из списка</button></article>`).join('')||'<p>Список пока пуст.</p>'}</div></div>`:''}
 <div id="histories" class="profile-grid"><div class="panel"><h2>История ников</h2><div id="nameHistory">Нет данных</div></div><div class="panel"><h2>История скинов Crafty</h2><div id="skinHistory">Нет данных</div></div></div></section>`;
 window.SpectraFriends?.profile(p,own);
 $('#profileLogin')?.addEventListener('click',()=>run(()=>login()));
 if(p){paintFace($('.profile-avatar'),skinUrl(p));mountSkin($('#skinPreview'),skinUrl(p),p.skins?.[0]?.variant,capeUrl(p));}
 $('#myProfile')?.addEventListener('click',()=>renderProfile());
 $('#findPlayer').onclick=()=>run(async()=>{const name=$('#playerSearch').value.trim();const found=await api('player',{name});if(request===profileRequest&&page==='profile')renderProfile(found);});
 $('#craftyLink').onclick=()=>run(()=>api('external',{url:'https://crafty.gg/players/'+encodeURIComponent($('#playerSearch').value.trim())}));
 if(own){for(const cape of p.capes||[])paintCape($(`[data-cape-preview="${cape.id}"]`),(cape.url||'').replace('http://textures.minecraft.net/','https://textures.minecraft.net/'));$('#changeName').onclick=()=>profileAction('name',{name:$('#newName').value});$('#changeSkin').onclick=()=>profileAction('skin',{variant:$('#skinVariant').value});$('#hideCape').onclick=()=>profileAction('hideCape');$$('[data-cape]').forEach(b=>b.onclick=()=>profileAction('cape',{capeId:b.dataset.cape}));$('#addSkin').onclick=()=>run(async()=>{updateState(await api('addSkin',{variant:$('#skinVariant').value}));renderProfile();});for(const x of state.skins||[]){paintSkinPair($(`[data-face="${x.id}"]`),x.image,x.variant);$(`[data-preview-skin="${x.id}"]`).onclick=()=>mountSkin($('#skinPreview'),x.image,x.variant,capeUrl(p));$(`[data-apply-skin="${x.id}"]`).onclick=()=>run(async()=>{updateState(await api('applySkin',{id:x.id}));renderProfile();toast('Скин изменён в Minecraft');});$(`[data-remove-skin="${x.id}"]`).onclick=()=>run(async()=>{updateState(await api('removeSkin',{id:x.id}));renderProfile();});}}
 if(p)api('crafty',{name:p.name}).then(data=>{if(request===profileRequest&&page==='profile')renderCrafty(data);}).catch(e=>{if(request===profileRequest&&$('#craftyData'))$('#craftyData').textContent=e.message;});else $('#craftyData').textContent='Войдите или найдите игрока';
}
function renderCrafty(data){
 const p=data.data?.player||data.data||data.player||data;
 const names=p.username_history||p.usernameHistory||p.usernames||p.name_history||[],skins=p.skin_history||p.skinHistory||p.skins||[];
 const historyDate=x=>x?date(x):'Дата неизвестна';
 $('#craftyData').innerHTML=`<dl class="player-info"><dt>Профиль Crafty создан</dt><dd>${p.created_at||p.createdAt?historyDate(p.created_at||p.createdAt):'Нет данных'}</dd><dt>Статус Crafty</dt><dd>${esc(p.status|| (p.claimed===true?'Подтверждён':p.claimed===false?'Не подтверждён':'Нет данных'))}</dd><dt>Locator Bar</dt><dd>${esc(p.locator_bar?.color||p.locatorBar?.color||'Источник не предоставил цвет')}</dd></dl><p class="muted">Дата профиля Crafty не является датой создания Minecraft-аккаунта.</p>`;
 $('#nameHistory').innerHTML=Array.isArray(names)&&names.length?names.map(x=>`<div class="history-row"><strong>${esc(typeof x==='string'?x:x.username||x.name)}</strong><span>${historyDate(x.changed_at||x.changedAt||x.created_at)}</span></div>`).join(''):'Источник не предоставил историю ников.';
 const history=Array.isArray(skins)?skins:[];
 $('#skinHistory').innerHTML=history.length?`<div class="saved-skins">${history.map((x,index)=>`<article class="saved-skin"><div class="saved-pair" data-history-skin="${index}"></div><p class="muted">${historyDate(x.created_at||x.last_seen)}</p><button data-history-preview="${index}">3D-превью</button></article>`).join('')}</div>`:'Источник не предоставил историю скинов.';
 for(const [index,x] of history.entries()){const url=(x.url||x.texture_url||x.skin_url||x.texture?.url||'').replace('http://textures.minecraft.net/','https://textures.minecraft.net/');const variant=x.variant||x.model||'classic';const host=$(`[data-history-skin="${index}"]`);if(url)lazySkinPair(host,url,variant);else host.textContent='Нет адреса текстуры';const button=$(`[data-history-preview="${index}"]`);button.disabled=!safeImage(url);button.onclick=()=>mountSkin($('#skinPreview'),url,variant,capeUrl(displayedProfile));}

}

function profileAction(operation,data={}){run(async()=>{updateState(await api('profileAction',{operation,...data}));toast('Профиль обновлён');renderProfile();});}
function bytes(n){if(!Number.isFinite(Number(n))||n<0)return '0 Б';const units=['Б','КиБ','МиБ','ГиБ'];let k=0;while(n>=1024&&k<3){n/=1024;k++;}return n.toLocaleString('ru-RU',{maximumFractionDigits:k?1:0})+' '+units[k];}
function findInstance(id){return id==='vanilla'?{id,name:'Minecraft '+state.selection?.version,version:state.selection?.version,loader:'vanilla',settings:state.defaults}:state.instances.find(x=>x.id===id);}
function viewButtons(kind){return `<select class="view-select" data-view="${kind}" aria-label="Вид списка"><option value="cards">Карточки</option><option value="tiles">Крупные плитки</option><option value="list">Компактный список</option></select>`;}
function bindViews(){$$('[data-view]').forEach(b=>{b.value=state.views?.[b.dataset.view]||'cards';b.onchange=()=>run(async()=>{updateState(await api('view',{kind:b.dataset.view,mode:b.value}));if(page==='versions')renderVersions();else renderInstances();});});}
async function choose(version,instanceId){updateState(await api('select',{version,instanceId}));$$('[data-version]').forEach(b=>b.classList.toggle('selected',!instanceId&&b.dataset.version===version));toast(instanceId?'Сборка выбрана':'Выбрана Minecraft '+version);}
function motionMs(ms){return window.matchMedia?.('(prefers-reduced-motion: reduce)').matches?0:ms;}
let quickCollapsed=false;
try{quickCollapsed=localStorage.getItem('spectra.quickCollapsed')==='true';}catch{}
function quickCard(version,instance,allowBedrock=true){if(allowBedrock&&!instance&&state.selection?.edition==='bedrock')return `<div class="quick-card"><div class="quick-art"><img src="assets/terrain.svg" alt=""></div><div class="quick-shade"></div><div class="quick-caption">${pixelIcon('cube')}<div><strong>Minecraft ${esc(state.selection.bedrockLabel)}</strong><span>Bedrock Edition · Windows</span></div></div></div>`;const name=instance?.name|| (version?'Minecraft '+version:'Выберите версию');const backdrop=instance?.banner||versionArt[instance?.version||version]||instance?.icon;return `<div class="quick-card"><div class="quick-art">${image(backdrop)||'<img src="assets/terrain.svg" alt="">'}</div><div class="quick-shade"></div><div class="quick-caption">${instance?.icon?image(instance.icon,'quick-icon'):pixelIcon('cube')}<div><strong>${esc(name)}</strong><span>${esc(instance?instance.version+' · '+instance.loader:version?'Java Edition':'Версия или модпак')}</span></div></div></div>`;}
let quickSignature='';
function renderQuick(){
 const host=$('#quickLaunch');if(!host)return;const selection=state.selection||{},selected=selection.edition==='bedrock'?null:selection.instanceId?findInstance(selection.instanceId):null;
 const signature=JSON.stringify([quickCollapsed,selection,selected?.name,selected?.banner,selected?.icon,versionArt[selected?.version||selection.version]]);if(signature===quickSignature&&$('#quickBody')){syncPlayButtons();return;}quickSignature=signature;$('#quickChoices')?.remove();
 host.classList.toggle('collapsed',quickCollapsed);
 host.innerHTML=`<div class="quick-header"><span class="eyebrow">БЫСТРЫЙ ЗАПУСК</span><button id="quickToggle" aria-expanded="${!quickCollapsed}" aria-controls="quickBody" title="${quickCollapsed?'Развернуть':'Свернуть'}">${quickCollapsed?'＋':'−'}</button></div><div id="quickBody" ${quickCollapsed?'hidden':''}>${quickCard(selection.version,selected)}<button id="quickChoose" aria-expanded="false" aria-controls="quickChoices">Выбрать версию или модпак ▾</button><div id="quickChoices" class="glass" hidden><select id="quickEdition" aria-label="Издание быстрого запуска"><option value="all">Все</option><option value="java">Java Edition</option><option value="bedrock">Bedrock Edition</option><option value="instances">Сборки</option></select><input id="quickSearch" placeholder="Поиск версии или сборки" aria-label="Поиск быстрого запуска"><div id="quickOptions"></div></div><button id="quickPlay" class="primary" ${selection.edition==='bedrock'?selection.bedrockId?'':'disabled':selected||selection.version?'':'disabled'}>${pixelIcon('play')} Играть</button></div>`;
 $('#quickToggle').onclick=()=>{quickCollapsed=!quickCollapsed;try{localStorage.setItem('spectra.quickCollapsed',String(quickCollapsed));}catch{}quickSignature='';const body=$('#quickBody');if(quickCollapsed){$('#quickChoices').hidden=true;body.animate?.([{opacity:1,transform:'translateY(0)'},{opacity:0,transform:'translateY(5px)'}],{duration:motionMs(130)}).finished.then(()=>renderQuick()).catch(()=>renderQuick());if(!body.animate)renderQuick();}else{renderQuick();$('#quickBody').animate?.([{opacity:0,transform:'translateY(5px)'},{opacity:1,transform:'translateY(0)'}],{duration:motionMs(170)});}};
 $('#quickChoose').onclick=()=>{const list=$('#quickChoices');list.hidden=!list.hidden;$('#quickChoose').setAttribute('aria-expanded',String(!list.hidden));if(!list.hidden){document.body.append(list);quickOffset=0;$('#quickEdition').value=state.selection?.edition==='bedrock'?'bedrock':'all';fillQuickOptions();positionQuickChoices();$('#quickSearch').focus();if(typeof SpectraBedrock!=='undefined')SpectraBedrock.load().then(()=>{if($('#quickChoices')&&!$('#quickChoices').hidden)fillQuickOptions();}).catch(e=>toast(e.message));}};
 $('#quickEdition').onchange=()=>{quickOffset=0;fillQuickOptions();};$('#quickSearch').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{quickOffset=0;fillQuickOptions();},120);};
 $('#quickPlay').onclick=()=>state.selection?.edition==='bedrock'?SpectraBedrock.launch():playAction(selected?.id||'vanilla');syncPlayButtons();
}
let quickOffset=0;
function fillQuickOptions(){const query=$('#quickSearch').value.trim().toLowerCase(),edition=$('#quickEdition')?.value||'all';const choices=[...(['all','instances'].includes(edition)?state.instances.filter(i=>(i.name+' '+i.version).toLowerCase().includes(query)).map(i=>({instance:i})):[]),...(['all','java'].includes(edition)?versions.filter(v=>(v.type==='release'||v.id===state.selection?.version||query)&&v.id.toLowerCase().includes(query)).map(v=>({version:v.id})):[]),...(['all','bedrock'].includes(edition)&&typeof SpectraBedrock!=='undefined'?SpectraBedrock.quickOptions(query).map(p=>({bedrock:p})):[])];const list=choices.slice(quickOffset,quickOffset+12);$('#quickOptions').innerHTML=list.map(x=>`<button class="quick-option" ${x.bedrock?`data-quick-bedrock="${esc(x.bedrock.id)}"`:x.instance?`data-quick-instance="${esc(x.instance.id)}"`:`data-quick-version="${esc(x.version)}"`}>${x.bedrock?SpectraBedrock.card(x.bedrock):quickCard(x.version,x.instance,false)}</button>`).join('')||'<p class="muted">Ничего не найдено. Каталог Bedrock загружается при первом открытии.</p>';$('#quickOptions').insertAdjacentHTML('beforeend',`<div class="quick-paging">${quickOffset?'<button id="quickPrev">←</button>':''}${quickOffset+12<choices.length?'<button id="quickNext">Далее →</button>':''}</div>`);$('#quickPrev')?.addEventListener('click',()=>{quickOffset=Math.max(0,quickOffset-12);fillQuickOptions();});$('#quickNext')?.addEventListener('click',()=>{quickOffset+=12;fillQuickOptions();});$$('[data-quick-instance]').forEach(b=>b.onclick=()=>run(()=>choose('',b.dataset.quickInstance)));$$('[data-quick-version]').forEach(b=>b.onclick=()=>run(()=>choose(b.dataset.quickVersion,'')));$$('[data-quick-bedrock]').forEach(b=>b.onclick=()=>run(()=>SpectraBedrock.select(choices.find(x=>x.bedrock?.id===b.dataset.quickBedrock)?.bedrock)));}

function positionQuickChoices(){const popup=$('#quickChoices'),anchor=$('#quickChoose');if(!popup||popup.hidden)return;const r=anchor.getBoundingClientRect(),h=window.innerHeight,w=window.innerWidth;const above=r.top-58,below=h-r.bottom-16,useAbove=above>=below,space=Math.max(80,useAbove?above:below);popup.style.maxHeight=Math.min(390,space)+'px';popup.style.width=Math.min(290,w-24)+'px';popup.style.left=Math.max(12,Math.min(r.left,w-Math.min(290,w-24)-12))+'px';popup.style.top=useAbove?'auto':r.bottom+8+'px';popup.style.bottom=useAbove?h-r.top+8+'px':'auto';}
function playLabel(id){return busy.has(id)?'Подготовка…':state.running.includes(id)?'■ Остановить':pixelIcon('play')+' Играть';}
function syncPlayButtons(){const bedrock=state.selection?.edition==='bedrock';const selected=state.selection?.instanceId||'vanilla';const b=$('#quickPlay');if(b){b.innerHTML=bedrock?busy.has('bedrock')?'Подготовка…':pixelIcon('play')+' Играть':playLabel(selected);b.disabled=bedrock?busy.has('bedrock')||!state.selection.bedrockId:busy.has(selected)||(!state.selection?.instanceId&&!state.selection?.version);b.classList.toggle('launching',busy.has(selected));}$$('.instance-card').forEach(c=>{const button=c.querySelector('[data-launch]');if(button){button.innerHTML=playLabel(c.dataset.id);button.disabled=busy.has(c.dataset.id);button.classList.toggle('launching',busy.has(c.dataset.id));}});}
function playAction(id){const button=$('#quickPlay');button?.animate?.([{transform:'translateY(0)'},{transform:'translateY(2px)'},{transform:'translateY(0)'}],{duration:motionMs(150)});if(state.running.includes(id))return run(()=>api('stop',{instanceId:id}));return launch(id);}
window.addEventListener?.('resize',positionQuickChoices);
document.addEventListener('pointerdown',e=>{if(!e.target.closest('#quickLaunch,#quickChoices')&&$('#quickChoices')){$('#quickChoices').hidden=true;$('#quickChoose')?.setAttribute('aria-expanded','false');}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#quickChoices')){$('#quickChoices').hidden=true;$('#quickChoose')?.setAttribute('aria-expanded','false');}});

function exportModal(id){const special=['quilt','neoforge'].includes(findInstance(id).loader);modal(`${closeButton()}<h2>Экспорт Prism / MultiMC</h2><p>ZIP включает моды, настройки и игровые файлы. Java, аккаунты, игровые библиотеки и логи не экспортируются.</p><label class="field">Целевой лаунчер<select id="exportTarget"><option value="prism">Prism Launcher</option><option value="multimc" ${special?'disabled':''}>MultiMC</option></select></label>${special?'<p class="muted">Для этого загрузчика доступен экспорт в Prism.</p>':'<p class="muted">Формат ZIP подходит для Prism и MultiMC.</p>'}<label><input id="exportWorlds" type="checkbox"> Включить миры и скриншоты</label><div class="form-actions"><button id="exportZip" class="primary">Сохранить ZIP</button></div>`);$('#exportZip').onclick=()=>run(async()=>{const b=$('#exportZip');b.disabled=true;try{const result=await api('exportInstance',{instanceId:id,includeWorlds:$('#exportWorlds').checked,target:$('#exportTarget').value});if(!result.cancelled){$('#modal').close();toast('ZIP сохранён для Prism / MultiMC');}}finally{b.disabled=false;}});}
let dragDepth=0;
document.addEventListener('dragenter',e=>{if([...e.dataTransfer.types].includes('Files')){e.preventDefault();dragDepth++;document.body.classList.add('pack-drop');}});
document.addEventListener('dragover',e=>{if([...e.dataTransfer.types].includes('Files')){e.preventDefault();e.dataTransfer.dropEffect='copy';}});
document.addEventListener('dragleave',()=>{if(--dragDepth<=0){dragDepth=0;document.body.classList.remove('pack-drop');}});
document.addEventListener('drop',e=>{e.preventDefault();dragDepth=0;document.body.classList.remove('pack-drop');run(async()=>{const files=[...e.dataTransfer.files];if(files.length!==1||!files[0].name.toLowerCase().endsWith('.zip'))throw new Error('Перенесите один ZIP-архив Prism/MultiMC');if(preview)throw new Error('Импорт доступен в Windows-приложении');if(!window.chrome.webview.postMessageWithAdditionalObjects)throw new Error('Обновите Microsoft Edge WebView2 Runtime');const id=String(++seq);const result=await new Promise((resolve,reject)=>{pending.set(id,{resolve,reject});try{window.chrome.webview.postMessageWithAdditionalObjects({id,action:'dropPack',data:{}},files);}catch(error){pending.delete(id);reject(error);}});updateState(result);if($('#shell').hidden){updateState(await api('expand'));openShell();}else navigate('instances');toast('Сборка импортирована');});});
bind();
let sourceUpdateRunning=false;
function showLogin(message='Войдите в Microsoft, чтобы продолжить'){ $('#updateScreen').hidden=true;$('#boot').hidden=false;$('#bootStatus').textContent=message; }
async function updateFromCommit(commit){if(sourceUpdateRunning)return;sourceUpdateRunning=true;$('#shell').hidden=true;$('#boot').hidden=true;$('#updateScreen').hidden=false;$('#updateTitle').textContent='Обновление';$('#updateDetail').textContent='Подготовка изменённых файлов…';try{return await api('updateSource',{commit});}finally{sourceUpdateRunning=false;}}
async function boot(){try{updateState(await api('state'));if(state.updateReport?.success===false)toast('Обновление не установлено: '+state.updateReport.message);const b=await api('bootstrap');if(b.commitName){latestCommitLabel={name:b.commitName,sha:b.commit};updateState(state);}$('#updateDetail').textContent=b.update;if(b.available){const button=$('#footerUpdate');button.hidden=false;button.textContent='Обновить до '+b.version;button.onclick=()=>run(async()=>{try{await updateFromCommit(b.commit);}catch(e){openShell();throw e;}});if(!preview&&b.automatic!==false){try{await updateFromCommit(b.commit);return;}catch(e){toast(e.message);}}}if(preview){openShell();}else if(state.hasAccount){$('#updateTitle').textContent='Запуск';$('#updateDetail').textContent='Восстанавливаем аккаунт…';try{await login(false);}catch{showLogin('Сессия истекла. Войдите в Microsoft снова.');}}else showLogin();}catch(e){showLogin('Не удалось завершить подготовку');toast(e.message);}}

// Browser preview uses clearly marked sample data. It never pretends to install or authenticate.
async function previewApi(action,data){
 if(action==='state'||action==='expand')return state;
 if(action==='bootstrap')return{update:'Просмотр интерфейса · проверка обновлений недоступна',available:false};
 if(action==='versions')return ['1.21.4','1.21.3','1.21.1','1.20.6','1.20.4','1.20.1','1.19.4','1.18.2','1.16.5','1.12.2','1.7.10','1.0','b1.7.3','a1.2.6','25w05a'].map((id,i)=>({id,type:id.startsWith('b')?'old_beta':id.startsWith('a')?'old_alpha':id.includes('w')?'snapshot':'release',releaseTime:new Date(2025-i,0,1).toISOString()}));
 if(action==='loaders')return data.loader==='vanilla'?[]:[{version:'0.16.10',recommended:true},{version:'0.16.9',recommended:false}];
 if(action==='artwork')return {};
 if(action==='components')return [{name:'Minecraft',version:'Просмотр интерфейса'},{name:'Загрузчик',version:'Просмотр интерфейса'}];
 if(action==='gpus')return ['Просмотр интерфейса · GPU не запрошены'];
 if(action==='files')return [];
 if(action==='search')return{items:[],warnings:['Просмотр интерфейса: сетевые каталоги доступны в Windows-приложении.']};
 if(action==='saveInstance'){const i={...data,id:data.id||'preview-'+Date.now()};const old=state.instances.findIndex(x=>x.id===i.id);old<0?state.instances.push(i):state.instances[old]=i;return state;}
 if(action==='bedrockVersions')return {installed:[],imported:[],available:[],updates:[],warning:'Проверка Bedrock доступна в Windows-приложении'};
 if(action==='bedrockStore'||action==='bedrockImport'||action==='bedrockLaunch')throw Error('Bedrock доступен в Windows-приложении');
 if(action==='bedrockSelect'){state.selection={edition:'bedrock',bedrockId:data.id,bedrockLabel:data.label};return state;}
 if(action==='projectDetails')throw Error('Каталог доступен в Windows-приложении');
 if(action==='fonts')return [];
 if(action==='importFont')throw Error('Загрузка шрифтов доступна в Windows-приложении');
 if(action==='appearance'){state.appearance=data;return state;}
 if(action==='settings'){state.defaults=data.defaults;return state;}
 if(action==='view'){state.views={...state.views,[data.kind]:data.mode};return state;}
 if(action==='select'){state.selection={edition:'java',version:data.version,instanceId:data.instanceId};return state;}
 if(action==='window')return;
 throw new Error('Это просмотр интерфейса. Действие доступно в приложении Spectra для Windows.');
}
if(preview&&new URLSearchParams(location.search).has('sample'))state.instances=[{id:'sample-1',name:'Тихая долина',version:'1.20.1',loader:'fabric',loaderVersion:'0.16.10',lastPlayed:'2026-10-07',icon:'',banner:'',settings:structuredClone(state.defaults)},{id:'sample-2',name:'Чистый Minecraft',version:'1.21.4',loader:'vanilla',loaderVersion:'',icon:'',banner:'',settings:structuredClone(state.defaults)}];
boot().then(()=>{getVersions().then(()=>renderQuick()).catch(()=>{});api('artwork').then(art=>{versionArt=art;renderQuick();}).catch(()=>{});});
