'use strict';
const SpectraAppearance=(()=>{
 const languages={ru:'Русский',en:'English',de:'Deutsch',fr:'Français',es:'Español',pt:'Português',it:'Italiano',pl:'Polski',uk:'Українська',tr:'Türkçe',zh:'简体中文',ja:'日本語',ko:'한국어'};
 const keys=['ВЕРСИИ','СБОРКИ','ОБЗОР','ПРОФИЛЬ','Настройки','Играть','Создать сборку','Сохранить настройки','Открыть профиль','Войти с Microsoft','Выйти из аккаунта','Войти в другой аккаунт','Сборки','Версии','Обновление','Запуск','МОДЫ','ШЕЙДЕРЫ','РЕСУРС ПАКИ','МИРЫ','СЕРВЕРЫ','СКРИНШОТЫ','ЛОГИ','ВЕРСИЯ','НАСТРОЙКИ'];
 const rows={en:'VERSIONS|INSTANCES|DISCOVER|PROFILE|Settings|Play|Create instance|Save settings|Open profile|Sign in with Microsoft|Sign out|Switch account|Instances|Versions|Update|Starting|MODS|SHADERS|RESOURCE PACKS|WORLDS|SERVERS|SCREENSHOTS|LOGS|VERSION|SETTINGS',de:'VERSIONEN|INSTANZEN|ENTDECKEN|PROFIL|Einstellungen|Spielen|Instanz erstellen|Speichern|Profil öffnen|Mit Microsoft anmelden|Abmelden|Konto wechseln|Instanzen|Versionen|Update|Start|MODS|SHADER|RESSOURCENPAKETE|WELTEN|SERVER|SCREENSHOTS|LOGS|VERSION|EINSTELLUNGEN',fr:'VERSIONS|INSTANCES|DÉCOUVRIR|PROFIL|Paramètres|Jouer|Créer une instance|Enregistrer|Ouvrir le profil|Connexion Microsoft|Déconnexion|Changer de compte|Instances|Versions|Mise à jour|Démarrage|MODS|SHADERS|PACKS DE RESSOURCES|MONDES|SERVEURS|CAPTURES|JOURNAUX|VERSION|PARAMÈTRES',es:'VERSIONES|INSTANCIAS|EXPLORAR|PERFIL|Ajustes|Jugar|Crear instancia|Guardar ajustes|Abrir perfil|Iniciar sesión con Microsoft|Cerrar sesión|Cambiar cuenta|Instancias|Versiones|Actualización|Inicio|MODS|SHADERS|PAQUETES DE RECURSOS|MUNDOS|SERVIDORES|CAPTURAS|REGISTROS|VERSIÓN|AJUSTES',pt:'VERSÕES|INSTÂNCIAS|EXPLORAR|PERFIL|Configurações|Jogar|Criar instância|Salvar configurações|Abrir perfil|Entrar com Microsoft|Sair|Trocar conta|Instâncias|Versões|Atualização|Iniciando|MODS|SHADERS|PACOTES DE RECURSOS|MUNDOS|SERVIDORES|CAPTURAS|REGISTROS|VERSÃO|CONFIGURAÇÕES',it:'VERSIONI|ISTANZE|ESPLORA|PROFILO|Impostazioni|Gioca|Crea istanza|Salva impostazioni|Apri profilo|Accedi con Microsoft|Esci|Cambia account|Istanze|Versioni|Aggiornamento|Avvio|MOD|SHADER|PACCHETTI RISORSE|MONDI|SERVER|SCHERMATE|LOG|VERSIONE|IMPOSTAZIONI',pl:'WERSJE|INSTANCJE|ODKRYWAJ|PROFIL|Ustawienia|Graj|Utwórz instancję|Zapisz ustawienia|Otwórz profil|Zaloguj przez Microsoft|Wyloguj|Zmień konto|Instancje|Wersje|Aktualizacja|Uruchamianie|MODY|SHADERY|PAKIETY ZASOBÓW|ŚWIATY|SERWERY|ZRZUTY EKRANU|LOGI|WERSJA|USTAWIENIA',uk:'ВЕРСІЇ|ЗБІРКИ|ОГЛЯД|ПРОФІЛЬ|Налаштування|Грати|Створити збірку|Зберегти налаштування|Відкрити профіль|Увійти з Microsoft|Вийти з акаунта|Змінити акаунт|Збірки|Версії|Оновлення|Запуск|МОДИ|ШЕЙДЕРИ|РЕСУРС ПАКИ|СВІТИ|СЕРВЕРИ|СКРИНШОТИ|ЛОГИ|ВЕРСІЯ|НАЛАШТУВАННЯ',tr:'SÜRÜMLER|PAKETLER|KEŞFET|PROFİL|Ayarlar|Oyna|Paket oluştur|Kaydet|Profili aç|Microsoft ile giriş|Çıkış|Hesap değiştir|Paketler|Sürümler|Güncelleme|Başlatılıyor|MODLAR|GÖLGELENDİRİCİLER|KAYNAK PAKETLERİ|DÜNYALAR|SUNUCULAR|EKRAN GÖRÜNTÜLERİ|GÜNLÜKLER|SÜRÜM|AYARLAR',zh:'版本|整合包|发现|个人资料|设置|开始游戏|创建整合包|保存设置|打开资料|使用 Microsoft 登录|退出登录|切换账户|整合包|版本|更新|启动|模组|光影|资源包|世界|服务器|截图|日志|版本|设置',ja:'バージョン|インスタンス|探索|プロフィール|設定|プレイ|インスタンス作成|設定を保存|プロフィールを開く|Microsoft でログイン|ログアウト|アカウント切替|インスタンス|バージョン|更新|起動|MOD|シェーダー|リソースパック|ワールド|サーバー|スクリーンショット|ログ|バージョン|設定',ko:'버전|인스턴스|탐색|프로필|설정|플레이|인스턴스 만들기|설정 저장|프로필 열기|Microsoft 로그인|로그아웃|계정 전환|인스턴스|버전|업데이트|시작|모드|셰이더|리소스 팩|월드|서버|스크린샷|로그|버전|설정'};
 const palettes={dark:['#090e18','#172333','#edf3fc','#9fc8f3',4],light:['#edf3fa','#ffffff','#15243b','#286ac8',8],steam:['#1b2028','#2a2e35','#dcdedf','#1a9fff',2],minecraft:['#171717','#292929','#ffffff','#52a535',0],aero:['#e6f3fa','#f5fcff','#153e57','#1898c6',10],windows:['#171717','#242424','#f2f2f2','#60cdff',8],gradient:['#182538','#26334a','#ffffff','#b6ceff',8],custom:['#090e18','#172333','#edf3fc','#9fc8f3',4]};
 const fonts={pixel:'SpectraPixel',reading:'SpectraReading',segoe:'Segoe UI',arial:'Arial',verdana:'Verdana',tahoma:'Tahoma',consolas:'Consolas',georgia:'Georgia',trebuchet:'Trebuchet MS'};
 const fontValid=id=>Object.hasOwn(fonts,id)||/^custom:[a-f0-9]{64}\.(ttf|otf|woff2?)$/.test(id||'');
 const fontFamily=id=>fonts[id]||('SpectraCustom_'+id.replace(/[^a-z0-9]/gi,''));
 let customFonts=[];
 let config={language:'ru',theme:'dark',colors:['#183950','#40316b','#142634'],angle:135,css:'',headingFont:'pixel',bodyFont:'reading',navigationPosition:'top'}, originals=new WeakMap(),queued=false;
 const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function validate(c){if(!c||typeof c!=='object')throw Error('Некорректная тема');return{navigationPosition:['top','bottom','left','right'].includes(c.navigationPosition)?c.navigationPosition:'top',language:languages[c.language]?c.language:'ru',theme:Object.hasOwn(palettes,c.theme)?c.theme:'dark',colors:(Array.isArray(c.colors)?c.colors:config.colors).filter(x=>/^#[0-9a-f]{6}$/i.test(x)).slice(0,16),angle:Math.max(0,Math.min(360,Number(c.angle)||0)),css:typeof c.css==='string'?c.css.slice(0,60000):'',headingFont:fontValid(c.headingFont)?c.headingFont:'pixel',bodyFont:fontValid(c.bodyFont)?c.bodyFont:'reading'};}
 function text(key){if(config.language==='ru')return key;const index=keys.indexOf(key);return index>=0?rows[config.language]?.split('|')[index]||key:SpectraLocales.dictionary(config.language)[key]||key;}
 function navigation(){const entries=[['versions','ВЕРСИИ','versions'],['instances','СБОРКИ','cube'],['discover','ОБЗОР','discover'],['profile','ПРОФИЛЬ','profile'],['settings','Настройки','edit']];for(const [page,key,icon] of entries){const button=page==='profile'?document.querySelector('#profileTab'):document.querySelector('nav [data-page="'+page+'"]');if(!button)continue;const label=page==='profile'&&!button.hasAttribute('data-i18n')?(typeof state!=='undefined'&&state.profile?.name?.toUpperCase()||button.dataset.navLabel||button.textContent):text(key);button.textContent=label;button.dataset&&(button.dataset.navLabel=label);if(button.setAttribute){button.setAttribute('aria-label',label);button.title=label;button.innerHTML=`<span class="pixel-icon nav-icon" style="--icon-mask:url('assets/${icon}.svg')" aria-hidden="true"></span><span class="nav-label" data-no-i18n>${escape(label)}</span>`;}}}

 function translate(){queued=false;const dict=Object.assign({},typeof SpectraLocales!=='undefined'?SpectraLocales.dictionary(config.language):{},Object.fromEntries(keys.map((k,i)=>[k,config.language==='ru'?k:rows[config.language]?.split('|')[i]||k])));for(const el of document.querySelectorAll?.('[data-i18n]')||[]){if(el.matches?.('#navigation > button'))continue;const key=el.getAttribute('data-i18n');const value=config.language==='ru'?key:dict[key]||key;if(el.textContent!==value)el.textContent=value;}const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){if(n.parentElement?.closest('script,style,textarea,input,pre,[data-no-i18n]'))continue;const current=n.nodeValue;let saved=originals.get(n);if(!saved||current!==saved.rendered)saved={source:current,rendered:current};const raw=saved.source.trim();const translated=dict[raw]||((raw===raw.toUpperCase())?dict[Object.keys(dict).find(k=>k.toUpperCase()===raw)]?.toLocaleUpperCase(config.language):null);const rendered=translated?saved.source.replace(raw,translated):saved.source;if(current!==rendered)n.nodeValue=rendered;originals.set(n,{source:saved.source,rendered});}for(const el of document.querySelectorAll?.('[placeholder],[title],[aria-label]')||[]){if(el.closest('textarea,[data-no-i18n]'))continue;let saved=originals.get(el)||{};for(const attr of ['placeholder','title','aria-label']){const current=el.getAttribute(attr);if(current==null)continue;const prior=saved[attr];const source=prior&&current===prior.rendered?prior.source:current;const rendered=dict[source]||source;if(current!==rendered)el.setAttribute(attr,rendered);saved[attr]={source,rendered};}originals.set(el,saved);}}
 function apply(c){config=validate(c);localStorage.setItem('spectraAppearance',JSON.stringify(config));document.documentElement.lang=config.language;const p=palettes[config.theme];let style=document.querySelector('#themeStyle');if(!style){style=document.createElement('style');style.id='themeStyle';document.head.append(style);}style.textContent=`body{--theme-bg:${p[0]};--theme-panel:${p[1]};--theme-text:${p[2]};--theme-accent:${p[3]};--theme-radius:${p[4]}px;background:${config.theme==='gradient'&&config.colors.length>=2?'linear-gradient('+config.angle+'deg,'+config.colors.join(',')+')':p[0]};color:${p[2]}}`;if(['dark','light','gradient'].includes(config.theme)){
  const ids=[...new Set([config.headingFont,config.bodyFont])];
  style.textContent+=ids.filter(id=>id.startsWith('custom:')).map(id=>`@font-face{font-family:'${fontFamily(id)}';src:url('https://fonts.spectra.local/${id.slice(7)}');font-display:swap}`).join('');
  style.textContent+=`body[data-theme="${config.theme}"]{--ui-font:'${fontFamily(config.bodyFont)}','Segoe UI',sans-serif;--heading-font:'${fontFamily(config.headingFont)}','Segoe UI',sans-serif}`;
 }document.body.dataset.theme=config.theme;document.body.dataset.navigation=config.navigationPosition;let custom=document.querySelector('#customThemeStyle');if(!custom){custom=document.createElement('style');custom.id='customThemeStyle';document.head.append(custom);}custom.textContent=config.css;translate();navigation();}
 let hydrated=false,saveTimer,saveChain=Promise.resolve();
 function hydrate(c){if(hydrated)return;hydrated=true;if(c&&Object.keys(c).length)apply(c);}
 function save(){const snapshot=structuredClone(config);saveChain=saveChain.catch(()=>{}).then(async()=>{const s=await api('appearance',snapshot);updateState(s);});return saveChain;}
 function autoSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>run(save),250);}

 function mount(host){const panel=document.createElement('div');panel.className='panel settings-section';panel.id='appearanceEditor';panel.innerHTML=`<h2>Язык и оформление</h2><div class="form-grid"><label>Язык<select id="uiLanguage">${Object.entries(languages).map(([k,v])=>`<option value="${k}" ${config.language===k?'selected':''}>${v}</option>`).join('')}</select></label><label>Тема<select id="uiTheme">${Object.keys(palettes).map(k=>`<option ${config.theme===k?'selected':''} value="${k}">${({dark:'Тёмная',light:'Светлая',steam:'Steam',minecraft:'Minecraft Launcher',aero:'Frutiger Aero',windows:'Windows 11',gradient:'Градиент',custom:'Пользовательская'})[k]}</option>`).join('')}</select></label><label>Расположение навигации<select id="uiNavigation">${Object.entries({top:'Сверху',bottom:'Снизу',left:'Слева',right:'Справа'}).map(([id,name])=>`<option value="${id}" ${config.navigationPosition===id?'selected':''}>${name}</option>`).join('')}</select></label></div><p class="muted">Язык основных разделов и действий. Расширенные описания пока на русском.</p><div id="fontEditor"><h3>Шрифты интерфейса</h3>${['heading','body'].map(kind=>`<div class="font-row"><label>${kind==='heading'?'Заголовки и важные надписи':'Остальные надписи'}<select data-font-kind="${kind}"></select></label><button data-font-import="${kind}">Загрузить свой…</button><button data-font-both="${kind}">Применить к обоим</button></div>`).join('')}<div class="font-sample"><h2>Твоя коллекция · Spectra</h2><p>Выбери сборку и отправляйся в приключение. Minecraft 123</p></div><p class="muted">TTF, OTF, WOFF, WOFF2 — до 10 МиБ. Шрифты сохраняются в лаунчере. При переносе JSON темы свои шрифты нужно загрузить отдельно.</p></div><h3>Градиент — до 16 цветовых точек</h3><div id="gradientStops"></div><button id="addGradient">Добавить цвет</button><label>Направление <input id="gradientAngle" type="range" min="0" max="360" value="${config.angle}"></label><h3>Пользовательский CSS</h3><p class="muted">Любые селекторы интерфейса и CSS, включая размеры, сетки, шрифты и фон. Применяется поверх выбранного стиля. Переменные: --theme-bg, --theme-panel, --theme-text, --theme-accent, --theme-radius.</p><textarea id="themeCss" rows="7" spellcheck="false" placeholder=".instance-card { border-radius: 24px; }">${escape(config.css)}</textarea><div class="toolbar"><button id="applyAppearance" class="primary">Применить и сохранить</button><button id="exportTheme">Экспорт JSON</button><button id="importTheme">Импорт JSON</button><button id="resetTheme">Сбросить</button></div><input type="file" id="themeFile" accept=".json,application/json" hidden>`;host.prepend(panel);
 const q=s=>panel.querySelector(s);
 function fontControls(){q('#fontEditor').hidden=!['dark','light','gradient'].includes(config.theme);for(const select of panel.querySelectorAll('[data-font-kind]')){const key=select.dataset.fontKind+'Font';const choices=[...Object.entries(fonts).map(([id,name])=>({id,name})),...customFonts.map(f=>({id:'custom:'+f.id,name:f.name}))];if(!choices.some(f=>f.id===config[key]))choices.push({id:config[key],name:'Загруженный шрифт'});select.innerHTML=choices.map(f=>`<option value="${escape(f.id)}" ${config[key]===f.id?'selected':''}>${escape(f.name)}</option>`).join('');select.onchange=()=>{config[key]=select.value;apply(config);autoSave();};}
 }
 fontControls();run(async()=>{customFonts=(await api('fonts')||[]).filter(f=>f&&fontValid('custom:'+f.id));if(panel.isConnected)fontControls();});
 panel.querySelectorAll('[data-font-import]').forEach(button=>button.onclick=()=>run(async()=>{const font=await api('importFont');if(!font)return;if(!fontValid('custom:'+font.id))throw Error('Неверный шрифт');customFonts=customFonts.filter(f=>f.id!==font.id);customFonts.push(font);config[button.dataset.fontImport+'Font']='custom:'+font.id;apply(config);fontControls();await save();}));
 panel.querySelectorAll('[data-font-both]').forEach(button=>button.onclick=()=>{const selected=config[button.dataset.fontBoth+'Font'];config.headingFont=selected;config.bodyFont=selected;apply(config);fontControls();autoSave();});
 function stops(){q('#gradientStops').innerHTML=config.colors.map((c,i)=>`<label><input type="color" value="${c}" data-color="${i}"><button data-remove="${i}" aria-label="Удалить цвет">×</button></label>`).join('');panel.querySelectorAll('[data-color]').forEach(x=>x.oninput=()=>{config.colors[Number(x.dataset.color)]=x.value;apply(config);autoSave();});panel.querySelectorAll('[data-remove]').forEach(x=>x.onclick=()=>{if(config.colors.length<=2)return;config.colors.splice(Number(x.dataset.remove),1);stops();apply(config);autoSave();});}
 q('#uiNavigation').onchange=e=>{config.navigationPosition=e.target.value;apply(config);autoSave();};stops();q('#addGradient').onclick=()=>{if(config.colors.length<16){config.colors.push('#78baff');stops();apply(config);autoSave();}};q('#uiTheme').onchange=e=>{config.theme=e.target.value;apply(config);fontControls();autoSave();};q('#uiLanguage').onchange=e=>{config.language=e.target.value;apply(config);autoSave();};q('#gradientAngle').oninput=e=>{config.angle=Number(e.target.value);apply(config);autoSave();};q('#applyAppearance').onclick=()=>run(async()=>{config.css=q('#themeCss').value;apply(config);await save();toast('Оформление сохранено');});q('#resetTheme').onclick=()=>run(async()=>{apply({language:config.language,theme:'dark',colors:['#183950','#40316b'],angle:135,css:''});await save();renderSettings();});q('#exportTheme').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({...config,css:q('#themeCss').value},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='spectra-theme.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};q('#importTheme').onclick=()=>q('#themeFile').click();q('#themeFile').onchange=()=>run(async()=>{const file=q('#themeFile').files[0];if(!file)return;if(file.size>131072)throw Error('Тема слишком большая');apply(JSON.parse(await file.text()));await save();renderSettings();});}
 new MutationObserver(records=>{if(records.every(r=>r.target.parentElement?.closest('pre,#liveLog,#themeStyle,#customThemeStyle')||r.target.closest?.('pre,#liveLog,#themeStyle,#customThemeStyle')))return;if(!queued){queued=true;requestAnimationFrame(translate);}}).observe(document.body,{childList:true,subtree:true,characterData:true});
 try{apply(JSON.parse(localStorage.getItem('spectraAppearance')||'{}'));}catch{apply(config);autoSave();}
 // Ctrl+Shift+F12 recovers the default theme even if custom CSS hides settings.
 document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.shiftKey&&e.key==='F12'){apply({language:'ru',theme:'dark',colors:['#183950','#40316b'],angle:135,css:''});run(save);}});
 return{apply,mount,validate,hydrate,language:()=>config.language,text,navigation};
})();
