'use strict';
const SpectraBedrock=(()=>{
 let catalog=null,request=0;
 function visiblePackages(items,query='',preview=false,legacy=false,old=false){const rows=items.filter(p=>(preview||!p.preview)&&(legacy||!p.legacy)&&(p.version+' '+p.name).toLowerCase().includes(query.toLowerCase()));rows.sort((a,b)=>b.version.localeCompare(a.version,undefined,{numeric:true}));return old?rows.reverse():rows;}
 function switcher(edition){return `<div class="edition-switch" role="group" aria-label="Издание Minecraft"><button data-edition="java" class="${edition==='java'?'active':''}">Java Edition</button><button data-edition="bedrock" class="${edition==='bedrock'?'active':''}">Bedrock Edition</button></div>`;}
 function bindSwitcher(){document.querySelectorAll('[data-edition]').forEach(b=>b.onclick=()=>{localStorage.setItem('spectra.versionEdition',b.dataset.edition);renderVersions();});}
 async function select(p){updateState(await api('bedrockSelect',{id:p.id,label:p.version}));toast('Выбрана Bedrock '+p.version);}
 async function launch(id=state.selection?.bedrockId){
  if(!id){toast('Выберите установленную или импортированную версию Bedrock');return;}const p=[...(catalog?.installed||[]),...(catalog?.imported||[])].find(p=>p.id===id);
  const start=async(install=false)=>{await api('bedrockLaunch',{id,install});$('#status').textContent='Запуск Minecraft Bedrock';toast('Запуск передан Windows');};
  if(id.startsWith('import:')){modal(`${closeButton()}<h2>Запуск выбранного пакета Bedrock</h2><p>${esc(p?.version||state.selection?.bedrockLabel||'')}</p><p>Если эта версия ещё не установлена, Windows установит пакет Minecraft для текущего пользователя и проверит его подпись. Это переключит установленную версию на выбранную; Windows может отклонить несовместимый пакет. Spectra не удаляет игру или её миры. Перед сменой версии сделайте резервную копию миров.</p><p class="muted">Для запуска нужна лицензия Minecraft в Microsoft Store. Java-вход Spectra не заменяет вход Store.</p><button id="confirmBedrockLaunch" class="primary">Установить при необходимости и запустить</button>`);$('#confirmBedrockLaunch').onclick=()=>run(async()=>{const button=$('#confirmBedrockLaunch');button.disabled=true;try{await start(true);$('#modal').close();}finally{button.disabled=false;}});}else await run(()=>start());
 }
 async function render(){
  const ticket=++request,view=viewSeq;$('#main').innerHTML=`<section>${heading('MINECRAFT FOR WINDOWS','Версии',viewButtons('versions'))}${switcher('bedrock')}<div class="toolbar bedrock-toolbar"><select id="bedrockSort"><option value="new">Сначала новые</option><option value="old">Сначала старые</option></select><label><input id="bedrockPreview" type="checkbox"> Preview / Beta</label><label><input id="bedrockLegacy" type="checkbox"> Windows 10 Edition</label><input id="bedrockSearch" placeholder="Поиск версии…"></div><div class="toolbar"><button id="bedrockImport">Импорт APPX / MSIX</button><button id="bedrockStore">Установить через Microsoft Store ↗</button><button id="bedrockRefresh">Обновить список</button></div><p class="muted">Запускаются установленные версии. Импортированные официальные пакеты устанавливает Windows; старые Windows 10 Edition включаются отдельной галочкой. Каталог обновлений Mojang содержит сведения о выпусках, а не ссылки на установку каждой версии.</p><div id="bedrockList">${empty('Ищем Bedrock','Проверяем установленные приложения Windows…')}</div></section>`;bindSwitcher();bindViews();$('#bedrockStore').onclick=()=>run(()=>api('bedrockStore'));$('#bedrockRefresh').onclick=render;$('#bedrockImport').onclick=()=>run(async()=>{const p=await api('bedrockImport');if(p){toast('Пакет добавлен: '+p.version);await render();}});
  try{catalog=await api('bedrockVersions');if(ticket!==request||view!==viewSeq)return;let limit=24;
   function fill(){const query=$('#bedrockSearch').value.toLowerCase(),preview=$('#bedrockPreview').checked,legacy=$('#bedrockLegacy').checked;
    const rows=visiblePackages([...(catalog.installed||[]),...(catalog.imported||[])],query,preview,legacy,$('#bedrockSort').value==='old');
    const updates=(catalog.updates||[]).filter(p=>p.version.toLowerCase().includes(query)&&(preview||p.patchNoteType==='retail'));
    $('#bedrockList').innerHTML=(catalog.warning?`<div class="warning">${esc(catalog.warning)}</div>`:'')+`<div class="section-label"><h2>Готовые версии и пакеты</h2><span class="muted">${rows.length}</span></div><div class="version-list view-${esc(state.views?.versions||'cards')}">${rows.map(p=>`<article class="version-card ${state.selection?.edition==='bedrock'&&state.selection?.bedrockId===p.id?'selected':''}" tabindex="0" role="button" data-bedrock-select="${esc(p.id)}"><div class="version-art"><img src="assets/terrain.svg" alt=""><span>${esc(p.version)}</span></div><div><h3 data-no-i18n>Minecraft ${esc(p.version)}</h3><span class="muted">${p.legacy?'Windows 10 Edition':p.preview?'Bedrock Preview':'Bedrock Edition'} · Версия пакета Windows · ${p.installed?'Установлена':'Пакет импортирован'}</span></div><button data-bedrock-play="${esc(p.id)}">${pixelIcon('play')} Играть</button></article>`).join('')||empty('Bedrock пока не установлен','Установите Minecraft for Windows через Store или импортируйте официальный пакет.')}</div><div class="section-label"><h2>Обновления Mojang</h2><span class="muted">Информация о выпусках</span></div><div class="version-list view-${esc(state.views?.versions||'cards')}">${updates.slice(0,limit).map((p,i)=>`<article class="version-card" data-bedrock-info="${i}" tabindex="0" role="button"><div class="version-art">${image(p.image?.url?new URL(p.image.url,'https://launchercontent.mojang.com/').href:'')}<span>${esc(p.version)}</span></div><div><h3 data-no-i18n>${esc(p.title)}</h3><span class="muted">${date(p.date)}</span></div><span class="pill">${esc(p.patchNoteType)}</span></article>`).join('')}</div>${updates.length>limit?'<button id="bedrockMore">Показать ещё</button>':''}`;
    document.querySelectorAll('[data-bedrock-select]').forEach(b=>{b.onclick=e=>{if(!e.target.closest('[data-bedrock-play]'))run(async()=>{await select(rows.find(p=>p.id===b.dataset.bedrockSelect));fill();});};b.onkeydown=e=>{if(e.key==='Enter'&&e.target===b)b.click();};});document.querySelectorAll('[data-bedrock-play]').forEach(b=>b.onclick=e=>{e.stopPropagation();run(async()=>{await select(rows.find(p=>p.id===b.dataset.bedrockPlay));await launch(b.dataset.bedrockPlay);});});
    document.querySelectorAll('[data-bedrock-info]').forEach(b=>{b.onclick=()=>{const p=updates[Number(b.dataset.bedrockInfo)];modal(`${closeButton()}<h2 data-no-i18n>${esc(p.title)}</h2><p>${date(p.date)}</p>${image(p.image?.url?new URL(p.image.url,'https://launchercontent.mojang.com/').href:'','artwork-preview')}<p data-no-i18n>${esc(p.shortText||'')}</p><p class="muted">Эта запись — информация об обновлении. Для запуска выберите установленную версию или импортируйте её пакет.</p>`);};b.onkeydown=e=>{if(e.key==='Enter')b.click();};});$('#bedrockMore')?.addEventListener('click',()=>{limit+=24;fill();});
   }
   for(const id of ['bedrockSort','bedrockPreview','bedrockLegacy','bedrockSearch'])$('#'+id).oninput=()=>{limit=24;fill();};fill();
  }catch(e){if(ticket===request&&view===viewSeq)$('#bedrockList').innerHTML=empty('Не удалось проверить Bedrock',esc(e.message));}
 }
 return{render,launch,switcher,bindSwitcher,visiblePackages};
})();
