'use strict';
const SpectraBedrock=(()=>{
 let catalog=null,request=0,pendingCatalogue=null,stale=false;
 function visiblePackages(items,query='',preview=false,legacy=false,old=false){const rows=items.filter(p=>(preview||!p.preview)&&(legacy||!p.legacy)&&(p.version+' '+p.name).toLowerCase().includes(query.toLowerCase()));rows.sort((a,b)=>(b.packageVersion||b.version).localeCompare(a.packageVersion||a.version,undefined,{numeric:true}));if(old)rows.reverse();return [...rows.filter(p=>p.latest),...rows.filter(p=>!p.latest)];}
 function editionName(p){return p.preview?'Bedrock Preview':p.legacy?'Windows 10 Edition':'Bedrock Edition';}
 function selectionCard(){const selected=packages().find(p=>p.id===state.selection?.bedrockId);if(selected)return card(selected);const label=state.selection?.bedrockLabel||'',version=label.replace(/^(?:Bedrock Preview|Windows 10 Edition|Bedrock Edition)\s+/,'');const numbers=version.match(/^(\d+)\.(\d+)/);return card({version,preview:label.includes('Preview'),legacy:numbers?+numbers[1]===0||+numbers[1]===1&&+numbers[2]<2:false});}
 function installConflict(p){return !!p&&!p.installed&&(catalog?.installed||[]).some(i=>i.name.toLowerCase()===p.name.toLowerCase()&&i.version!==p.packageVersion);}
 function latestAction(){return state.selection?.edition==='bedrock'&&state.selection?.bedrockId==='latest'?latestPackage().updateAvailable?'Обновить':latestPackage().installed?'Играть':'Установить':'Играть';}
 function latestPackage(){return {id:'latest',version:'Последняя версия',name:'Minecraft',latest:true,updateAvailable:catalog?.latestStatus?.updateAvailable===true,installed:catalog?.latestStatus?.installed??(catalog?.installed||[]).some(p=>!p.preview)};}
 function packages(){if(!catalog)return [latestPackage()];const available=(catalog.available||[]).map(p=>({...p,installed:(catalog.installed||[]).some(i=>i.name===p.name&&i.version===p.packageVersion)}));const known=new Set(available.map(p=>p.name+':'+p.packageVersion));return [latestPackage(),...available,...(catalog.installed||[]).filter(p=>!known.has(p.name+':'+p.version)),...(catalog.imported||[]).filter(p=>!known.has(p.name+':'+p.version))];}
 async function load(refresh=false){if(catalog&&!refresh&&!stale)return catalog;if(pendingCatalogue&&!refresh)return pendingCatalogue;const task=api('bedrockVersions',{refresh}).then(result=>{catalog=result;stale=false;return result;});pendingCatalogue=task;try{return await task;}finally{if(pendingCatalogue===task)pendingCatalogue=null;}}
 function quickOptions(query=''){return visiblePackages(packages(),query,false,false).concat(packages().filter(p=>p.id===state.selection?.bedrockId&&(p.preview||p.legacy)&&(p.version+' '+p.name).toLowerCase().includes(query.toLowerCase())));}
 function card(p){return `<div class="quick-card"><div class="quick-art"><img src="assets/terrain.svg" alt=""></div><div class="quick-shade"></div><div class="quick-caption">${pixelIcon('cube')}<div><strong data-no-i18n>Minecraft ${esc(p.version)}</strong><span>${editionName(p)}${p.format?' · '+esc(p.format):''}</span></div></div></div>`;}
 function switcher(edition){return `<div class="edition-switch" role="group" aria-label="Издание Minecraft"><button data-edition="java" class="${edition==='java'?'active':''}">Java Edition</button><button data-edition="bedrock" class="${edition==='bedrock'?'active':''}">Bedrock Edition</button></div>`;}
 function bindSwitcher(){document.querySelectorAll('[data-edition]').forEach(b=>b.onclick=()=>{localStorage.setItem('spectra.versionEdition',b.dataset.edition);renderVersions();});}
 async function select(p){if(!p)throw Error('Версия отсутствует в списке');updateState(await api('bedrockSelect',{id:p.id,label:p.latest?p.version:editionName(p)+' '+p.version}));toast('Выбрана '+editionName(p)+' '+p.version);}
 async function launch(id=state.selection?.bedrockId){
  if(!id){toast('Выберите версию Bedrock');return;}const p=packages().find(p=>p.id===id);if(id==='latest'&&p?.updateAvailable){await api('bedrockOfficialLauncher');modal(`${closeButton()}<h2>Обновление Bedrock</h2><p>Скачайте обновление через Minecraft Launcher.</p><p class="muted">Выберите Minecraft for Windows. Если лаунчер не установлен, открыта страница скачивания.</p>`);return;}
  const start=async(install=false,replace=false)=>{busy.add('bedrock');syncPlayButtons();try{const result=await api('bedrockLaunch',{id,install,replace,installOnly:install&&!p?.installed});stale=true;if(result?.status==='installed'){$('#modal').close();toast(result.message);await load(true);if(page==='versions')await render();renderQuick();return;}if(result?.status==='officialLauncher'){modal(`${closeButton()}<h2>Обновление Bedrock</h2><p>${esc(result.message)}</p>`);return;}if(result?.status==='needsInstall'||result?.status==='needsUpdate'){
    modal(`${closeButton()}<h2>Установка Minecraft</h2><p>${esc(result.message)}</p><p class="muted">Установка использует источник Microsoft Store и принимает условия установки пакета и источника WinGet. Прогресс будет показан в Spectra.</p><button id="installLatestBedrock" class="primary">${result.status==='needsUpdate'?'Обновить и запустить':'Скачать версию'}</button><button id="openLatestStore">Открыть Microsoft Store</button>`);$('#openLatestStore').onclick=()=>run(()=>api('bedrockStore'));$('#installLatestBedrock').onclick=()=>run(async()=>{const button=$('#installLatestBedrock');button.disabled=true;try{await start(true);}finally{button.disabled=false;}});return;
   }if(result?.status==='installerUnavailable'){
    modal(`${closeButton()}<h2>Обновление через WinGet недоступно</h2><p>${esc(result.message)}</p><p class="muted">Официальный лаунчер откроется отдельно. Выберите Minecraft for Windows и выполните обновление там; Spectra не сообщает об успешном обновлении, пока его не проверит.</p><button id="openOfficialBedrock" class="primary">Открыть Minecraft Launcher</button><button id="openStoreBedrock">Открыть Microsoft Store</button><button id="playCurrentBedrock">Запустить установленную игру</button><button id="retryBedrockUpdate">Проверить снова</button>`);
    $('#openStoreBedrock').onclick=()=>run(()=>api('bedrockStore'));$('#openOfficialBedrock').onclick=()=>run(()=>api('bedrockOfficialLauncher'));$('#playCurrentBedrock').onclick=()=>run(async()=>{const response=await api('bedrockLaunchCurrent');if(response?.status==='launched'){toast('Запуск передан Windows');$('#modal').close();}else toast(response?.message||'Minecraft не найден');});$('#retryBedrockUpdate').onclick=()=>run(async()=>{await load(true);if(page==='versions')await render();await launch('latest');});return;
   }if(result?.status==='store'){toast(result.message);modal(`${closeButton()}<h2>Установка Minecraft</h2><p>${esc(result.message)}</p><button id="retryLatestBedrock" class="primary">Проверить и запустить</button>`);$('#retryLatestBedrock').onclick=()=>run(()=>launch('latest'));return;}$('#status').textContent='Запуск Minecraft Bedrock';toast('Запуск передан Windows');if(id==='latest'){$('#modal').close();if(page==='versions')await render(true);renderQuick();}}finally{busy.delete('bedrock');syncPlayButtons();}};
  if(id.startsWith('online:')&&installConflict(p)){
   modal(`${closeButton()}<h2>${esc(editionName(p))} ${esc(p.version)}</h2><div class="warning"><strong>Внимание:</strong> замена удалит установленный клиент Minecraft Bedrock (${esc((catalog?.installed||[]).filter(i=>i.name.toLowerCase()===p.name.toLowerCase()).map(i=>i.version).join(', ')||'текущая версия')}) и поставит ${esc(p.version)}. Вернуть прежнюю версию можно только повторной установкой (через Store, если файла нет в кэше Spectra).</div><p>Этот выпуск использует ту же идентичность Windows, что и установленная игра. Spectra не заменяет её. Можно сохранить пакет отдельно или заменить установленную версию на выбранную: перед заменой Spectra копирует всю папку данных (миры, паки, скины, настройки) в bedrock/backups и возвращает её после установки. Версия регистрируется как приложение разработчика (нужен режим разработчика Windows); файлы хранятся в bedrock/versions, снять регистрацию можно кнопкой «Снять регистрацию версий Spectra». Закройте игру перед заменой.</p><div style="display:flex;gap:14px;flex-wrap:wrap;margin-top:18px">${p.format==='GDK'?'':'<button id="replaceBedrock" class="primary">Заменить текущий клиент и запустить</button>'}<button id="downloadBedrockOnly">Скачать отдельно</button></div>`);$('#replaceBedrock')?.addEventListener('click',()=>run(async()=>{const b=$('#replaceBedrock');b.disabled=true;try{await start(true,true);$('#modal').close();}finally{b.disabled=false;}}));$('#downloadBedrockOnly').onclick=()=>run(async()=>{const button=$('#downloadBedrockOnly');button.disabled=true;try{const result=await api('bedrockDownload',{id});toast(result.message);modal(`${closeButton()}<h2>Пакет скачан</h2><p>${esc(result.message)}</p><p data-no-i18n>${esc(result.path)}</p>`);}finally{button.disabled=false;}});return;
  }
  if(id.startsWith('import:')||id.startsWith('online:')){modal(`${closeButton()}<h2>Запуск ${esc(p?editionName(p):'Minecraft')} ${esc(p?.version||state.selection?.bedrockLabel||'')}</h2><p>${id.startsWith('online:')?'Spectra скачает выбранную версию с серверов Microsoft, если её ещё нет в кэше. Импорт файла вручную не нужен.':'Будет использован импортированный пакет.'}</p><p>Установка не должна заменять существующую игру: если обнаружен конфликт версий, Spectra остановит её. MSIXVC сохраняется отдельно; для установки современной игры используйте «Последняя версия». Перед установкой закройте игру и сделайте копии миров.</p><p class="muted">Для запуска нужны лицензия Minecraft и вход в Microsoft Store; для GDK также Gaming Services. Java-вход Spectra не заменяет вход Store.</p><button id="confirmBedrockLaunch" class="primary">Скачать и установить</button>`);$('#confirmBedrockLaunch').onclick=()=>run(async()=>{const button=$('#confirmBedrockLaunch');button.disabled=true;try{await start(true);$('#modal').close();}finally{button.disabled=false;}});}else await run(()=>start());
 }
 async function render(refresh=false){
  const ticket=++request,view=viewSeq;$('#main').innerHTML=`<section>${heading('MINECRAFT FOR WINDOWS','Версии',viewButtons('versions'))}${switcher('bedrock')}<div class="toolbar bedrock-toolbar"><select id="bedrockSort"><option value="new">Сначала новые</option><option value="old">Сначала старые</option></select><label><input id="bedrockPreview" type="checkbox"> Preview / Beta</label><label><input id="bedrockLegacy" type="checkbox"> Windows 10 Edition</label><input id="bedrockSearch" placeholder="Поиск версии…"></div><div class="toolbar"><button id="bedrockAdditions">ДОПОЛНЕНИЯ</button><button id="bedrockImport">Импорт APPX / MSIX</button><button id="bedrockStore">Microsoft Store ↗</button><button id="bedrockRefresh">Обновить список</button><button id="bedrockUnregister">Снять регистрацию версий Spectra</button></div><p class="muted">«Последняя версия» запускает установленную обычную игру; если её нет, предлагает установку в фоне через Microsoft Store / WinGet. «Скачать пакет» сохраняет выбранный выпуск отдельно, без замены игры. Доступность старых файлов зависит от Microsoft. Preview и Windows 10 Edition включаются отдельными галочками.</p><div id="bedrockList">${empty('Ищем версии Bedrock','Получаем каталог и установленные приложения…')}</div></section>`;bindSwitcher();bindViews();$('#bedrockAdditions').onclick=()=>SpectraContent.additions();$('#bedrockStore').onclick=()=>run(()=>api('bedrockStore'));$('#bedrockRefresh').onclick=()=>render(true);$('#bedrockUnregister').onclick=()=>run(async()=>{if(!confirm('Снять с регистрации версии Bedrock, установленные через Spectra? Файлы версий останутся, игру можно будет вернуть через Microsoft Store или официальный лаунчер.'))return;const r=await api('bedrockUnregister');toast(r.message);await render(true);});$('#bedrockImport').onclick=()=>run(async()=>{const p=await api('bedrockImport');if(p){toast('Пакет добавлен: '+p.version);await render(true);}});
  try{await load(refresh);if(ticket!==request||view!==viewSeq)return;let limit=24;
   function fill(){const query=$('#bedrockSearch').value.toLowerCase(),preview=$('#bedrockPreview').checked,legacy=$('#bedrockLegacy').checked,rows=visiblePackages(packages(),query,preview,legacy,$('#bedrockSort').value==='old'),installed=packages().filter(p=>p.installed&&!p.latest),allRows=[...installed,...rows.filter(p=>!p.installed||p.latest)];
    const renderCard=p=>`<article class="version-card ${state.selection?.edition==='bedrock'&&state.selection?.bedrockId===p.id?'selected':''}" tabindex="0" role="button" data-bedrock-select="${esc(p.id)}"><div class="version-art"><img src="assets/terrain.svg" alt=""><span>${esc(p.version)}</span></div><div><h3 data-no-i18n>Minecraft ${esc(p.version)}</h3><span class="muted">${editionName(p)} · ${p.format?esc(p.format)+' · ':''}${p.latest?'Установленная игра / Microsoft Store':p.installed?'Установлена':p.id.startsWith('online:')?'Скачать с Microsoft':'Пакет импортирован'}</span>${p.packageVersion?`<small class="muted" data-no-i18n>Windows: ${esc(p.packageVersion)}</small>`:'<small class="muted">Показана версия пакета Windows</small>'}</div><button data-bedrock-play="${esc(p.id)}">${pixelIcon('play')} ${p.latest?p.updateAvailable?'Обновить':p.installed?'Играть':'Установить':p.installed?'Играть':installConflict(p)?'Версия: скачать или заменить':'Скачать версию'}</button>${(p.installed&&!p.latest||p.id.startsWith('import:'))?`<button data-bedrock-delete="${esc(p.id)}">Удалить</button>`:''}${p.id.startsWith('online:')?`<button data-bedrock-download="${esc(p.id)}">${pixelIcon('download')} Скачать пакет</button>`:''}</article>`;
    const catalogRows=rows.filter(p=>!p.installed||p.latest);
    $('#bedrockList').innerHTML=(catalog.warning?`<div class="warning">${esc(catalog.warning)}</div>`:'')+`<details class="installed-versions" ${localStorage.getItem('spectra.installed.bedrock')!=='closed'?'open':''}><summary>Установленные версии (${installed.length})</summary><div class="version-list view-${esc(state.views?.versions||'cards')}">${installed.slice(0,limit).map(renderCard).join('')||'<p class="muted">Установленных версий нет</p>'}</div></details><div class="section-label"><h2>Каталог Bedrock</h2><span class="muted">${catalogRows.length}</span></div><div class="version-list view-${esc(state.views?.versions||'cards')}">${catalogRows.slice(0,limit).map(renderCard).join('')||empty('Версия не найдена','Измените поиск или включите дополнительные категории.')}</div>${catalogRows.length>limit||installed.length>limit?'<div class="form-actions"><button id="bedrockMore">Показать ещё</button></div>':''}`;
    document.querySelector('.installed-versions')?.addEventListener('toggle',e=>localStorage.setItem('spectra.installed.bedrock',e.target.open?'open':'closed'));
    document.querySelectorAll('[data-bedrock-select]').forEach(b=>{b.onclick=e=>{if(!e.target.closest('[data-bedrock-play],[data-bedrock-download],[data-bedrock-delete]'))run(async()=>{await select(allRows.find(p=>p.id===b.dataset.bedrockSelect));fill();});};b.onkeydown=e=>{if(e.key==='Enter'&&e.target===b)b.click();};});document.querySelectorAll('[data-bedrock-delete]').forEach(b=>b.onclick=e=>{e.stopPropagation();confirmAction('Удалить версию Bedrock?','Клиент будет удалён из Windows. Данные сохранятся в резервной копии bedrock/backups.',async()=>{updateState(await api('bedrockDeleteVersion',{id:b.dataset.bedrockDelete}));stale=true;await render(true);});});document.querySelectorAll('[data-bedrock-play]').forEach(b=>b.onclick=e=>{e.stopPropagation();run(async()=>{await select(allRows.find(p=>p.id===b.dataset.bedrockPlay));await launch(b.dataset.bedrockPlay);});});document.querySelectorAll('[data-bedrock-download]').forEach(b=>b.onclick=e=>{e.stopPropagation();run(async()=>{b.disabled=true;try{const result=await api('bedrockDownload',{id:b.dataset.bedrockDownload});toast(result.message);modal(`${closeButton()}<h2>Пакет скачан</h2><p>${esc(result.message)}</p><p class="muted" data-no-i18n>${esc(result.path)}</p>`);}finally{b.disabled=false;}});});$('#bedrockMore')?.addEventListener('click',()=>{limit+=24;fill();});
   }
   for(const id of ['bedrockSort','bedrockPreview','bedrockLegacy','bedrockSearch'])$('#'+id).oninput=()=>{limit=24;fill();};fill();renderQuick();
  }catch(e){if(ticket===request&&view===viewSeq)$('#bedrockList').innerHTML=empty('Не удалось проверить Bedrock',esc(e.message));}
 }
 return{latestAction,installConflict,selectionCard,editionName,latestPackage,render,launch,switcher,bindSwitcher,visiblePackages,load,quickOptions,card,select};
})();
