'use strict';
const SpectraBedrock=(()=>{
 let catalog=null,request=0,pendingCatalogue=null,stale=false;
 function visiblePackages(items,query='',preview=false,legacy=false,old=false){const rows=items.filter(p=>(preview||!p.preview)&&(legacy||!p.legacy)&&(p.version+' '+p.name).toLowerCase().includes(query.toLowerCase()));rows.sort((a,b)=>(b.packageVersion||b.version).localeCompare(a.packageVersion||a.version,undefined,{numeric:true}));return old?rows.reverse():rows;}
 function packages(){if(!catalog)return [];const available=(catalog.available||[]).map(p=>({...p,installed:(catalog.installed||[]).some(i=>i.name===p.name&&i.version===p.packageVersion)}));const known=new Set(available.map(p=>p.name+':'+p.packageVersion));return [...available,...(catalog.installed||[]).filter(p=>!known.has(p.name+':'+p.version)),...(catalog.imported||[]).filter(p=>!known.has(p.name+':'+p.version))];}
 async function load(refresh=false){if(catalog&&!refresh&&!stale)return catalog;if(pendingCatalogue&&!refresh)return pendingCatalogue;const task=api('bedrockVersions',{refresh}).then(result=>{catalog=result;stale=false;return result;});pendingCatalogue=task;try{return await task;}finally{if(pendingCatalogue===task)pendingCatalogue=null;}}
 function quickOptions(query=''){return visiblePackages(packages(),query,false,false).concat(packages().filter(p=>p.id===state.selection?.bedrockId&&(p.preview||p.legacy)&&(p.version+' '+p.name).toLowerCase().includes(query.toLowerCase())));}
 function card(p){return `<div class="quick-card"><div class="quick-art"><img src="assets/terrain.svg" alt=""></div><div class="quick-shade"></div><div class="quick-caption">${pixelIcon('cube')}<div><strong data-no-i18n>Minecraft ${esc(p.version)}</strong><span>${p.legacy?'Windows 10 Edition':p.preview?'Bedrock Preview':'Bedrock Edition'}${p.format?' · '+esc(p.format):''}</span></div></div></div>`;}
 function switcher(edition){return `<div class="edition-switch" role="group" aria-label="Издание Minecraft"><button data-edition="java" class="${edition==='java'?'active':''}">Java Edition</button><button data-edition="bedrock" class="${edition==='bedrock'?'active':''}">Bedrock Edition</button></div>`;}
 function bindSwitcher(){document.querySelectorAll('[data-edition]').forEach(b=>b.onclick=()=>{localStorage.setItem('spectra.versionEdition',b.dataset.edition);renderVersions();});}
 async function select(p){if(!p)throw Error('Версия отсутствует в списке');updateState(await api('bedrockSelect',{id:p.id,label:p.version}));toast('Выбрана Bedrock '+p.version);}
 async function launch(id=state.selection?.bedrockId){
  if(!id){toast('Выберите версию Bedrock');return;}const p=packages().find(p=>p.id===id);
  const start=async(install=false)=>{busy.add('bedrock');syncPlayButtons();try{await api('bedrockLaunch',{id,install});$('#status').textContent='Запуск Minecraft Bedrock';toast('Запуск передан Windows');stale=true;}finally{busy.delete('bedrock');syncPlayButtons();}};
  if(id.startsWith('import:')||id.startsWith('online:')){modal(`${closeButton()}<h2>Запуск Bedrock ${esc(p?.version||state.selection?.bedrockLabel||'')}</h2><p>${id.startsWith('online:')?'Spectra скачает выбранную версию с серверов Microsoft, если её ещё нет в кэше. Импорт файла вручную не нужен.':'Будет использован импортированный пакет.'}</p><p>Windows установит выбранную версию для текущего пользователя, если она ещё не установлена. При переключении используется общий каталог миров Minecraft: сначала закройте игру и сделайте копии миров. Windows может отклонить несовместимый пакет.</p><p class="muted">Для запуска нужны лицензия Minecraft и вход в Microsoft Store; для GDK также Gaming Services. Java-вход Spectra не заменяет вход Store.</p><button id="confirmBedrockLaunch" class="primary">Скачать при необходимости и запустить</button>`);$('#confirmBedrockLaunch').onclick=()=>run(async()=>{const button=$('#confirmBedrockLaunch');button.disabled=true;try{await start(true);$('#modal').close();}finally{button.disabled=false;}});}else await run(()=>start());
 }
 async function render(refresh=false){
  const ticket=++request,view=viewSeq;$('#main').innerHTML=`<section>${heading('MINECRAFT FOR WINDOWS','Версии',viewButtons('versions'))}${switcher('bedrock')}<div class="toolbar bedrock-toolbar"><select id="bedrockSort"><option value="new">Сначала новые</option><option value="old">Сначала старые</option></select><label><input id="bedrockPreview" type="checkbox"> Preview / Beta</label><label><input id="bedrockLegacy" type="checkbox"> Windows 10 Edition</label><input id="bedrockSearch" placeholder="Поиск версии…"></div><div class="toolbar"><button id="bedrockImport">Импорт APPX / MSIX</button><button id="bedrockStore">Microsoft Store ↗</button><button id="bedrockRefresh">Обновить список</button></div><p class="muted">Выберите выпуск: Spectra скачает пакет с Microsoft и попросит Windows установить его. Доступность старых файлов зависит от Microsoft. Preview и Windows 10 Edition включаются отдельными галочками.</p><div id="bedrockList">${empty('Ищем версии Bedrock','Получаем каталог и установленные приложения…')}</div></section>`;bindSwitcher();bindViews();$('#bedrockStore').onclick=()=>run(()=>api('bedrockStore'));$('#bedrockRefresh').onclick=()=>render(true);$('#bedrockImport').onclick=()=>run(async()=>{const p=await api('bedrockImport');if(p){toast('Пакет добавлен: '+p.version);await render(true);}});
  try{await load(refresh);if(ticket!==request||view!==viewSeq)return;let limit=24;
   function fill(){const query=$('#bedrockSearch').value.toLowerCase(),preview=$('#bedrockPreview').checked,legacy=$('#bedrockLegacy').checked,rows=visiblePackages(packages(),query,preview,legacy,$('#bedrockSort').value==='old');
    $('#bedrockList').innerHTML=(catalog.warning?`<div class="warning">${esc(catalog.warning)}</div>`:'')+`<div class="section-label"><h2>Версии Bedrock</h2><span class="muted">${rows.length}</span></div><div class="version-list view-${esc(state.views?.versions||'cards')}">${rows.slice(0,limit).map(p=>`<article class="version-card ${state.selection?.edition==='bedrock'&&state.selection?.bedrockId===p.id?'selected':''}" tabindex="0" role="button" data-bedrock-select="${esc(p.id)}"><div class="version-art"><img src="assets/terrain.svg" alt=""><span>${esc(p.version)}</span></div><div><h3 data-no-i18n>Minecraft ${esc(p.version)}</h3><span class="muted">${p.legacy?'Windows 10 Edition':p.preview?'Bedrock Preview':'Bedrock Edition'} · ${p.format?esc(p.format)+' · ':''}${p.installed?'Установлена':p.id.startsWith('online:')?'Скачать с Microsoft':'Пакет импортирован'}</span>${p.packageVersion?`<small class="muted" data-no-i18n>Windows: ${esc(p.packageVersion)}</small>`:'<small class="muted">Показана версия пакета Windows</small>'}</div><button data-bedrock-play="${esc(p.id)}">${pixelIcon('play')} ${p.installed?'Играть':'Установить и играть'}</button></article>`).join('')||empty('Версия не найдена','Измените поиск или включите дополнительные категории.')}</div>${rows.length>limit?'<button id="bedrockMore">Показать ещё</button>':''}`;
    document.querySelectorAll('[data-bedrock-select]').forEach(b=>{b.onclick=e=>{if(!e.target.closest('[data-bedrock-play]'))run(async()=>{await select(rows.find(p=>p.id===b.dataset.bedrockSelect));fill();});};b.onkeydown=e=>{if(e.key==='Enter'&&e.target===b)b.click();};});document.querySelectorAll('[data-bedrock-play]').forEach(b=>b.onclick=e=>{e.stopPropagation();run(async()=>{await select(rows.find(p=>p.id===b.dataset.bedrockPlay));await launch(b.dataset.bedrockPlay);});});$('#bedrockMore')?.addEventListener('click',()=>{limit+=24;fill();});
   }
   for(const id of ['bedrockSort','bedrockPreview','bedrockLegacy','bedrockSearch'])$('#'+id).oninput=()=>{limit=24;fill();};fill();
  }catch(e){if(ticket===request&&view===viewSeq)$('#bedrockList').innerHTML=empty('Не удалось проверить Bedrock',esc(e.message));}
 }
 return{render,launch,switcher,bindSwitcher,visiblePackages,load,quickOptions,card,select};
})();
