'use strict';
const SpectraContent=(()=>{
 let edition=localStorage.getItem('spectra.discoverEdition')||'java',kind='modpacks',ticket=0;
 const names={modpacks:'МОДПАКИ',skins:'СКИНЫ',worlds:'КАРТЫ',addons:'АДДОНЫ',resources:'ТЕКСТУР ПАКИ'};
 function categories(){return edition==='java'?['modpacks','skins','worlds']:['addons','skins','worlds','resources'];}
 function controls(){return `<div class="edition-switch"><button data-content-edition="java" class="${edition==='java'?'active':''}">Java Edition</button><button data-content-edition="bedrock" class="${edition==='bedrock'?'active':''}">Bedrock Edition</button></div><div class="content-tabs">${categories().map(k=>`<button data-content-kind="${k}" class="${kind===k?'active':''}">${names[k]}</button>`).join('')}</div>`;}
 function bindControls(){ $$('[data-content-edition]').forEach(b=>b.onclick=()=>{edition=b.dataset.contentEdition;localStorage.setItem('spectra.discoverEdition',edition);kind=categories()[0];render();});$$('[data-content-kind]').forEach(b=>b.onclick=()=>{kind=b.dataset.contentKind;render();});}
 async function render(){
  if(!categories().includes(kind))kind=categories()[0];const t=++ticket;
  if(kind==='modpacks'){await renderModpacks();if(t!==ticket||page!=='discover')return;$('#main section').insertAdjacentHTML('afterbegin',controls());bindControls();return;}
  $('#main').innerHTML=`<section>${heading('КОНТЕНТ СООБЩЕСТВА','Обзор')}${controls()}<div class="toolbar"><input id="contentQuery" placeholder="Поиск…"><select id="contentProvider"></select><button id="contentSearch">Найти</button><button id="contentImport">Импорт скачанного файла</button></div><p class="muted">Выберите источник. Если сайт требует вход или подтверждение загрузки, скачайте файл на сайте и импортируйте его здесь.</p><div id="contentResults"></div><button id="contentMore" hidden>Показать ещё</button></section>`;bindControls();
  const sources=await api('contentSources',{edition,kind,query:''});if(t!==ticket||page!=='discover')return;
  $('#contentProvider').innerHTML=sources.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('');let offset=0;
  async function search(append=false,inBrowser=false){const request=++ticket;if(!append){offset=0;$('#contentResults').innerHTML=empty('Получаем каталог','Загружаем список с выбранного сайта…');}
   const e=edition,k=kind,source=$('#contentProvider').value,query=$('#contentQuery').value;
   try{const result=await api(inBrowser?'contentBrowserSearch':'contentSearch',{edition:e,kind:k,source,query,offset});if(request!==ticket||!$('#contentResults'))return;
    const cards=result.items.map(x=>`<article class="catalog-card"><div class="catalog-top"><div class="catalog-icon">${image(x.icon)||pixelIcon('cube')}</div><h3>${esc(x.title)}</h3></div><p>${esc(x.description||'')}</p><div class="catalog-bottom"><button data-content-link="${esc(x.url)}">Открыть сайт ↗</button><button data-content-download="${esc(x.id)}" data-url="${esc(x.url)}" class="primary">Скачать</button></div></article>`).join('');
    if(append)$('#contentResults .catalog-grid')?.insertAdjacentHTML('beforeend',cards);else $('#contentResults').innerHTML=(result.warning?`<div class="warning">${esc(result.warning)} <button id="contentOpenInSpectra">Открыть в Spectra</button><button id="contentOpenSource">Открыть в браузере ↗</button></div>`:'')+`<div class="catalog-grid">${cards}</div>`;
    $('#contentOpenInSpectra')?.addEventListener('click',()=>run(()=>search(false,true)));
    $('#contentOpenSource')?.addEventListener('click',()=>api('openLink',{url:result.url}));
    $$('[data-content-link]').forEach(b=>b.onclick=()=>run(()=>api('openLink',{url:b.dataset.contentLink})));
    $$('[data-content-download]').forEach(b=>b.onclick=()=>download({edition:e,kind:k,source,projectId:b.dataset.contentDownload,url:b.dataset.url}));
    $('#contentMore').hidden=!result.hasMore;offset+=24;
   }catch(error){if(request===ticket&&$('#contentResults'))$('#contentResults').innerHTML=empty('Не удалось загрузить каталог',esc(error.message));}
  }
  $('#contentSearch').onclick=()=>run(()=>search());$('#contentProvider').onchange=()=>run(()=>search());$('#contentQuery').onkeydown=e=>{if(e.key==='Enter')run(()=>search());};$('#contentImport').onclick=()=>importFile();$('#contentMore').onclick=()=>run(()=>search(true));await run(()=>search());
 }
 async function targetDialog(action){
  await getVersions();modal(`${closeButton()}<h2>Куда установить карту?</h2><p>Выберите сборку или версию Minecraft. При необходимости версия сначала скачается.</p><label>Сборка или версия<select id="worldDestination">${state.instances.map(i=>`<option value="instance:${esc(i.id)}">${esc(i.name)} · ${esc(i.version)}</option>`).join('')}${versions.map(v=>`<option value="version:${esc(v.id)}">Minecraft ${esc(v.id)}</option>`).join('')}</select></label><div class="form-actions"><button id="worldCancel">Отмена</button><button id="worldInstall" class="primary">Установить карту</button></div>`);
  $('#worldCancel').onclick=()=>$('#modal').close();$('#worldInstall').onclick=()=>run(async()=>{const b=$('#worldInstall');b.disabled=true;const [type,id]=$('#worldDestination').value.split(':');try{const close=await action(type==='instance'?{instanceId:id}:{version:id});if(close!==false)$('#modal').close();}finally{if(b.isConnected)b.disabled=false;}});
 }
 async function perform(action,data){
  const result=await api(action,data);if(result?.cancelled)return false;
  if(result?.status==='manualDownload'){modal(`${closeButton()}<h2>Скачивание на сайте</h2><p>${esc(result.message)}</p><div class="form-actions"><button id="downloadOnSite" class="primary">Открыть страницу загрузки</button><button id="importAfterDownload">Импортировать файл</button></div>`);$('#downloadOnSite').onclick=()=>run(()=>api('openLink',{url:result.url}));$('#importAfterDownload').onclick=()=>{ $('#modal').close();importFile();};return false;}
  updateState(await api('state'));toast(result.message||'Контент установлен');return true;
 }
 function download(data){if(data.edition==='java'&&data.kind==='worlds')run(()=>targetDialog(target=>perform('contentDownload',{...data,...target})));else run(()=>perform('contentDownload',{...data,variant:'classic'}));}
 function importFile(){const data={edition,kind,variant:'classic'};if(edition==='java'&&kind==='worlds')run(()=>targetDialog(target=>perform('contentImport',{...data,...target})));else run(()=>perform('contentImport',data));}
 async function additions(){
  modal(`${closeButton()}<h2>Дополнения Bedrock</h2><p class="muted">Файлы открываются в Minecraft при запуске последней версии. В списке показаны файлы Spectra и дополнения, установленные в игре. Перед удалением установленного дополнения создаётся резервная копия.</p><div class="content-tabs">${['addons','worlds','resources'].map(k=>`<button data-addition-kind="${k}">${names[k]}</button>`).join('')}</div><div id="additionItems"></div>`);
  const items=await api('bedrockContent');if(!$('#additionItems'))return;
  function fill(k){$('#additionItems').innerHTML=items.filter(x=>x.kind===k).map(x=>`<div class="content-source"><span>${esc(x.name)}<small class="muted"> · ${x.installed?'Установлено в игре':'Файл Spectra для импорта'}</small></span><button data-delete-addition="${esc(x.id)}">Удалить</button></div>`).join('')||'<p class="muted">В этой категории пока пусто</p>';$$('[data-delete-addition]').forEach(b=>b.onclick=()=>confirmAction('Удалить дополнение?',items.find(x=>x.id===b.dataset.deleteAddition)?.name||'',async()=>{await api('bedrockContentDelete',{id:b.dataset.deleteAddition});setTimeout(()=>additions(),0);}));}
  $$('[data-addition-kind]').forEach(b=>b.onclick=()=>fill(b.dataset.additionKind));fill('addons');
 }
 function settings(host){host.insertAdjacentHTML('beforeend',`<div class="panel settings-section"><h2>Окно лаунчера</h2><button id="launcherFullscreen">${state.launcherFullscreen?'Выйти из полноэкранного режима':'Полноэкранный режим'} · F11</button></div><div class="panel settings-section"><h2>Скины Bedrock</h2><p id="skinDownloadFolder" data-no-i18n>${esc(state.bedrockSkinFolder||'Загрузки')}</p><button id="pickBedrockSkinFolder">Изменить папку загрузки</button></div>`);host.insertAdjacentHTML('beforeend',`<div class="panel settings-section"><h2>NameMC API</h2><p>Для Parse нужен отдельный ключ. ${state.parseConfigured?'Ключ сохранён.':'Ключ не задан.'} Поиск через API принимает ник игрока; без запроса показываются популярные скины.</p><input type="password" id="parseApiKey" autocomplete="off" placeholder="Parse API key"><button id="saveParseKey">Сохранить ключ</button><button id="clearParseKey">Удалить ключ</button></div>`);$('#saveParseKey').onclick=()=>run(async()=>{const key=$('#parseApiKey').value.trim();if(!key)throw new Error('Введите ключ Parse');updateState(await api('settings',{parseKey:key}));$('#parseApiKey').value='';toast('Ключ сохранён');});$('#clearParseKey').onclick=()=>run(async()=>{updateState(await api('settings',{clearParseKey:true}));toast('Ключ удалён');});$('#launcherFullscreen').onclick=()=>run(async()=>{await api('window',{command:'fullscreen'});updateState(await api('state'));$('#launcherFullscreen').textContent=(state.launcherFullscreen?'Выйти из полноэкранного режима':'Полноэкранный режим')+' · F11';});$('#pickBedrockSkinFolder').onclick=()=>run(async()=>{updateState(await api('bedrockSkinFolder'));$('#skinDownloadFolder').textContent=state.bedrockSkinFolder;});}
 document.addEventListener('keydown',e=>{if(e.key==='F11'&&!e.repeat){e.preventDefault();api('window',{command:'fullscreen'}).catch(()=>{});}});
 return {render,settings,additions};
})();
