'use strict';
(()=>{
 let tab='friends',refreshing=false,items=[],request=0,search='',panelAnimation=null,closing=false;
 const panel=$('#friendsPanel');
 function showPanel(){closing=false;panelAnimation?.cancel();panel.hidden=false;if(!matchMedia('(prefers-reduced-motion: reduce)').matches)panelAnimation=panel.animate([{opacity:0,transform:'translateY(-10px) scale(.97)'},{opacity:1,transform:'none'}],{duration:220,easing:'cubic-bezier(.2,.8,.2,1)'});}
 function hidePanel(){if(panel.hidden||closing)return;closing=true;request++;panelAnimation?.cancel();if(matchMedia('(prefers-reduced-motion: reduce)').matches){panel.hidden=true;closing=false;return;}panelAnimation=panel.animate([{opacity:1,transform:'none'},{opacity:0,transform:'translateY(-8px) scale(.98)'}],{duration:160,easing:'ease-in',fill:'forwards'});panelAnimation.onfinish=()=>{panel.hidden=true;closing=false;panelAnimation?.cancel();};}

 const tr=text=>typeof SpectraAppearance==='undefined'?text:SpectraAppearance.text(text);
 function canJoin(p){return p?.playing&&['servers','lan'].includes(p.targetKind)&&!!p.target;}
 function status(friend){if(!friend.online)return tr('Не в сети');const p=friend.presence;if(!p?.playing)return tr('В сети')+' · Spectra';const base=`Minecraft ${p.version} · ${p.loader} ${p.loaderVersion||''}`;const mode=p.gameState||(p.targetKind==='servers'?'server':p.targetKind==='worlds'?'world':p.targetKind==='lan'?'lan':'menu');return base+' · '+(mode==='menu'?tr('Главное меню / загрузка'):mode==='connecting'?tr('Подключается')+': '+p.target:mode==='server'?tr('Сервер')+': '+p.target:mode==='world'?tr('Одиночный мир')+(p.worldName||p.target?': '+(p.worldName||p.target):''):mode==='lan'?tr('LAN-мир')+(p.worldName?': '+p.worldName:'')+(p.target?' · '+p.target:' · '+tr('Адрес не определён')):'');}
 async function refresh(){if(refreshing||panel.hidden)return;refreshing=true;const ticket=++request;try{const result=await api('friends');if(ticket!==request||panel.hidden)return;items=result.items||[];state.friendsSharingError=result.sharingError||'';draw();}catch(e){if(!panel.hidden)panel.innerHTML=`<h2>Друзья</h2><p>${esc(e.message)}</p><button id="friendsConnect">Подключиться к сети Spectra</button><button id="friendsSetup">Настройки сервера</button>`;$('#friendsConnect')?.addEventListener('click',()=>{hidePanel();registration();});$('#friendsSetup')?.addEventListener('click',()=>{hidePanel();navigate('settings');});}finally{refreshing=false;if(ticket!==request&&!panel.hidden&&!closing)refresh();}}
 function draw(){
 const rows=items.filter(f=>(tab==='friends'?f.relation==='friend':f.relation!=='friend')&&(`${f.name} ${f.minecraftName||''}`).toLocaleLowerCase().includes(search.toLocaleLowerCase())).sort((a,b)=>Number(b.online)-Number(a.online)||a.name.localeCompare(b.name));
 panel.innerHTML=`<div class="section-label"><div><div class="eyebrow">SPECTRA NETWORK</div><h2>Друзья <small class="friends-count">${items.filter(f=>f.relation==='friend'&&f.online).length} в сети</small></h2></div><button id="friendsClose" aria-label="Закрыть">×</button></div><div class="friends-tabs"><button id="myFriends" class="${tab==='friends'?'active':''}">Мои друзья</button><button id="friendRequests" class="${tab==='requests'?'active':''}">Запросы (${items.filter(f=>f.relation==='incoming').length})</button></div><label class="friends-search"><input id="friendsFilter" placeholder="Найти друга…" value="${esc(search)}" maxlength="48"></label><div class="friends-list">${rows.map(f=>`<article class="friend-row"><button data-friend-profile="${esc(f.id)}" class="friend-avatar ${f.online?'is-online':'is-offline'}">${esc(f.name[0])}</button><div class="friend-details"><button class="text-button" data-friend-profile="${esc(f.id)}" data-no-i18n>${esc(f.name)}</button>${f.minecraftName?`<small class="muted">Minecraft: ${esc(f.minecraftName)} · не подтверждён</small>`:''}<small title="Статус определён по логу Minecraft" class="${f.online?'friend-online':'muted'}">${esc(f.relation==='incoming'?'Входящий запрос':f.relation==='outgoing'?'Ожидает подтверждения':status(f))}</small><div>${f.relation==='incoming'?`<button data-friend-op="accept" data-id="${esc(f.id)}">Принять</button><button data-friend-op="decline" data-id="${esc(f.id)}">Отклонить</button>`:f.relation==='outgoing'?`<button data-friend-op="cancel" data-id="${esc(f.id)}">Отменить</button>`:`${f.online&&canJoin(f.presence)?`<button data-friend-join="${esc(f.id)}">Подключиться</button>`:''}${f.online&&f.presence?.playing&&f.presence?.sharedPack?`<button data-friend-download="${esc(f.id)}">Скачать сборку</button>`:''}<button data-friend-op="remove" data-id="${esc(f.id)}">Удалить</button>`}</div></div></article>`).join('')||'<div class="friends-empty"><span>◇</span><p>Здесь появятся ваши друзья</p><small>Добавьте друга по его имени Spectra</small></div>'}</div>${state.friendsSharingError?`<p class="friend-sharing-error">${esc(state.friendsSharingError)}</p>`:''}<div class="friends-actions"><button id="addFriend">Добавить друга</button><button id="shareLan">Поделиться LAN-миром</button></div>`;
 $('#friendsFilter').oninput=e=>{const value=e.target.value,position=e.target.selectionStart;search=value;draw();$('#friendsFilter').focus();$('#friendsFilter').setSelectionRange(position,position);};
 $('#friendsClose').onclick=()=>{hidePanel();};$('#myFriends').onclick=()=>{tab='friends';draw();};$('#friendRequests').onclick=()=>{tab='requests';draw();};$('#addFriend').onclick=playerBrowser;$('#shareLan').onclick=shareLan;
 $$('[data-friend-op]').forEach(b=>b.onclick=()=>run(async()=>{if(b.dataset.friendOp==='remove'){const friend=items.find(f=>f.id===b.dataset.id);confirmAction('Удалить друга?',friend?.name||'',async()=>{await api('friendAction',{id:b.dataset.id,operation:'remove'});showPanel();await refresh();});return;}b.disabled=true;await api('friendAction',{id:b.dataset.id,operation:b.dataset.friendOp});await refresh();}));
 $$('[data-friend-profile]').forEach(b=>b.onclick=()=>networkProfile(items.find(f=>f.id===b.dataset.friendProfile)));
 $$('[data-friend-download]').forEach(b=>b.onclick=()=>join(items.find(f=>f.id===b.dataset.friendDownload),true));
 $$('[data-friend-join]').forEach(b=>b.onclick=()=>join(items.find(f=>f.id===b.dataset.friendJoin)));
 }
 function networkProfile(player){hidePanel();modal(`${closeButton()}<h2 data-no-i18n>${esc(player.name)}</h2><p>${esc(status(player))}</p><p>Minecraft: ${esc(player.minecraftName||'Не указан')} · не подтверждён</p><p class="muted">Аккаунт Spectra: ${esc(player.id)}</p><p class="muted">Minecraft-ник не подтверждает личность владельца аккаунта Spectra.</p>${player.minecraftName?'<button id="networkMinecraftProfile">Minecraft-профиль</button>':''}`);$('#networkMinecraftProfile')?.addEventListener('click',()=>run(async()=>{const found=await api('player',{name:player.minecraftName});$('#modal').close();await navigate('profile');renderProfile(found);}));}
 function playerBrowser(prefill=''){hidePanel();modal(`${closeButton()}<h2>Найти друга</h2><p>Ищите по уникальному имени Spectra. Поиск по Minecraft-нику также доступен, но его принадлежность не подтверждена. Уточните имя Spectra у друга.</p><form id="friendSearchForm" class="toolbar"><input id="friendNickname" placeholder="Имя Spectra или Minecraft-ник" value="${esc(typeof prefill==='string'?prefill:'')}" minlength="2" maxlength="24" required><button class="primary">Найти</button></form><div id="friendSearchResult"></div><button id="friendCrafty">Открыть браузер игроков Crafty ↗</button>`);$('#friendCrafty').onclick=()=>run(()=>api('external',{url:'https://crafty.gg/players'}));$('#friendSearchForm').onsubmit=e=>{e.preventDefault();run(async()=>{const result=await api('friendsSearch',{query:$('#friendNickname').value.trim()});if(!$('#friendSearchResult'))return;$('#friendSearchResult').innerHTML=(result.items||[]).map(player=>`<div class="panel"><h3 data-no-i18n>${esc(player.name)}</h3><p>Minecraft: ${esc(player.minecraftName||'Не указан')} · не подтверждён</p><small>${esc(player.id)}</small><div class="toolbar"><button data-request-network="${esc(player.id)}">Отправить запрос</button></div></div>`).join('')||'<p>Игроки не найдены. Друг должен подключиться к этой сети Spectra через Google.</p>';$$('[data-request-network]').forEach(b=>b.onclick=()=>run(async()=>{await api('friendAction',{id:b.dataset.requestNetwork,operation:'request'});$('#modal').close();toast('Запрос дружбы отправлен');showPanel();tab='requests';await refresh();}));});};}
 async function join(friend,downloadOnly=false){hidePanel();modal(`${closeButton()}<h2>Сборка ${esc(friend.name)}</h2><p role="status">Сравниваем включённые моды ваших сборок…</p><span id="friendPlanTicket" data-id="${esc(friend.id)}" hidden></span>`);try{const plan=await api('friendPackPlan',{id:friend.id});if(!$('#modal').open||$('#friendPlanTicket')?.dataset.id!==friend.id)return;packDialog(friend,plan,downloadOnly);}catch(e){if($('#modal').open&&$('#friendPlanTicket')?.dataset.id===friend.id)modal(`${closeButton()}<h2>Сборка друга недоступна</h2><p>${esc(e.message)}</p><p class="muted">Друг должен использовать новую версию Spectra и показывать игровую активность. Для передачи файлов серверу нужно хранилище R2.</p>`);}}
 function packDialog(friend,plan,downloadOnly=false){
  const matching=state.instances.filter(i=>plan.matching.includes(i.id)),manifest=plan.manifest,connect=canJoin(plan.presence)&&!downloadOnly;
  modal(`${closeButton()}<div class="eyebrow">СОВМЕСТНАЯ ИГРА</div><h2>Сборка ${esc(friend.name)}</h2><div class="friend-pack-summary"><h3 data-no-i18n>${esc(manifest.name)}</h3><span>Minecraft ${esc(manifest.version)} · ${esc(manifest.loader)} ${esc(manifest.loaderVersion)}</span><small>${manifest.files.filter(f=>f.kind==='mods').length} модов · ${(manifest.files.reduce((n,f)=>n+f.size,0)/1048576).toFixed(1)} МиБ</small></div>${matching.length&&connect?`<div class="panel"><p>Найдены сборки с таким же составом включённых модов:</p><select id="matchingFriendPack">${matching.map(i=>`<option value="${esc(i.id)}">${esc(i.name)}</option>`).join('')}</select><button id="joinMatchingFriend" class="primary">Подключиться</button></div>`:matching.length?'<p>Подходящая сборка уже есть. При желании можно установить ещё одну копию.</p>':'<p>У вас пока нет сборки с таким же составом включённых модов.</p>'}<form id="friendPackInstall"><label>Куда установить<select id="friendPackTarget"><option value="">Создать новую сборку</option>${state.instances.filter(i=>!state.running.includes(i.id)).map(i=>`<option value="${esc(i.id)}">Заменить: ${esc(i.name)}</option>`).join('')}</select></label><p class="muted" id="overwriteFriendHint" hidden>Выбранные папки будут заменены. Предыдущие файлы сохранятся в папке backups; миры останутся на месте.</p><div class="friend-pack-categories">${['mods','shaders','resources'].map(kind=>{const files=manifest.files.filter(f=>f.kind===kind),title={mods:'Моды',shaders:'Шейдеры',resources:'Ресурс паки'}[kind];return `<section class="friend-pack-category"><label><input type="checkbox" data-pack-category="${kind}" ${kind==='mods'?'checked':''}> ${title} <small>${files.length}</small></label><details><summary>Выбрать файлы</summary><div class="friend-pack-files">${files.map(f=>`<label><input type="checkbox" data-pack-file="${esc(f.kind+'/'+f.name)}" data-kind="${kind}" checked><span data-no-i18n>${esc(f.name)}</span><small>${(f.size/1048576).toFixed(1)} МиБ</small></label>`).join('')||'<p class="muted">Нет файлов</p>'}</div></details></section>`;}).join('')}</div><p class="muted">Если убрать моды из списка, состав сборки изменится и сервер может отклонить подключение.</p><button class="primary" id="installFriendButton">Установить сборку</button><p id="friendInstallStatus" role="status"></p></form>`);
  $('#friendPackTarget').onchange=e=>{$('#overwriteFriendHint').hidden=!e.target.value;$('#installFriendButton').textContent=e.target.value?'Заменить выбранные папки':'Установить сборку';};
  $('#joinMatchingFriend')?.addEventListener('click',()=>run(async()=>{const b=$('#joinMatchingFriend');b.disabled=true;try{updateState(await api('joinFriend',{id:friend.id,instanceId:$('#matchingFriendPack').value}));$('#modal').close();navigate('instances');}finally{b.disabled=false;}}));
  $('#friendPackInstall').onsubmit=e=>{e.preventDefault();const target=$('#friendPackTarget').value,categories=$$('[data-pack-category]:checked').map(x=>x.dataset.packCategory),selected=$$('[data-pack-file]:checked').filter(x=>categories.includes(x.dataset.kind)).map(x=>x.dataset.packFile);if(!categories.length){toast('Выберите хотя бы одну категорию');return;}
   const install=async()=>{const button=$('#installFriendButton');button.disabled=true;$('#friendInstallStatus').textContent='Скачиваем файлы и проверяем контрольные суммы…';try{const result=await api('installFriendPack',{id:friend.id,packId:plan.packId,overwrite:target,categories,selected});updateState(result.state);installedFriend(friend,result.instanceId,result.presence||plan.presence);}finally{if($('#installFriendButton'))$('#installFriendButton').disabled=false;}};
   if(target){$('#friendPackInstall .friend-overwrite-confirm')?.remove();const label=state.instances.find(i=>i.id===target)?.name||'';const approved=document.createElement('div');approved.className='friend-overwrite-confirm';approved.innerHTML=`<p>Заменить выбранные папки в сборке «${esc(label)}»?</p><button type="button" class="primary">Да, заменить с резервной копией</button><button type="button">Отмена</button>`;$('#friendPackInstall').append(approved);buttonConfirm(approved,install);}else run(install);
  };
 }
 function buttonConfirm(host,action){const buttons=host.querySelectorAll('button');buttons[0].onclick=()=>{host.remove();run(action);};buttons[1].onclick=()=>host.remove();}
 function installedFriend(friend,instanceId,presence){modal(`${closeButton()}<h2>Сборка установлена</h2><p>Файлы проверены и готовы к игре.</p>${presence.targetKind==='servers'?`<label><input type="checkbox" id="addFriendServer" checked> Добавить ${esc(presence.target)} в список серверов</label>`:''}<div class="toolbar"><button id="finishFriendInstall">Готово</button>${canJoin(presence)?'<button id="playInstalledFriend" class="primary">Подключиться к другу</button>':''}</div>`);
  let saved=false;async function saveServer(){if(saved||!$('#addFriendServer')?.checked)return;const list=await api('files',{instanceId,kind:'servers'});if(!list.some(f=>f.address===presence.target))await api('serverAction',{instanceId,operation:'add',index:-1,name:friend.name+' · сервер',address:presence.target});saved=true;}
  $('#finishFriendInstall').onclick=()=>run(async()=>{await saveServer();$('#modal').close();navigate('instances');});if($('#playInstalledFriend'))$('#playInstalledFriend').onclick=()=>run(async()=>{const b=$('#playInstalledFriend');b.disabled=true;try{await saveServer();updateState(await api('joinFriend',{id:friend.id,instanceId,allowCustomized:true}));$('#modal').close();navigate('instances');}finally{b.disabled=false;}});
 }
 function shareLan(){hidePanel();modal(`${closeButton()}<h2>Поделиться LAN-миром</h2><p>В Minecraft нажмите «Открыть для сети». Spectra определит порт из лога и адрес компьютера автоматически. Если выбран неверный сетевой адаптер, здесь можно указать адрес вручную. Друзья должны находиться в той же сети; Windows должна разрешать Java входящие подключения.</p><input id="lanAddress" placeholder="192.168.1.5:54321"><button id="saveLan" class="primary">Показать друзьям</button><button id="clearLan">Убрать адрес</button>`);$('#saveLan').onclick=()=>run(async()=>{await api('shareLan',{address:$('#lanAddress').value.trim()});$('#modal').close();toast('LAN-адрес доступен друзьям');});$('#clearLan').onclick=()=>run(async()=>{await api('shareLan',{address:''});$('#modal').close();});}
 function settings(host){host.insertAdjacentHTML('beforeend',`<div class="panel settings-section"><h2>Друзья Spectra</h2><p>Все друзья должны подключаться к одной сети Spectra через Google. Minecraft-токен серверу друзей больше не передаётся. Настройки аккаунта Spectra доступны в собственном профиле.</p><form id="friendsSettingsForm"><label>Сервер друзей (HTTPS)<input id="friendsEndpoint" placeholder="https://spectra-friends.example.workers.dev" value="${esc(state.friendsEndpoint||'')}"></label><label><input id="shareActivity" type="checkbox" ${state.shareGameActivity!==false?'checked':''}> Показывать друзьям игру, версию, мир и адрес сервера</label><div class="form-actions"><button class="primary">Сохранить сервер друзей</button></div></form></div>`);$('#friendsSettingsForm').onsubmit=e=>{e.preventDefault();run(async()=>{updateState(await api('friendsSettings',{endpoint:$('#friendsEndpoint').value.trim(),shareActivity:$('#shareActivity').checked,hideOnline:state.hideOnlineStatus===true}));toast('Настройки друзей сохранены');});};}
 let loginAttempt=0;
 function registration(){
  if(!state.profile){toast('Сначала войдите в свой Minecraft-профиль');return;}
  const ticket=++loginAttempt;
  modal(`${closeButton()}<div class="network-registration"><span class="spectra-logo" aria-hidden="true"></span><div class="eyebrow">SPECTRA NETWORK</div><h2>Подключиться к сети Spectra</h2><p>Создайте аккаунт Spectra для друзей и совместной игры. При первом входе через Google он зарегистрируется автоматически.</p><button id="networkGoogleLogin" class="primary google-login"><span aria-hidden="true">G</span> Продолжить с Google</button><p class="muted">Вход откроется в обычном браузере. Пароль Google не передаётся Spectra. Используем только базовый профиль и подтверждённый адрес почты.</p><p class="muted">Minecraft-аккаунт остаётся для запуска игры; его ник в сети Spectra будет неподтверждённым.</p><p id="networkLoginStatus" role="status"></p></div>`);
  $('#networkGoogleLogin').onclick=()=>run(async()=>{
   const button=$('#networkGoogleLogin'),label=$('#networkLoginStatus');button.disabled=true;label.textContent='Открываем Google в браузере…';
   try{const started=await api('networkBegin');if(ticket!==loginAttempt||!$('#networkLoginStatus')||!$('#modal').open)return;label.textContent='Завершите вход Google в браузере. Ожидаем подключение…';
    const expires=Date.now()+600000;
    async function poll(){if(ticket!==loginAttempt||!$('#networkLoginStatus')||!$('#modal').open)return;
     try{if(Date.now()>expires)throw Error('Вход истёк. Нажмите Google ещё раз.');const result=await api('networkPoll',{flowId:started.flowId});if(ticket!==loginAttempt||!$('#networkLoginStatus')||!$('#modal').open)return;
      if(result.status==='connected'){updateState(result.state);$('#modal').close();toast('Вы подключились к сети Spectra');if(page==='profile')renderProfile();return;}setTimeout(poll,2000);
     }catch(e){if(ticket===loginAttempt&&$('#networkLoginStatus')){label.textContent=e.message||String(e);button.disabled=false;}}
    }setTimeout(poll,1500);
   }catch(e){label.textContent=e.message||String(e);button.disabled=false;}
  });
 }
 function ownAccount(){const host=$('#networkAccountSettings');if(!host)return;const account=state.networkAccount;
  host.innerHTML=`<h2>Аккаунт Spectra</h2>${account?`<p>Подключено через Google: <span data-no-i18n>${esc(account.email)}</span></p><p class="muted">ID Spectra: ${esc(account.id)}</p><label>Уникальное имя Spectra<input id="networkHandle" value="${esc(account.name)}" minlength="3" maxlength="24" pattern="[A-Za-z0-9_]{3,24}"></label><div class="toolbar"><button id="saveNetworkHandle">Сохранить имя Spectra</button><button id="networkDisconnect">Отключиться от сети Spectra</button></div><p class="muted">Minecraft: ${esc(account.minecraftName||state.profile?.name||'')} · не подтверждён. Друзья привязаны к ID Spectra.</p>`:'<p>Подключитесь к сети, чтобы добавлять друзей и показывать игровую активность.</p><button id="networkConnect" class="primary">Подключиться к сети Spectra</button>'}`;
  host.insertAdjacentHTML('beforeend',`<form id="friendPrivacy" class="friend-privacy"><h3>Видимость для друзей</h3><label><input id="hideSpectraOnline" type="checkbox" ${state.hideOnlineStatus?'checked':''}> Скрывать статус сети</label><label><input id="hideSpectraGame" type="checkbox" ${state.shareGameActivity===false?'checked':''}> Скрывать игровую активность</label><p class="muted">Скрытый статус сети также скрывает игру. Скрытая игровая активность убирает версию, адрес сервера и доступ к сборке.</p><button type="submit">Сохранить видимость</button></form>`);
  $('#friendPrivacy').onsubmit=e=>{e.preventDefault();run(async()=>{updateState(await api('friendsSettings',{endpoint:state.friendsEndpoint,hideOnline:$('#hideSpectraOnline').checked,shareActivity:!$('#hideSpectraGame').checked}));toast('Видимость обновлена');ownAccount();});};
 $('#networkConnect')?.addEventListener('click',registration);$('#saveNetworkHandle')?.addEventListener('click',()=>run(async()=>{updateState(await api('networkAccount',{name:$('#networkHandle').value.trim()}));ownAccount();toast('Имя Spectra сохранено');}));$('#networkDisconnect')?.addEventListener('click',()=>run(async()=>{updateState(await api('networkLogout'));items=[];ownAccount();toast('Вы отключились от сети Spectra');}));
 }
 function profile(player,own){if(!player)return;if(own){ownAccount();return;}$('#profileFriendRequest')?.addEventListener('click',()=>playerBrowser(player.name));if(!state.networkAccount)return;api('friends').then(data=>{if(displayedProfile?.id!==player.id)return;const friends=data.items?.filter(f=>f.minecraftId===player.id&&f.relation==='friend')||[];if($('#profileOnline'))$('#profileOnline').textContent=friends.length?friends.map(f=>f.name+': '+status(f)+' · Minecraft-ник не подтверждён').join('; '):'Статус доступен друзьям Spectra';}).catch(()=>{});}
 $('#friendsButton').onclick=()=>{if(!panel.hidden&&!closing){hidePanel();return;}showPanel();$('#accountMenu').hidden=true;if(items.length)draw();else panel.innerHTML='<div class="friends-loading"><span class="spectra-logo"></span><p>Получаем друзей…</p></div>';refresh();};
 document.addEventListener('pointerdown',e=>{if(!e.target.closest('#friendsPanel,#friendsButton'))hidePanel();});
 document.addEventListener('keydown',e=>{if(e.key==='Escape')hidePanel();});setInterval(()=>{if(!panel.hidden&&!closing)refresh();},10000);
 window.SpectraFriends={settings,profile,registration};
})();
