'use strict';
(()=>{
 let tab='friends',refreshing=false,items=[],request=0;
 const panel=$('#friendsPanel');
 function status(friend){if(!friend.online)return 'Не в сети';const p=friend.presence;if(!p?.playing)return 'В сети · Spectra';return `Minecraft ${p.version} · ${p.loader} ${p.loaderVersion||''}${p.targetKind==='worlds'?' · Запущен мир: '+p.target:p.targetKind==='servers'?' · Запущен сервер: '+p.target:p.targetKind==='lan'?' · LAN: '+p.target:''}`;}
 async function refresh(){if(refreshing||panel.hidden)return;refreshing=true;const ticket=++request;try{const result=await api('friends');if(ticket!==request||panel.hidden)return;items=result.items||[];draw();}catch(e){if(!panel.hidden)panel.innerHTML=`<h2>Друзья</h2><p>${esc(e.message)}</p><button id="friendsSetup">Настройки сервера</button>`;$('#friendsSetup')?.addEventListener('click',()=>{panel.hidden=true;navigate('settings');});}finally{refreshing=false;}}
 function draw(){
 const rows=items.filter(f=>tab==='friends'?f.relation==='friend':f.relation!=='friend');
 panel.innerHTML=`<div class="section-label"><h2>Друзья</h2><button id="friendsClose" aria-label="Закрыть">×</button></div><div class="friends-tabs"><button id="myFriends" class="${tab==='friends'?'active':''}">Мои друзья</button><button id="friendRequests" class="${tab==='requests'?'active':''}">Запросы (${items.filter(f=>f.relation==='incoming').length})</button></div><div class="friends-list">${rows.map(f=>`<article class="friend-row"><button data-friend-profile="${esc(f.id)}" class="friend-avatar">${esc(f.name[0])}</button><div class="friend-details"><button class="text-button" data-friend-profile="${esc(f.id)}" data-no-i18n>${esc(f.name)}</button><small class="${f.online?'friend-online':'muted'}">${esc(f.relation==='incoming'?'Входящий запрос':f.relation==='outgoing'?'Ожидает подтверждения':status(f))}</small><div>${f.relation==='incoming'?`<button data-friend-op="accept" data-id="${esc(f.id)}">Принять</button><button data-friend-op="decline" data-id="${esc(f.id)}">Отклонить</button>`:f.relation==='outgoing'?`<button data-friend-op="cancel" data-id="${esc(f.id)}">Отменить</button>`:`${f.online&&['servers','lan'].includes(f.presence?.targetKind)?`<button data-friend-join="${esc(f.id)}">Подключиться</button>`:''}<button data-friend-op="remove" data-id="${esc(f.id)}">Удалить</button>`}</div></div></article>`).join('')||'<p class="muted">Список пуст</p>'}</div><div class="friends-actions"><button id="addFriend">Добавить друга</button><button id="shareLan">Поделиться LAN-миром</button></div>`;
 $('#friendsClose').onclick=()=>{panel.hidden=true;};$('#myFriends').onclick=()=>{tab='friends';draw();};$('#friendRequests').onclick=()=>{tab='requests';draw();};$('#addFriend').onclick=playerBrowser;$('#shareLan').onclick=shareLan;
 $$('[data-friend-op]').forEach(b=>b.onclick=()=>run(async()=>{if(b.dataset.friendOp==='remove'){const friend=items.find(f=>f.id===b.dataset.id);confirmAction('Удалить друга?',friend?.name||'',async()=>{await api('friendAction',{id:b.dataset.id,operation:'remove'});panel.hidden=false;await refresh();});return;}b.disabled=true;await api('friendAction',{id:b.dataset.id,operation:b.dataset.friendOp});await refresh();}));
 $$('[data-friend-profile]').forEach(b=>b.onclick=()=>run(async()=>{const friend=items.find(f=>f.id===b.dataset.friendProfile);const player=await api('player',{name:friend.name});panel.hidden=true;await navigate('profile');renderProfile(player);}));
 $$('[data-friend-join]').forEach(b=>b.onclick=()=>join(items.find(f=>f.id===b.dataset.friendJoin)));
 }
 function playerBrowser(){panel.hidden=true;modal(`${closeButton()}<h2>Найти друга</h2><p>Введите Minecraft-ник. Профиль и история доступны через Crafty. Игрок должен подключить Spectra к тому же серверу друзей.</p><form id="friendSearchForm" class="toolbar"><input id="friendNickname" placeholder="Ник игрока" minlength="3" maxlength="16" required pattern="[A-Za-z0-9_]{3,16}"><button class="primary">Найти</button></form><div id="friendSearchResult"></div><button id="friendCrafty">Открыть браузер игроков Crafty ↗</button>`);$('#friendCrafty').onclick=()=>run(()=>api('external',{url:'https://crafty.gg/players'}));$('#friendSearchForm').onsubmit=e=>{e.preventDefault();run(async()=>{const player=await api('player',{name:$('#friendNickname').value.trim()});$('#friendSearchResult').innerHTML=`<div class="panel"><h3 data-no-i18n>${esc(player.name)}</h3><button id="sendFriendRequest">Отправить запрос</button><button id="openFriendProfile">Открыть профиль</button></div>`;$('#sendFriendRequest').onclick=()=>run(async()=>{await api('friendAction',{id:player.id,operation:'request'});$('#modal').close();toast('Запрос дружбы отправлен');panel.hidden=false;tab='requests';await refresh();});$('#openFriendProfile').onclick=async()=>{$('#modal').close();await navigate('profile');renderProfile(player);};});};}
 function join(friend){const p=friend.presence,knownPack=!!(p.packSource&&p.packId&&p.packVersion);panel.hidden=true;modal(`${closeButton()}<h2>Подключиться к ${esc(friend.name)}</h2><p>${esc(status(friend))}</p><p>${knownPack?'Можно скачать ту же опубликованную версию модпака. Изменения, внесённые другом вручную, не передаются.':'Для пользовательской сборки выберите свою совместимую сборку. Состав модов должен подходить серверу.'}</p>${knownPack?'<label><input type="checkbox" id="downloadFriendPack"> Скачать сборку, если её ещё нет</label>':`<label>Сборка<select id="friendInstance"><option value="vanilla">Minecraft без модов</option>${state.instances.map(i=>`<option value="${esc(i.id)}">${esc(i.name)} · ${esc(i.version)} · ${esc(i.loader)}</option>`).join('')}</select></label>`}<button id="joinFriendGame" class="primary">Подключиться</button><p class="muted">Адрес относится к запуску через лаунчер; друг мог сменить сервер внутри игры. LAN работает только в одной локальной сети.</p>`);$('#joinFriendGame').onclick=()=>run(async()=>{const b=$('#joinFriendGame');b.disabled=true;try{updateState(await api('joinFriend',{id:friend.id,download:$('#downloadFriendPack')?.checked||false,instanceId:$('#friendInstance')?.value||''}));$('#modal').close();navigate('instances');}finally{b.disabled=false;}});}
 function shareLan(){panel.hidden=true;modal(`${closeButton()}<h2>Поделиться LAN-миром</h2><p>В Minecraft нажмите «Открыть для сети». Укажите IPv4 компьютера и порт, показанный игрой. Друзья должны находиться в той же сети; Windows должна разрешать Java входящие подключения.</p><input id="lanAddress" placeholder="192.168.1.5:54321"><button id="saveLan" class="primary">Показать друзьям</button><button id="clearLan">Убрать адрес</button>`);$('#saveLan').onclick=()=>run(async()=>{await api('shareLan',{address:$('#lanAddress').value.trim()});$('#modal').close();toast('LAN-адрес доступен друзьям');});$('#clearLan').onclick=()=>run(async()=>{await api('shareLan',{address:''});$('#modal').close();});}
 function settings(host){host.insertAdjacentHTML('beforeend',`<div class="panel settings-section"><h2>Друзья Spectra</h2><p>Все друзья должны подключаться к одному серверу. Владелец этого сервера получает Minecraft access token для проверки аккаунта; используйте только свой или доверенный сервер.</p><form id="friendsSettingsForm"><label>Сервер друзей (HTTPS)<input id="friendsEndpoint" placeholder="https://spectra-friends.example.workers.dev" value="${esc(state.friendsEndpoint||'')}"></label><label><input id="shareActivity" type="checkbox" ${state.shareGameActivity!==false?'checked':''}> Показывать друзьям игру, версию, мир и адрес сервера</label><div class="form-actions"><button class="primary">Сохранить сервер друзей</button></div></form></div>`);$('#friendsSettingsForm').onsubmit=e=>{e.preventDefault();run(async()=>{updateState(await api('friendsSettings',{endpoint:$('#friendsEndpoint').value.trim(),shareActivity:$('#shareActivity').checked}));toast('Настройки друзей сохранены');});};}
 function profile(player,own){if(!player||own)return;$('#profileFriendRequest')?.addEventListener('click',()=>run(async()=>{await api('friendAction',{id:player.id,operation:'request'});toast('Запрос дружбы отправлен');}));if(!state.friendsEndpoint)return;api('friends').then(data=>{if(displayedProfile?.id!==player.id)return;const friend=data.items?.find(f=>f.id===player.id&&f.relation==='friend');if($('#profileOnline'))$('#profileOnline').textContent=friend?status(friend):'Статус доступен друзьям';}).catch(()=>{});}
 $('#friendsButton').onclick=()=>{panel.hidden=!panel.hidden;if(!panel.hidden){$('#accountMenu').hidden=true;panel.innerHTML='<p>Получаем друзей…</p>';refresh();}};
 document.addEventListener('pointerdown',e=>{if(!e.target.closest('#friendsPanel,#friendsButton')){panel.hidden=true;request++;}});
 document.addEventListener('keydown',e=>{if(e.key==='Escape')panel.hidden=true;});setInterval(()=>{if(!panel.hidden)refresh();},30000);
 window.SpectraFriends={settings,profile};
})();
