'use strict';
const SpectraProjects=(()=>{
 let request=0;
 const https=url=>{try{const u=new URL(url);return u.protocol==='https:'&&!u.username&&!u.password?u.href:'';}catch{return '';}};
 function description(content,format){
  if(format!=='html')return String(content||'').split(/\n\s*\n/).map(p=>/^#{1,3} /.test(p)?`<h3>${esc(p.replace(/^#{1,3} /,''))}</h3>`:`<p>${esc(p)}</p>`).join('');
  const source=new DOMParser().parseFromString(String(content||''),'text/html');
  function node(n){if(n.nodeType===3)return esc(n.textContent);if(n.nodeType!==1)return '';const tag=n.tagName.toLowerCase();if(['script','style','iframe','object','embed','form','input','button','svg','math'].includes(tag))return '';const text=[...n.childNodes].map(node).join('');if(tag==='a'){const url=https(n.getAttribute('href'));return url?`<a href="${esc(url)}" data-project-link="${esc(url)}">${text}</a>`:text;}if(tag==='img'){const url=https(n.getAttribute('src'));return url?image(url,'description-image'):'';}if(['p','h1','h2','h3','h4','ul','ol','li','strong','em','code','pre','blockquote','br','hr','table','tbody','tr','td','th'].includes(tag))return `<${tag}>${text}</${tag}>`;return text;}
  return [...source.body.childNodes].map(node).join('');
 }
 async function open(source,id,kind,instanceId=''){
  const ticket=++request,overlay=kind!=='modpacks',view=++viewSeq;
  const loading=`${overlay?closeButton():''}<div class="project-loading">${empty('Открываем страницу','Получаем описание, авторов и скриншоты…')}</div>`;
  if(overlay){modal(loading);$('#modal').classList.add('project-dialog');}else{$('#main').innerHTML='<section>'+loading+'</section>';}
  try{
   const p=await api('projectDetails',{source,projectId:id,kind,instanceId});if(ticket!==request||view!==viewSeq||overlay&&!$('#modal').open)return;
   const screenshots=(p.screenshots||[]).filter(s=>https(s.url)),authors=p.authors||[],versions=p.versions||[];
   const html=`${overlay?closeButton():''}<article class="project-page"><button id="projectBack" class="text-button">← Назад к каталогу</button><header class="project-header"><div class="project-avatar">${image(p.icon)||pixelIcon('cube')}</div><div><div class="eyebrow">${esc(source.toUpperCase())} · ${esc(kind==='modpacks'?'МОДПАК':kind==='mods'?'МОД':kind==='shaders'?'ШЕЙДЕР':'РЕСУРС ПАК')}</div><h1 data-no-i18n>${esc(p.title)}</h1><p data-no-i18n>${esc(p.summary)}</p></div></header><div class="project-body"><div><div class="project-gallery">${screenshots.length?`<button id="projectHero" title="Открыть скриншот">${image(screenshots[0].url)}</button><div class="project-thumbnails">${screenshots.map((s,i)=>`<button data-project-shot="${i}" aria-label="${esc(s.caption||'Скриншот '+(i+1))}">${image(s.url)}</button>`).join('')}</div><p class="muted" id="projectCaption" data-no-i18n>${esc(screenshots[0].caption)}</p>`:'<div class="project-no-gallery">Автор не добавил скриншоты</div>'}</div><div class="project-tabs"><button data-project-tab="description" class="active">Описание</button><button data-project-tab="versions">Версии (${versions.length})</button></div><div class="project-description" id="projectDescription" data-no-i18n>${description(p.description,p.format)||'<p>Описание отсутствует.</p>'}</div><div id="projectVersions" hidden>${versions.map(v=>`<div class="project-version"><div><strong data-no-i18n>${esc(v.name)}</strong><small data-no-i18n>${esc(v.version)}</small><p class="muted" data-no-i18n>${esc((v.game||[]).join(' · '))}</p></div><small>${date(v.date)}</small></div>`).join('')||'<p>Совместимых версий нет.</p>'}</div></div><aside class="project-sidebar"><button id="projectInstall" class="primary">${pixelIcon('down')} ${kind==='modpacks'?'Установить сборку':'Установить'}</button>${instanceId?`<p class="muted">${esc(findInstance(instanceId).version)} · ${esc(findInstance(instanceId).loader)}</p>`:''}<dl><dt>Загрузки</dt><dd>${Intl.NumberFormat(SpectraAppearance.language()).format(p.downloads||0)}</dd><dt>Создан</dt><dd>${date(p.created)}</dd><dt>Обновлён</dt><dd>${date(p.updated)}</dd><dt>Лицензия</dt><dd data-no-i18n>${esc(p.license||'Не указана')}</dd></dl><h3>Авторы</h3>${authors.map(a=>`<button class="project-author text-button" data-project-link="${esc(https(a.url))}" data-no-i18n>${esc(a.name)}<small>${esc(a.role||'Автор')}</small></button>`).join('')||'<p>Не указаны</p>'}<div class="project-categories">${(p.categories||[]).map(c=>`<span class="pill" data-no-i18n>${esc(c)}</span>`).join('')}</div>${https(p.url)?`<button data-project-link="${esc(https(p.url))}">Открыть на ${esc(source==='modrinth'?'Modrinth':'CurseForge')} ↗</button>`:''}<p class="muted">Установка выбирает совместимый файл и обязательные зависимости.</p></aside></div></article>`;
   const host=overlay?$('#modalContent'):$('#main');host.innerHTML=overlay?html:'<section>'+html+'</section>';$('.modal-close')?.addEventListener('click',()=>$('#modal').close());
   const back=()=>{if(overlay)catalogModal(kind,instanceId);else navigate('discover');};$('#projectBack').onclick=back;
   let shot=0;host.querySelectorAll('[data-project-shot]').forEach(b=>b.onclick=()=>{shot=Number(b.dataset.projectShot);$('#projectHero').innerHTML=image(screenshots[shot].url);$('#projectCaption').textContent=screenshots[shot].caption||'';host.querySelectorAll('[data-project-shot]').forEach(x=>x.classList.toggle('active',x===b));});
   $('#projectHero')?.addEventListener('click',()=>{const gallery=document.createElement('dialog');gallery.className='project-image-dialog';gallery.innerHTML=`<button class="modal-close" aria-label="Закрыть">×</button><img src="${esc(screenshots[shot].url)}" alt="${esc(screenshots[shot].caption||'Скриншот')}">`;document.body.append(gallery);gallery.querySelector('button').onclick=()=>gallery.close();gallery.onclose=()=>gallery.remove();gallery.showModal();});
   host.querySelectorAll('[data-project-tab]').forEach(b=>b.onclick=()=>{const versions=b.dataset.projectTab==='versions';$('#projectDescription').hidden=versions;$('#projectVersions').hidden=!versions;host.querySelectorAll('[data-project-tab]').forEach(x=>x.classList.toggle('active',x===b));});
   host.querySelectorAll('[data-project-link]').forEach(b=>b.onclick=e=>{e.preventDefault();const url=https(b.dataset.projectLink);if(url)run(()=>api('openLink',{url}));});
   $('#projectInstall').onclick=()=>run(async()=>{const b=$('#projectInstall');b.disabled=true;b.textContent='Загрузка…';try{if(kind==='modpacks'){updateState(await api('installPack',{source,projectId:id}));toast('Модпак добавлен в сборки');}else{await api('install',{source,projectId:id,kind,instanceId});toast('Дополнение установлено');}b.textContent='✓ Установлено';}catch(e){b.disabled=false;b.textContent='Повторить установку';throw e;}});
  }catch(e){if(ticket!==request||view!==viewSeq)return;const host=overlay?$('#modalContent'):$('#main');host.innerHTML=`${overlay?closeButton():''}<div class="empty"><h2>Не удалось открыть проект</h2><p>${esc(e.message)}</p><button id="projectRetry">Повторить</button><button id="projectBack">Назад</button></div>`;$('#projectRetry').onclick=()=>open(source,id,kind,instanceId);$('#projectBack').onclick=()=>overlay?catalogModal(kind,instanceId):navigate('discover');$('.modal-close')?.addEventListener('click',()=>$('#modal').close());}
 }
 return {open,description,https};
})();
