'use strict';
const SpectraShell=(()=>{
 let signature='';
 function refresh(){const host=$('#steamLibrary');if(!host)return;const rows=state.instances||[],next=JSON.stringify([rows.map(i=>[i.id,i.name,i.version,i.icon]),state.selection]);if(next===signature)return;signature=next;host.innerHTML=`<div class="steam-library-heading">Библиотека <span>${rows.length}</span></div><label class="steam-library-search"><input id="steamLibrarySearch" placeholder="Поиск сборки…" aria-label="Поиск в библиотеке"></label><div class="steam-library-actions"><button id="steamLibraryCreate">＋ Создать сборку</button><button id="steamLibraryDiscover">Обзор модпаков</button></div><div class="steam-library-list">${rows.map(i=>`<button data-steam-instance="${esc(i.id)}" class="${state.selection?.instanceId===i.id&&state.selection?.edition!=='bedrock'?'active':''}" data-search="${esc((i.name+' '+i.version).toLowerCase())}"><span>${image(i.icon)||pixelIcon('cube')}</span><div><strong data-no-i18n>${esc(i.name)}</strong><small data-no-i18n>${esc(i.version)} · ${esc(i.loader)}</small></div></button>`).join('')||'<p class="muted">Добавь первую сборку</p>'}</div>`;$('#steamLibraryCreate').onclick=()=>instanceModal();$('#steamLibraryDiscover').onclick=()=>navigate('discover');$('#steamLibrarySearch').oninput=e=>host.querySelectorAll('[data-steam-instance]').forEach(b=>b.hidden=!b.dataset.search.includes(e.target.value.toLowerCase()));host.querySelectorAll('[data-steam-instance]').forEach(b=>b.onclick=()=>run(async()=>{await choose('',b.dataset.steamInstance);openEditor(b.dataset.steamInstance,'version');}));}
 // Toasts keep an explicit close action and restart their appearance animation.
 const notifications=[];const noticePanel=$('#notificationsPanel'),noticeButton=$('#notificationsButton');
 function drawNotifications(){if(!noticePanel)return;noticePanel.innerHTML=`<div class="notification-heading"><h2>Уведомления</h2><button id="clearNotifications">Очистить</button><button id="closeNotifications" aria-label="Закрыть">×</button></div><div class="notification-list">${notifications.map(n=>`<article><span aria-hidden="true">◇</span><div><p>${esc(n.message)}</p><small>${new Date(n.time).toLocaleTimeString(SpectraAppearance.language(),{hour:'2-digit',minute:'2-digit'})}</small></div></article>`).join('')||'<div class="friends-empty"><p>Новых уведомлений нет</p><small>Здесь появятся результаты действий лаунчера</small></div>'}</div>`;$('#clearNotifications').onclick=()=>{notifications.length=0;$('#notificationCount').hidden=true;drawNotifications();};$('#closeNotifications').onclick=()=>{noticePanel.hidden=true;noticeButton.setAttribute('aria-expanded','false');};}
 if(noticeButton)noticeButton.onclick=()=>{noticePanel.hidden=!noticePanel.hidden;noticeButton.setAttribute('aria-expanded',String(!noticePanel.hidden));if(!noticePanel.hidden){drawNotifications();noticePanel.animate?.([{opacity:0,transform:'translateY(-5px)'},{opacity:1,transform:'translateY(0)'}],{duration:motionMs(160)});}};
 document.addEventListener('pointerdown',e=>{if(noticePanel&&!e.target.closest('#notificationsPanel,#notificationsButton')){noticePanel.hidden=true;noticeButton.setAttribute('aria-expanded','false');}});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&noticePanel){noticePanel.hidden=true;noticeButton.setAttribute('aria-expanded','false');}});
 const originalToast=toast;
 toast=message=>{notifications.unshift({message:String(message),time:Date.now()});if(notifications.length>50)notifications.pop();const count=$('#notificationCount');if(count){count.textContent=String(notifications.length);count.hidden=false;}if(noticePanel&&!noticePanel.hidden)drawNotifications();originalToast(message);const host=$('#toast');host.innerHTML=`<span class="notification-mark" aria-hidden="true">◇</span><span class="notification-message">${esc(message)}</span><button aria-label="Закрыть уведомление" id="dismissToast">×</button>`;$('#dismissToast').onclick=()=>{clearTimeout(toast.timer);host.hidden=true;};host.animate?.([{opacity:0,transform:'translate(-50%, 8px)'},{opacity:1,transform:'translate(-50%, 0)'}],{duration:motionMs(180)});};
 refresh();return {refresh};
})();
