using System.IO;
using System.Text.Json.Nodes;
namespace Spectra;
public sealed class LibraryActions(Store store,GameService game)
{
 void Writable(string id){if(game.Running.ContainsKey(id))throw new IOException("Закройте Minecraft перед изменениями");}
 public string PathFor(string id,string kind,string relative){var root=store.Folder(store.Get(id));var dir=Path.GetFullPath(Path.Combine(root,GameService.KindFolder(kind)));var path=Store.SafePath(root,relative);if(!path.StartsWith(dir+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase))throw new IOException("Файл вне выбранной категории");return path;}
 public void Enable(string id,string kind,string[] paths,bool enabled){Writable(id);if(kind is not ("mods" or "shaders" or "resources"))throw new IOException("Неизвестная категория");var moves=paths.Distinct().Select(p=>PathFor(id,kind,p)).Where(p=>p.EndsWith(".disabled",StringComparison.OrdinalIgnoreCase)==enabled).Select(p=>(From:p,To:enabled?p[..^9]:p+".disabled")).ToArray();foreach(var move in moves){if(!File.Exists(move.From)||File.Exists(move.To))throw new IOException("Невозможно переименовать "+Path.GetFileName(move.From));}var completed=new List<(string From,string To)>();try{foreach(var move in moves){File.Move(move.From,move.To);completed.Add(move);}}catch{foreach(var move in completed.AsEnumerable().Reverse())File.Move(move.To,move.From);throw;}}
 public void Server(string id,string operation,int index,string name,string address){Writable(id);var file=Path.Combine(store.Folder(store.Get(id)),"servers.dat");var root=Nbt.Load(file)??new Dictionary<string,object>();var list=root.GetValueOrDefault("servers") as List<object>??new Nbt.NbtList(10);root["servers"]=list;if(operation!="add"&&(index<0||index>=list.Count))throw new IOException("Сервер не найден");if(operation=="delete"){list.RemoveAt(index);}else{if(name.Trim().Length is <1 or >100||address.Trim().Length is <1 or >255||address.Any(char.IsWhiteSpace))throw new IOException("Проверьте название и адрес сервера");var entry=operation=="add"?new Dictionary<string,object>():list[index] as Dictionary<string,object>??throw new IOException("Некорректный сервер");entry["name"]=name.Trim();entry["ip"]=address.Trim();if(operation=="add")list.Add(entry);}Nbt.Save(file,root);}
 public void RenameWorld(string id,string relative,string name){Writable(id);if(name.Trim().Length is <1 or >100)throw new IOException("Проверьте имя мира");var level=Path.Combine(PathFor(id,"worlds",relative),"level.dat");var root=Nbt.Load(level)??throw new IOException("Не найден level.dat");var data=root.GetValueOrDefault("Data") as Dictionary<string,object>??throw new IOException("Нет данных мира");data["LevelName"]=name.Trim();Nbt.Save(level,root,true);}
 public void DeleteWorld(string id,string relative){Writable(id);Directory.Delete(PathFor(id,"worlds",relative),true);}
 public void ImportWorld(string id,string folder){Writable(id);if(!File.Exists(Path.Combine(folder,"level.dat")))throw new IOException("Выберите папку мира с level.dat");var saves=Path.Combine(store.Folder(store.Get(id)),"saves");Directory.CreateDirectory(saves);var target=Path.Combine(saves,Path.GetFileName(folder)+"-"+Guid.NewGuid().ToString("N")[..6]);try{foreach(var file in Directory.EnumerateFiles(folder,"*",new EnumerationOptions{RecurseSubdirectories=true,AttributesToSkip=FileAttributes.ReparsePoint})){if((File.GetAttributes(file)&FileAttributes.ReparsePoint)!=0)throw new IOException("Ссылки внутри мира не поддерживаются");var dest=Store.SafePath(target,Path.GetRelativePath(folder,file));Directory.CreateDirectory(Path.GetDirectoryName(dest)!);File.Copy(file,dest);}}catch{if(Directory.Exists(target))Directory.Delete(target,true);throw;}}
 public void RenameScreenshot(string id,string relative,string name){var path=PathFor(id,"screenshots",relative);if(string.IsNullOrWhiteSpace(name)||name.IndexOfAny(Path.GetInvalidFileNameChars())>=0||name is "." or "..")throw new IOException("Некорректное имя файла");var ext=Path.GetExtension(path);if(!name.EndsWith(ext,StringComparison.OrdinalIgnoreCase))name+=ext;File.Move(path,Path.Combine(Path.GetDirectoryName(path)!,name),false);}
 public void DeleteInstance(string id){Writable(id);if(id=="vanilla")throw new IOException("Нельзя удалить обычный Minecraft");var instance=store.Get(id);var folder=Path.GetDirectoryName(store.Folder(instance))!;Directory.Delete(folder,true);store.Config.Instances.Remove(instance);if(store.Config.SelectedInstance==id)store.Config.SelectedInstance="";store.Save();}
}
